import type { JobRecord } from "@/lib/jobs/types";

export const memory = new Map<string, JobRecord>();

export const READ_CACHE_MS = 3_000;

export const REROUTE_AFTER_MS = 60_000;
export const REROUTE_WINDOW_MS = 15 * 60_000;
export const DEFER_DURATION_MS = 5 * 60_000;

export const FLOW_STATUSES = new Set<string>([
  "waiting_for_selected",
  "selected_review",
  "sequential_pairing",
  "waiting_for_pro",
  "reserved",
  "negotiating",
  "searching",
  "agreed",
  "paid_booked",
  "en_route",
  "arrived",
  "in_progress",
  "completed",
  "satisfied",
  "released",
  "cancelled",
  "expired",
  "disputed",
  "under_appeal",
  "refunded",
]);

export const PRO_ACTIONABLE_LIST_STATUSES = [
  "negotiating",
  "agreed",
  "paid_booked",
  "en_route",
  "arrived",
  "in_progress",
  "completed",
  "satisfied",
] as const;

export const LEAN_JOB_COLUMNS = [
  "id",
  "client_request_id",
  "motorist_id",
  "motorist_name",
  "motorist_photo",
  "motorist_vehicle",
  "vehicle_label",
  "repair_pro_id",
  "repair_pro_name",
  "repair_pro_photo",
  "service_type",
  "problem_text",
  "description",
  "flow_status",
  "status",
  "pricing_currency",
  "pro_base_major",
  "agreed_major",
  "amount_minor",
  "platform_fee_minor",
  "pro_payout_minor",
  "payment_id",
  "payment_reference",
  "escrow_status",
  "pickup_address",
  "pickup_lat",
  "pickup_lng",
  "pro_lat",
  "pro_lng",
  "eta_minutes",
  "distance_km",
  "eta_text",
  "distance_text",
  "pro_location_at",
  "motorist_location_at",
  "negotiate_ends_at",
  "max_offers",
  "offers",
  "status_history",
  "pairing_stage",
  "pairing_deadline",
  "queue_position",
  "remaining_candidates",
  "reservation_status",
  "assignment_status",
  "chosen_pro_id",
  "pairing_radius_km",
  "radius_km",
  "linked_request_id",
  "scheduled_dispatch_at",
  "dispatch_notified_at",
  "created_at",
  "updated_at",
  "paid_at",
  "released_at",
  "cancelled_at",
  "satisfied_at",
  "rating",
  "rating_note",
  "dispute",
  "evidence",
].join(", ");
