/**
 * Sample notifications for local/demo when API table empty.
 * Motorist vs Repair Pro sets differ.
 */

import type { AppNotification } from "@/lib/notifications/types";

function ago(mins: number): string {
  return new Date(Date.now() - mins * 60_000).toISOString();
}

/** 12+ samples spanning all categories */
export function localSampleNotifications(
  userId: string,
  role: "motorist" | "professional"
): AppNotification[] {
  if (role === "professional") {
    return [
      {
        id: "local-p1",
        userId,
        category: "requests",
        priority: "critical",
        title: "New service request",
        body: "Battery jump · Lekki Phase 1 · 1.2 km away",
        href: "/dashboard",
        actionType: "accept_request",
        groupKey: "req-demo-bat",
        jobId: "demo-job-p1",
        jobStatus: "negotiating",
        createdAt: ago(2),
      },
      {
        id: "local-p1b",
        userId,
        category: "requests",
        priority: "high",
        title: "Offer update",
        body: "Chioma countered your labour price.",
        href: "/dashboard",
        actionType: "open_job",
        groupKey: "req-demo-bat",
        jobId: "demo-job-p1",
        jobStatus: "negotiating",
        createdAt: ago(4),
      },
      {
        id: "local-p2",
        userId,
        category: "messages",
        priority: "normal",
        title: "Message from Ada",
        body: "I am by the red gate.",
        href: "/messages/demo-thread-p",
        actionType: "open_chat",
        jobId: "demo-job-p2",
        jobStatus: "en_route",
        messageText: "I am by the red gate.",
        createdAt: ago(8),
      },
      {
        id: "local-p3",
        userId,
        category: "payments",
        priority: "high",
        title: "Escrow ready",
        body: "Customer paid. ₦18,000 held — start trip when ready.",
        href: "/jobs",
        actionType: "open_job",
        createdAt: ago(15),
      },
      {
        id: "local-p4",
        userId,
        category: "payments",
        priority: "normal",
        title: "Payout released",
        body: "₦17,100 credited after platform fee (5%).",
        href: "/payments/history",
        actionType: "view_payment",
        createdAt: ago(40),
        readAt: ago(30),
      },
      {
        id: "local-p5",
        userId,
        category: "system",
        priority: "normal",
        title: "Documents under review",
        body: "Your certificate is being checked by Ona Care.",
        actionType: "none",
        createdAt: ago(60),
      },
      {
        id: "local-p6",
        userId,
        category: "system",
        priority: "high",
        title: "Go Live reminder",
        body: "You are Away. Go Live to receive nearby requests.",
        href: "/dashboard",
        actionType: "none",
        createdAt: ago(90),
      },
      {
        id: "local-p7",
        userId,
        category: "system",
        priority: "normal",
        title: "Rating received",
        body: "Ada rated you 5.0 · “On time and fair.”",
        actionType: "none",
        createdAt: ago(120),
        readAt: ago(100),
      },
      {
        id: "local-p8",
        userId,
        category: "requests",
        priority: "critical",
        title: "Safety alert",
        body: "Customer shared an SOS pin. Call support if needed.",
        href: "/jobs",
        actionType: "open_job",
        createdAt: ago(5),
      },
      {
        id: "local-p9",
        userId,
        category: "messages",
        priority: "normal",
        title: "Message from Emeka",
        body: "Great work. Thank you!",
        // Closed chat — full text inline only, no open_chat / href
        actionType: "none",
        href: null,
        jobId: "demo-job-p9",
        jobStatus: "released",
        messageText: "Great work. Thank you! Escrow should release shortly.",
        createdAt: ago(200),
      },
      {
        id: "local-p10",
        userId,
        category: "system",
        priority: "low",
        title: "System update",
        body: "Negotiation window is now 20 minutes for all trades.",
        actionType: "none",
        createdAt: ago(400),
        readAt: ago(350),
      },
    ];
  }

  // Motorist samples
  return [
    {
      id: "local-m1",
      userId,
      category: "requests",
      priority: "high",
      title: "Mechanic accepted",
      body: "Tunde A. accepted your battery request.",
      href: "/jobs/demo-job-m1",
      actionType: "open_job",
      groupKey: "job-m1",
      jobId: "demo-job-m1",
      jobStatus: "accepted",
      createdAt: ago(3),
    },
    {
      id: "local-m2",
      userId,
      category: "requests",
      priority: "high",
      title: "Mechanic en route",
      body: "Tunde is on the way · ETA 8 min.",
      href: "/jobs/demo-job-m1",
      actionType: "view_tracking",
      groupKey: "job-m1",
      jobId: "demo-job-m1",
      jobStatus: "en_route",
      createdAt: ago(6),
    },
    {
      id: "local-m3",
      userId,
      category: "requests",
      priority: "critical",
      title: "Mechanic arrived",
      body: "Your Repair Pro is on site. Meet them at the gate.",
      href: "/jobs/demo-job-m1",
      actionType: "view_tracking",
      groupKey: "job-m1",
      jobId: "demo-job-m1",
      jobStatus: "arrived",
      createdAt: ago(12),
    },
    {
      id: "local-m4",
      userId,
      category: "messages",
      priority: "normal",
      title: "Message from Tunde",
      body: "I am 5 minutes away. Stay put.",
      href: "/messages/demo-thread-1",
      actionType: "open_chat",
      jobId: "demo-job-m1",
      jobStatus: "en_route",
      messageText: "I am 5 minutes away. Stay put.",
      createdAt: ago(10),
    },
    {
      id: "local-m5",
      userId,
      category: "payments",
      priority: "high",
      title: "Escrow held",
      body: "₦12,500 labour fee is held safely until you confirm.",
      href: "/payments/history",
      actionType: "view_payment",
      createdAt: ago(25),
    },
    {
      id: "local-m6",
      userId,
      category: "payments",
      priority: "normal",
      title: "Payment released",
      body: "You confirmed the job. Escrow released to your Repair Pro.",
      href: "/payments/history",
      actionType: "view_payment",
      createdAt: ago(80),
      readAt: ago(70),
    },
    {
      id: "local-m7",
      userId,
      category: "requests",
      priority: "normal",
      title: "Job completed",
      body: "Mark satisfaction to release escrow.",
      // Finished job — View job shows closed popup (not live /jobs)
      href: "/jobs/demo-job-m2",
      actionType: "open_job",
      jobId: "demo-job-m2",
      jobStatus: "completed",
      createdAt: ago(90),
    },
    {
      id: "local-m8",
      userId,
      category: "system",
      priority: "normal",
      title: "Rate your Repair Pro",
      body: "How was Tunde’s service?",
      href: "/jobs/demo-job-m2",
      actionType: "rate",
      createdAt: ago(95),
    },
    {
      id: "local-m9",
      userId,
      category: "system",
      priority: "critical",
      title: "Safety / SOS",
      body: "If you feel unsafe, call emergency services. Ona Care is notified.",
      actionType: "none",
      createdAt: ago(1),
    },
    {
      id: "local-m10",
      userId,
      category: "messages",
      priority: "normal",
      title: "Message from Ada",
      body: "Thanks for confirming.",
      actionType: "none",
      href: null,
      jobId: "demo-job-m10",
      jobStatus: "released",
      messageText:
        "Thanks for confirming. Parts are sorted. Safe drive home!",
      createdAt: ago(150),
    },
    {
      id: "local-m11",
      userId,
      category: "system",
      priority: "low",
      title: "System update",
      body: "You can add multiple vehicles from Profile.",
      actionType: "none",
      createdAt: ago(500),
      readAt: ago(400),
    },
    {
      id: "local-m12",
      userId,
      category: "requests",
      priority: "normal",
      title: "Job started",
      body: "Work has begun on your vehicle.",
      href: "/jobs/demo-job-m1",
      actionType: "open_job",
      jobStatus: "in_progress",
      createdAt: ago(20),
      readAt: ago(18),
    },
  ];
}
