/**
 * Automedics live catalog the only inventory loaded into Ona Shop.
 * Every row is a real SKU from the Automedics price list.
 */

export const AUTOMEDICS_CATEGORIES = [
  { slug: "batteries", name: "Batteries" },
  { slug: "engine-oil", name: "Engine Oil" },
  { slug: "transmission-fluid", name: "Transmission Fluid" },
  { slug: "brake-fluid", name: "Brake Fluid" },
  { slug: "coolant", name: "Coolant" },
  { slug: "oil-filters", name: "Oil Filters" },
  { slug: "air-filters", name: "Air Filters" },
  { slug: "cabin-filters", name: "Cabin Filters" },
  { slug: "brake-pads", name: "Brake Pads" },
  { slug: "brake-discs", name: "Brake Discs" },
  { slug: "brake-linings", name: "Brake Linings" },
  { slug: "shock-absorbers", name: "Shock Absorbers" },
  { slug: "ball-joints", name: "Ball Joints" },
  { slug: "stabilizer-linkages", name: "Stabilizer Linkages" },
  {
    slug: "stabilizer-rubbers-bushings",
    name: "Stabilizer Rubbers & Bushings",
  },
  { slug: "tie-rod-ends-sockets", name: "Tie Rod Ends & Sockets" },
  { slug: "other-accessories", name: "Other / Accessories" },
] as const;

export type AutomedicsCategorySlug =
  (typeof AUTOMEDICS_CATEGORIES)[number]["slug"];

export type AutomedicsProduct = {
  sku: string;
  name: string;
  categorySlug: AutomedicsCategorySlug;
  /** Naira major units. null = contact for price. */
  priceMajor: number | null;
  vehicle: string;
  brand: string;
  imageKey: string;
  keywords: string[];
};

const CAT_IMAGE: Record<AutomedicsCategorySlug, string> = {
  batteries: "battery",
  "engine-oil": "engine-oil-5l",
  "transmission-fluid": "transmission-fluid",
  "brake-fluid": "brake-fluid",
  coolant: "coolant-green",
  "oil-filters": "oil-filter",
  "air-filters": "air-filter",
  "cabin-filters": "cabin-filter",
  "brake-pads": "brake-pads",
  "brake-discs": "brake-disc",
  "brake-linings": "brake-lining",
  "shock-absorbers": "shock-absorber",
  "ball-joints": "ball-joint",
  "stabilizer-linkages": "stabilizer-link",
  "stabilizer-rubbers-bushings": "bushing",
  "tie-rod-ends-sockets": "tie-rod",
  "other-accessories": "radiator-cap",
};

function tokens(name: string, vehicle: string, extra: string[] = []): string[] {
  const bag = new Set<string>();
  for (const w of `${name} ${vehicle}`.toLowerCase().split(/[^a-z0-9+]+/)) {
    if (w.length >= 2) bag.add(w);
  }
  for (const e of extra) bag.add(e.toLowerCase());
  return [...bag];
}

function p(
  sku: string,
  name: string,
  categorySlug: AutomedicsCategorySlug,
  priceMajor: number | null,
  vehicle: string,
  brand = "Automedics",
  imageKey?: string,
): AutomedicsProduct {
  return {
    sku,
    name,
    categorySlug,
    priceMajor,
    vehicle,
    brand,
    imageKey: imageKey || CAT_IMAGE[categorySlug],
    keywords: tokens(name, vehicle, [brand, categorySlug.replace(/-/g, " ")]),
  };
}

export const AUTOMEDICS_PRODUCTS: AutomedicsProduct[] = [
  // 1. Batteries
  p("ATM-BAT-100AMH", "100 AMH Battery", "batteries", 110000, "General"),
  p("ATM-BAT-75AMH", "75 AMH Battery", "batteries", 85000, "General"),

  // 2. Engine Oil
  p(
    "ATM-OIL-5W20-5L",
    "5W-20 5 Litres Premium",
    "engine-oil",
    52000,
    "General",
    "Automedics",
    "engine-oil-5l",
  ),
  p(
    "ATM-OIL-5W20-1L",
    "5W-20 1 Litre Premium",
    "engine-oil",
    13000,
    "General",
    "Automedics",
    "engine-oil-1l",
  ),
  p(
    "ATM-OIL-5W30-5L",
    "5W-30 5 Litres Premium",
    "engine-oil",
    52000,
    "General",
    "Automedics",
    "engine-oil-5l",
  ),
  p(
    "ATM-OIL-5W30-1L",
    "5W-30 1 Litre Premium",
    "engine-oil",
    13000,
    "General",
    "Automedics",
    "engine-oil-1l",
  ),

  // 3. Transmission Fluid
  p("ATM-ATF-TIV-4L", "ATF T-IV 4L", "transmission-fluid", 25000, "General"),
  p(
    "ATM-ATF-WS-4L",
    "ATF WS 4L (Mannol)",
    "transmission-fluid",
    25000,
    "General",
    "Mannol",
  ),
  p(
    "ATM-ATF-DW1",
    "DW1 Transmission Oil",
    "transmission-fluid",
    8000,
    "General",
  ),
  p("ATM-ATF-DEXRON-VI", "Dexron VI", "transmission-fluid", null, "General"),
  p(
    "ATM-ATF-DEXIII",
    "Dexiii Transmission Oil",
    "transmission-fluid",
    7000,
    "General",
  ),

  // 4. Brake Fluid
  p("ATM-BF-DOT3", "DOT3 Brake Fluid", "brake-fluid", 4000, "General"),
  p("ATM-BF-DOT4", "DOT4 Brake Fluid", "brake-fluid", 4500, "General"),

  // 5. Coolant
  p(
    "ATM-COOL-GREEN",
    "Green Radiator Coolant",
    "coolant",
    7000,
    "General",
    "Automedics",
    "coolant-green",
  ),
  p(
    "ATM-COOL-RED",
    "Red Radiator Coolant",
    "coolant",
    7000,
    "General",
    "Automedics",
    "coolant-red",
  ),

  // 6. Oil Filters
  p(
    "ATM-OF-001",
    "ATM 001 Automedics Oil Filter",
    "oil-filters",
    2000,
    "General",
  ),
  p("ATM-OF-002", "ATM 002 Automedics Filter", "oil-filters", 2000, "General"),
  p(
    "ATM-OF-003",
    "ATM 003 Automedics Oil Filter",
    "oil-filters",
    2000,
    "General",
  ),
  p(
    "ATM-OF-501",
    "ATM 501 Automedics Oil Filter",
    "oil-filters",
    3500,
    "General",
  ),
  p("ATM-OF-502", "ATM 502 Automedics Filter", "oil-filters", 3500, "General"),
  p(
    "ATM-OF-503",
    "ATM 503 Automedics Oil Filter",
    "oil-filters",
    3500,
    "General",
  ),
  p(
    "ATM-OF-504",
    "ATM 504 Automedics Oil Filter",
    "oil-filters",
    3500,
    "General",
  ),
  p(
    "ATM-OF-505",
    "ATM 505 Automedics Oil Filter",
    "oil-filters",
    3500,
    "General",
  ),
  p(
    "ATM-OF-506",
    "ATM 506 Automedics Oil Filter",
    "oil-filters",
    3500,
    "General",
  ),
  p("ATM-OF-PG195", "PG195 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG252", "PG252 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG4651", "PG4651 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG5195", "PG5195 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG5276", "PG5276 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG5280", "PG5280 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG5317", "PG5317 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG5609", "PG5609 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG5646", "PG5646 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG5692", "PG5692 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG5702", "PG5702 Oil Filter", "oil-filters", 5000, "General"),
  p("ATM-OF-PG8113", "PG8113 Oil Filter", "oil-filters", 5000, "General"),
  p(
    "ATM-OF-SH121",
    "SH121 SCT Oil Filter",
    "oil-filters",
    3500,
    "General",
    "SCT",
  ),
  p(
    "ATM-OF-SH4031P",
    "SH4031P SCT Oil Filter",
    "oil-filters",
    3500,
    "General",
    "SCT",
  ),
  p(
    "ATM-OF-SH4051",
    "SH4051 SCT Filter",
    "oil-filters",
    3500,
    "General",
    "SCT",
  ),
  p("ATM-OF-SM106", "SM106 SCT Filter", "oil-filters", 3500, "General", "SCT"),
  p(
    "ATM-OF-R85394",
    "R85394 Oil Filter (Car Quest)",
    "oil-filters",
    3500,
    "General",
    "Car Quest",
  ),

  // 7. Air Filters (duplicate Camry 2.7 / RAV4 2003 alts dropped)
  p(
    "ATM-AF-CAMRY27",
    "Air Filter 2.7 Camry",
    "air-filters",
    15000,
    "Toyota Camry 2.7",
  ),
  p(
    "ATM-AF-COROLLA18",
    "Air Filter Corolla 1.8",
    "air-filters",
    15000,
    "Toyota Corolla 1.8",
  ),
  p(
    "ATM-AF-FRONTIER",
    "Air Filter Frontier",
    "air-filters",
    15000,
    "Nissan Frontier",
  ),
  p(
    "ATM-AF-HIGHLANDER-2011",
    "Air Filter Highlander 2011",
    "air-filters",
    15000,
    "Toyota Highlander 2011",
  ),
  p(
    "ATM-AF-RAV4-2003",
    "Air Filter RAV4 2003",
    "air-filters",
    15000,
    "Toyota RAV4 2003",
  ),
  p("ATM-AF-RX350", "Air Filter RX350", "air-filters", 15000, "Lexus RX350"),
  p(
    "ATM-AF-COROLLA-17801",
    "Air Filter Corolla (17801-22020)",
    "air-filters",
    15000,
    "Toyota Corolla",
  ),
  p(
    "ATM-AF-ELANTRA",
    "Air Filter Elantra",
    "air-filters",
    15000,
    "Hyundai Elantra",
  ),
  p(
    "ATM-AF-260300-0110",
    "Air Filter 260300-0110",
    "air-filters",
    15000,
    "General",
  ),
  p(
    "ATM-AF-26030-0140",
    "26030-0140 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B130150105",
    "B130150105 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B130G0066",
    "B130G0066 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B130G0154",
    "B130G0154 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B130G0155",
    "B130G0155 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B130G0170",
    "B130G0170 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B13170117",
    "B13170117 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B140G0043",
    "B140G0043 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B140G0054",
    "B140G0054 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B140G0056",
    "B140G0056 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),
  p(
    "ATM-AF-B152303200",
    "B152303200 CFAO Air Filter",
    "air-filters",
    15000,
    "General",
    "CFAO",
  ),

  // 8. Cabin Filters
  p(
    "ATM-CF-B140G0060",
    "B140G0060 CFAO Cabin Filter",
    "cabin-filters",
    5000,
    "General",
    "CFAO",
  ),

  // 9. Brake Pads
  p(
    "ATM-BP-A1N008T",
    "A1N008T Aisin Brake Pad",
    "brake-pads",
    15000,
    "General",
    "Aisin",
  ),
  p(
    "ATM-BP-A1N138T",
    "A1N138T Aisin Brake Pad",
    "brake-pads",
    15000,
    "General",
    "Aisin",
  ),
  p(
    "ATM-BP-A1N141T",
    "A1N141T Aisin Brake Pad",
    "brake-pads",
    15000,
    "General",
    "Aisin",
  ),
  p(
    "ATM-BP-A1N225T",
    "A1N225T Aisin Brake Pad",
    "brake-pads",
    15000,
    "General",
    "Aisin",
  ),
  p(
    "ATM-BP-A1N229T",
    "A1N229T Aisin Brake Pad",
    "brake-pads",
    15000,
    "General",
    "Aisin",
  ),
  p(
    "ATM-BP-A1N254T",
    "A1N254T Aisin Brake Pad",
    "brake-pads",
    15000,
    "General",
    "Aisin",
  ),
  p(
    "ATM-BP-A2N007T",
    "A2N007T Aisin Brake Pad",
    "brake-pads",
    15000,
    "General",
    "Aisin",
  ),
  p(
    "ATM-BP-A2N224T",
    "A2N224T Aisin Brake Pad",
    "brake-pads",
    15000,
    "General",
    "Aisin",
  ),
  p(
    "ATM-BP-A2N232T",
    "A2N232T Aisin Brake Pad",
    "brake-pads",
    15000,
    "General",
    "Aisin",
  ),
  p(
    "ATM-BP-D1123",
    "D-1123 Automedics Brake Pad",
    "brake-pads",
    30000,
    "General",
  ),
  p(
    "ATM-BP-D1304",
    "D-1304 Automedics Brake Pad",
    "brake-pads",
    20000,
    "General",
  ),
  p(
    "ATM-BP-D1324",
    "D-1324 Front Automedics Brake Pad",
    "brake-pads",
    20000,
    "General",
  ),
  p(
    "ATM-BP-D1325",
    "D-1325 Rear Automedics Brake Pad",
    "brake-pads",
    15000,
    "General",
  ),
  p(
    "ATM-BP-D1336",
    "D-1336 Front Automedics Brake Pad",
    "brake-pads",
    20000,
    "General",
  ),
  p(
    "ATM-BP-D1391",
    "D-1391 Rear Automedics Brake Pad",
    "brake-pads",
    15000,
    "General",
  ),
  p(
    "ATM-BP-D1401",
    "D-1401 Front Automedics Brake Pad",
    "brake-pads",
    20000,
    "General",
  ),
  p(
    "ATM-BP-D1402",
    "D-1402 Rear Automedics Brake Pad",
    "brake-pads",
    15000,
    "General",
  ),
  p(
    "ATM-BP-D2270",
    "D-2270 Front Automedics Brake Pad",
    "brake-pads",
    20000,
    "General",
  ),
  p(
    "ATM-BP-D2278",
    "D-2278 Automedics Brake Pad",
    "brake-pads",
    20000,
    "General",
  ),
  p(
    "ATM-BP-D787",
    "D-787 Front Automedics Brake Pad",
    "brake-pads",
    20000,
    "General",
  ),
  p(
    "ATM-BP-D906",
    "D-906 Front Automedics Brake Pad",
    "brake-pads",
    20000,
    "General",
  ),
  p("ATM-BP-1011", "Brake Pad 1011", "brake-pads", 25000, "Ford F150"),
  p("ATM-BP-1012", "Brake Pad 1012", "brake-pads", 25000, "Ford F150"),
  p("ATM-BP-2228", "Brake Pad 2228", "brake-pads", 25000, "Toyota Tacoma"),
  p(
    "ATM-BP-2278F",
    "Brake Pad 2278 Front",
    "brake-pads",
    25000,
    "Toyota Tundra",
  ),
  p(
    "ATM-BP-2278B",
    "Brake Pad 2278B Rear",
    "brake-pads",
    25000,
    "Toyota Tundra",
  ),
  p("ATM-BP-5153", "Brake Pad 5153", "brake-pads", 25000, "General"),
  p(
    "ATM-BP-8691F",
    "Brake Pad 8691F",
    "brake-pads",
    25000,
    "Hyundai Elantra 2011",
  ),
  p("ATM-BP-DI011", "Eco Smart Brake Pad DI011", "brake-pads", 25000, "Ford"),
  p(
    "ATM-BP-09W20",
    "F Brake Pad 09W20 Asimco",
    "brake-pads",
    25000,
    "Honda",
    "Asimco",
  ),
  p(
    "ATM-BP-CAMRY-2010-F",
    "Front Brake Pad Camry 2010",
    "brake-pads",
    20000,
    "Toyota Camry 2010",
  ),
  p(
    "ATM-BP-RAV4-F",
    "Front Brake Pad RAV4",
    "brake-pads",
    20000,
    "Toyota RAV4",
  ),
  p(
    "ATM-BP-RX350-F",
    "Front Brake Pad RX350",
    "brake-pads",
    20000,
    "Lexus RX350",
  ),
  p(
    "ATM-BP-HGB-04465YZZEQ",
    "HGB-04465YZZEQ Front Corolla 2014",
    "brake-pads",
    20000,
    "Toyota Corolla 2014",
  ),
  p(
    "ATM-BP-HGB1211-8331",
    "HGB1211-8331 Front RAV4 2008",
    "brake-pads",
    20000,
    "Toyota RAV4 2008",
  ),
  p(
    "ATM-BP-HGB1401-8509",
    "HGB1401-8509 Front Venza 2010-2014",
    "brake-pads",
    20000,
    "Toyota Venza 2010-2014",
  ),
  p(
    "ATM-BP-HGB1402-8510",
    "HGB1402-8510 Rear Venza 2008-2016",
    "brake-pads",
    20000,
    "Toyota Venza 2008-2016",
  ),
  p(
    "ATM-BP-HGB1571-8780",
    "HGB1571-8780 Front Corolla 2008",
    "brake-pads",
    20000,
    "Toyota Corolla 2008",
  ),
  p(
    "ATM-BP-HGB1572-8781",
    "HGB1572-8781 Rear Corolla 2008",
    "brake-pads",
    20000,
    "Toyota Corolla 2008",
  ),
  p(
    "ATM-BP-IKB-AC1175",
    "IKB AC1175 Front Corolla 2014",
    "brake-pads",
    20000,
    "Toyota Corolla 2014",
  ),
  p(
    "ATM-BP-NUELA-Z",
    "Nuela Z Brake Pad",
    "brake-pads",
    25000,
    "Ford Edge 2008",
  ),
  p("ATM-BP-OWL", "OWL Brake Pad", "brake-pads", 20000, "Nissan & Toyota"),
  p(
    "ATM-BP-KD1743",
    "R Brake Pad KD1743 Asimco",
    "brake-pads",
    25000,
    "Honda Accord",
    "Asimco",
  ),
  p(
    "ATM-BP-SCT-SP106-SP659",
    "SCT SP106 to SP659 series (all SP numbers)",
    "brake-pads",
    15000,
    "Various",
    "SCT",
  ),
  p(
    "ATM-BP-YBD-BP3004",
    "YBD BP3004",
    "brake-pads",
    25000,
    "Acura / Honda 2007-2012",
  ),

  // 10. Brake Discs
  p("ATM-BD-BACK", "Back Brake Disc", "brake-discs", 60000, "General"),
  p(
    "ATM-BD-TUNDRA-2008-R",
    "Back Disc Tundra 2008",
    "brake-discs",
    95000,
    "Toyota Tundra 2008",
  ),
  p(
    "ATM-BD-ODYSSEY-2008-F",
    "Front Brake Disc Odyssey 2008",
    "brake-discs",
    75000,
    "Honda Odyssey 2008",
  ),
  p(
    "ATM-BD-TACOMA-2008-F",
    "Front Disc Tacoma 2008",
    "brake-discs",
    95000,
    "Toyota Tacoma 2008",
  ),
  p(
    "ATM-BD-TUNDRA-2008-F",
    "Front Disc Tundra 2008",
    "brake-discs",
    95000,
    "Toyota Tundra 2008",
  ),

  // 11. Brake Linings
  p(
    "ATM-BL-SS904",
    "Auto Brake Lining SS904 L200",
    "brake-linings",
    20000,
    "Mitsubishi L200",
  ),
  p(
    "ATM-BL-SS903",
    "Auto Brake Lining SS903 4Runner",
    "brake-linings",
    20000,
    "Toyota 4Runner",
  ),
  p(
    "ATM-BL-L200",
    "Brake Lining L200",
    "brake-linings",
    25000,
    "Mitsubishi L200",
  ),

  // 12. Shock Absorbers
  p(
    "ATM-SH-1214-0195",
    "1214-0195 Sensen Shock",
    "shock-absorbers",
    95000,
    "General",
    "Sensen",
  ),
  p(
    "ATM-SH-4213-0470",
    "4213-0470 Sensen Shocks",
    "shock-absorbers",
    95000,
    "General",
    "Sensen",
  ),
  p(
    "ATM-SH-SEQUOIA-2008-R",
    "Back Shock Sequoia 2008",
    "shock-absorbers",
    65000,
    "Toyota Sequoia 2008",
  ),
  p(
    "ATM-SH-CRV-2009-R",
    "Back Shock CR-V 2009",
    "shock-absorbers",
    80000,
    "Honda CR-V 2009",
  ),
  p(
    "ATM-SH-HIGHLANDER-2008-R",
    "Back Shock Highlander 2008 4×4",
    "shock-absorbers",
    70000,
    "Toyota Highlander 2008",
  ),
  p(
    "ATM-SH-CAMRY-2012-F-SHORT",
    "Front Shock Camry 2012 Short",
    "shock-absorbers",
    70000,
    "Toyota Camry 2012",
  ),
  p(
    "ATM-SH-CAMRY-2014-F-LONG",
    "Front Shock Camry 2014 Long",
    "shock-absorbers",
    70000,
    "Toyota Camry 2014",
  ),
  p(
    "ATM-SH-COROLLA-2003-F",
    "Front Shock Corolla 2003",
    "shock-absorbers",
    70000,
    "Toyota Corolla 2003",
  ),
  p(
    "ATM-SH-PATHFINDER-2005-F",
    "Front Shock Pathfinder 2005",
    "shock-absorbers",
    70000,
    "Nissan Pathfinder 2005",
  ),
  p(
    "ATM-SH-PILOT-2003-2007-F",
    "Front Shock Pilot 2003-2007",
    "shock-absorbers",
    65000,
    "Honda Pilot 2003-2007",
  ),
  p(
    "ATM-SH-RAV4-2005-F",
    "Front Shock RAV4 2005",
    "shock-absorbers",
    70000,
    "Toyota RAV4 2005",
  ),
  p(
    "ATM-SH-RX350-F",
    "Front Shock RX350",
    "shock-absorbers",
    70000,
    "Lexus RX350",
  ),
  p(
    "ATM-SH-JMB-ACCORD-2008-R",
    "JMB Rear Shock Accord 2008",
    "shock-absorbers",
    65000,
    "Honda Accord 2008",
  ),
  p(
    "ATM-SH-MJL-ACCORD-2008-F",
    "MJL Front Shock Accord 2008",
    "shock-absorbers",
    60000,
    "Honda Accord 2008",
  ),
  p(
    "ATM-SH-XTERRA-R",
    "Rear Shock Xterra",
    "shock-absorbers",
    65000,
    "Nissan Xterra",
  ),

  // 13. Ball Joints (duplicate RAV4 2008 alt dropped)
  p(
    "ATM-BJ-CAMRY27-2008",
    "Ball Joint Camry 2.7 2008",
    "ball-joints",
    20000,
    "Toyota Camry 2.7 2008",
  ),
  p("ATM-BJ-18", "Ball Joint 1.8", "ball-joints", 20000, "Toyota Corolla 1.8"),
  p("ATM-BJ-22", "Ball Joint 2.2", "ball-joints", 20000, "General"),
  p("ATM-BJ-24", "Ball Joint 2.4", "ball-joints", 20000, "General"),
  p("ATM-BJ-27", "Ball Joint 2.7", "ball-joints", 20000, "Toyota Camry 2.7"),
  p(
    "ATM-BJ-ACCORD-2013",
    "Ball Joint Accord 2013",
    "ball-joints",
    20000,
    "Honda Accord 2013",
  ),
  p(
    "ATM-BJ-ACCORD-2008UP",
    "Ball Joint Accord 2008+",
    "ball-joints",
    20000,
    "Honda Accord 2008 upward",
  ),
  p(
    "ATM-BJ-ACCORD-2018",
    "Ball Joint Accord 2018",
    "ball-joints",
    20000,
    "Honda Accord 2018",
  ),
  p(
    "ATM-BJ-CAMRY-24",
    "Ball Joint Camry 2.4",
    "ball-joints",
    20000,
    "Toyota Camry 2.4",
  ),
  p(
    "ATM-BJ-CAMRY-2015",
    "Ball Joint Camry 2015",
    "ball-joints",
    20000,
    "Toyota Camry 2015",
  ),
  p(
    "ATM-BJ-CIVIC-2018",
    "Ball Joint Civic 2018",
    "ball-joints",
    20000,
    "Honda Civic 2018",
  ),
  p(
    "ATM-BJ-CIVIC-2007",
    "Ball Joint Civic 2007",
    "ball-joints",
    20000,
    "Honda Civic 2007",
  ),
  p(
    "ATM-BJ-CRV-2015",
    "Ball Joint CR-V 2015",
    "ball-joints",
    20000,
    "Honda CR-V 2015",
  ),
  p(
    "ATM-BJ-CRV-2018",
    "Ball Joint CR-V 2018",
    "ball-joints",
    20000,
    "Honda CR-V 2018",
  ),
  p(
    "ATM-BJ-CRV-2007",
    "Ball Joint CR-V 2007",
    "ball-joints",
    20000,
    "Honda CR-V 2007",
  ),
  p(
    "ATM-BJ-HIGHLANDER",
    "Ball Joint Highlander",
    "ball-joints",
    20000,
    "Toyota Highlander",
  ),
  p(
    "ATM-BJ-RAV4-2008",
    "Ball Joint RAV4 2008",
    "ball-joints",
    20000,
    "Toyota RAV4 2008",
  ),
  p("ATM-BJ-RX350", "Ball Joint RX350", "ball-joints", 20000, "Lexus RX350"),
  p(
    "ATM-BJ-SEQUOIA",
    "Ball Joint Sequoia",
    "ball-joints",
    25000,
    "Toyota Sequoia",
  ),
  p(
    "ATM-BJ-CAMRY-2012",
    "Ball Joint Camry 2012",
    "ball-joints",
    20000,
    "Toyota Camry 2012",
  ),
  p(
    "ATM-BJ-CRV-2008",
    "Ball Joint CR-V 2008",
    "ball-joints",
    20000,
    "Honda CR-V 2008",
  ),

  // 14. Stabilizer Linkages + one group for remaining models
  p(
    "ATM-SL-LP1972SEN",
    "Speed Plus LP1972SEN",
    "stabilizer-linkages",
    20000,
    "Honda Accord 08/13, CR-V 2012, Odyssey 13",
    "Speed Plus",
  ),
  p(
    "ATM-SL-CAMRY-2007-F",
    "Stab Link Camry 2007 Front",
    "stabilizer-linkages",
    20000,
    "Toyota Camry 2007",
  ),
  p(
    "ATM-SL-18F",
    "Stab Linkage 1.8F",
    "stabilizer-linkages",
    20000,
    "Toyota Corolla 1.8",
  ),
  p("ATM-SL-22F", "Stab Linkage 2.2F", "stabilizer-linkages", 20000, "General"),
  p("ATM-SL-24F", "Stab Linkage 2.4F", "stabilizer-linkages", 20000, "General"),
  p(
    "ATM-SL-27F",
    "Stab Linkage 2.7F",
    "stabilizer-linkages",
    20000,
    "Toyota Camry 2.7",
  ),
  p(
    "ATM-SL-ACCORD-2018-F",
    "Stab Linkage Accord 2018 Front",
    "stabilizer-linkages",
    20000,
    "Honda Accord 2018",
  ),
  p(
    "ATM-SL-ACCORD-2008-R",
    "Stab Linkage Accord 2008 Rear",
    "stabilizer-linkages",
    20000,
    "Honda Accord 2008",
  ),
  p(
    "ATM-SL-ACCORD-2008-F",
    "Stab Linkage Accord 2008 Front",
    "stabilizer-linkages",
    20000,
    "Honda Accord 2008",
  ),
  p(
    "ATM-SL-CRV-2007-R",
    "Stab Linkage CR-V 2007 Rear",
    "stabilizer-linkages",
    20000,
    "Honda CR-V 2007",
  ),
  p(
    "ATM-SL-CRV-2018-F",
    "Stab Linkage CR-V 2018 Front",
    "stabilizer-linkages",
    20000,
    "Honda CR-V 2018",
  ),
  p(
    "ATM-SL-CRV-2007",
    "Stab Linkage CR-V 2007",
    "stabilizer-linkages",
    20000,
    "Honda CR-V 2007",
  ),
  p(
    "ATM-SL-L200-F",
    "Stab Linkage L200 Front",
    "stabilizer-linkages",
    20000,
    "Mitsubishi L200",
  ),
  p(
    "ATM-SL-OTHER-MODELS",
    "Stabilizer linkages for Camry, Corolla, CR-V, RAV4, Highlander, RX350",
    "stabilizer-linkages",
    20000,
    "Toyota Camry, Toyota Corolla, Honda CR-V, Toyota RAV4, Toyota Highlander, Lexus RX350",
  ),

  // 15. Stabilizer Rubbers & Bushings
  p(
    "ATM-RB-STAB-48815",
    "Stabilizer Rubbers (48815, 48818 series and others)",
    "stabilizer-rubbers-bushings",
    6000,
    "Camry, CR-V, RAV4, RX350, Jazz, Highlander, GX",
  ),
  p(
    "ATM-RB-BUSH-A",
    "Lower Arm Bushings A",
    "stabilizer-rubbers-bushings",
    6000,
    "Various Toyota & Honda models",
  ),
  p(
    "ATM-RB-BUSH-B",
    "Lower Arm Bushings B",
    "stabilizer-rubbers-bushings",
    15000,
    "Various Toyota & Honda models",
  ),

  // 16. Tie Rod Ends & Sockets
  p(
    "ATM-TR-18-COROLLA",
    "Tie Rod End 1.8 Corolla",
    "tie-rod-ends-sockets",
    25000,
    "Toyota Corolla 1.8",
  ),
  p("ATM-TR-22", "Tie Rod End 2.2", "tie-rod-ends-sockets", 25000, "General"),
  p("ATM-TR-24", "Tie Rod End 2.4", "tie-rod-ends-sockets", 25000, "General"),
  p(
    "ATM-TR-CAMRY-2015",
    "Tie Rod End Camry 2015",
    "tie-rod-ends-sockets",
    25000,
    "Toyota Camry 2015",
  ),
  p(
    "ATM-TR-CIVIC-2007",
    "Tie Rod End Civic 2007",
    "tie-rod-ends-sockets",
    25000,
    "Honda Civic 2007",
  ),
  p(
    "ATM-TR-CIVIC-2018",
    "Tie Rod End Civic 2018",
    "tie-rod-ends-sockets",
    25000,
    "Honda Civic 2018",
  ),
  p(
    "ATM-TR-CRV-2007-2018",
    "Tie Rod End CR-V 2007/2010/2018",
    "tie-rod-ends-sockets",
    25000,
    "Honda CR-V",
  ),
  p(
    "ATM-TR-RAV4-2008-2015",
    "Tie Rod End RAV4 2008/2015",
    "tie-rod-ends-sockets",
    25000,
    "Toyota RAV4",
  ),
  p(
    "ATM-TR-RX350",
    "Tie Rod End RX350",
    "tie-rod-ends-sockets",
    25000,
    "Lexus RX350",
  ),
  p(
    "ATM-TR-SOCKETS",
    "Tie Rod Sockets for Camry, Corolla, Accord, Civic, CR-V, RAV4, Tacoma",
    "tie-rod-ends-sockets",
    25000,
    "Toyota Camry, Toyota Corolla, Honda Accord, Honda Civic, Honda CR-V, Toyota RAV4, Toyota Tacoma",
  ),

  // 17. Other / Accessories
  p(
    "ATM-ACC-CFAO-RADCAP",
    "CFAO Radiator Caps (all variants)",
    "other-accessories",
    4000,
    "General",
    "CFAO",
    "radiator-cap",
  ),
  p(
    "ATM-ACC-DENZO-SPARK",
    "Denzo Spark Plug",
    "other-accessories",
    3000,
    "General",
    "Denzo",
    "spark-plug",
  ),
  p(
    "ATM-ACC-GREASE-MAGIC",
    "Grease Magic",
    "other-accessories",
    3000,
    "General",
    "Automedics",
    "grease",
  ),
  p(
    "ATM-ACC-INJECTOR-CURE",
    "Injector Cure",
    "other-accessories",
    4000,
    "General",
    "Automedics",
    "injector-cure",
  ),
  p(
    "ATM-ACC-NANO-BLUE",
    "Nano Blue",
    "other-accessories",
    4000,
    "General",
    "Automedics",
    "fuel-additive",
  ),
  p(
    "ATM-ACC-POLYTRON-MTC-473",
    "Polytron MTC 473ml",
    "other-accessories",
    28000,
    "General",
    "Polytron",
    "fuel-additive",
  ),
  p(
    "ATM-ACC-POLYTRON-4L",
    "Polytron 4L",
    "other-accessories",
    235000,
    "General",
    "Polytron",
    "engine-oil-5l",
  ),
  p(
    "ATM-ACC-POLYTRON-FUEL-354",
    "Polytron Fuel Treatment 354ml",
    "other-accessories",
    18000,
    "General",
    "Polytron",
    "fuel-additive",
  ),
  p(
    "ATM-ACC-SEALANT-GUM",
    "Sealant Gum",
    "other-accessories",
    1500,
    "General",
    "Automedics",
    "sealant",
  ),
  p(
    "ATM-ACC-SAFETY-BOOT",
    "Safety Boot",
    "other-accessories",
    16000,
    "General",
    "Automedics",
    "safety-boot",
  ),
  p(
    "ATM-ACC-OVERALL",
    "Overall",
    "other-accessories",
    16000,
    "General",
    "Automedics",
    "overall",
  ),
  p(
    "ATM-ACC-FRONT-HUB",
    "Front Hub",
    "other-accessories",
    110000,
    "General",
    "Automedics",
    "front-hub",
  ),
  p(
    "ATM-ACC-STEERING-RACK",
    "Steering Rack",
    "other-accessories",
    150000,
    "General",
    "Automedics",
    "steering-rack",
  ),
  p(
    "ATM-ACC-O2-SENSOR",
    "Oxygen Sensor",
    "other-accessories",
    20000,
    "General",
    "Automedics",
    "oxygen-sensor",
  ),
  p(
    "ATM-ACC-SOMKOLCH",
    "Somkolch Anti-Rust",
    "other-accessories",
    25000,
    "General",
    "Somkolch",
    "anti-rust",
  ),
];

export function automedicsImageUrl(imageKey: string): string {
  return `/shop/automedics/${imageKey}.jpg`;
}

export function parseVehicleFitment(vehicle: string): {
  vehicleLabel: string;
  vehicleMake: string | null;
  vehicleModel: string | null;
  vehicleYear: number | null;
  vehicleGeneral: boolean;
  vehicleTags: string[];
} {
  const label = vehicle.trim();
  const general = /^general$/i.test(label) || /^various$/i.test(label);
  const tags = label
    .split(/,|&|\//)
    .map((t) => t.trim())
    .filter(Boolean);
  const yearMatch = label.match(/\b(19|20)\d{2}\b/);
  const makes = [
    "Toyota",
    "Honda",
    "Lexus",
    "Nissan",
    "Hyundai",
    "Ford",
    "Mitsubishi",
    "Acura",
  ];
  const make = makes.find((m) => label.toLowerCase().includes(m.toLowerCase()));
  let model: string | null = null;
  if (make) {
    const after = label
      .slice(label.toLowerCase().indexOf(make.toLowerCase()) + make.length)
      .trim();
    const modelTok = after.split(/\s+/)[0];
    if (modelTok && !/^\d/.test(modelTok) && modelTok.toLowerCase() !== "and") {
      model = modelTok.replace(/,$/, "");
    }
  }
  return {
    vehicleLabel: label,
    vehicleMake: make ?? null,
    vehicleModel: model,
    vehicleYear: yearMatch ? Number(yearMatch[0]) : null,
    vehicleGeneral: general,
    vehicleTags: general ? ["General"] : tags,
  };
}
