"use client";

/**
 * ONA Shop demo catalog (Phase 2) — 70+ realistic demo products.
 * 5+ products × 14 trades, all is_demo = true, deterministic ids/slugs/skus
 * so seeding is idempotent. Attributes match each trade's schema exactly.
 */

export type DemoProduct = {
  /** Deterministic id (demo-<trade>-<slug>) — seed key for idempotency. */
  id: string;
  tradeKey: string;
  categorySlug: string;
  subcategorySlug?: string;
  brand: { slug: string; name: string };
  name: string;
  subtitle: string;
  description: string;
  sku: string;
  mpn?: string;
  oemNumber?: string;
  priceMinor: number;
  /** Starting stock; 0 = exists but currently unavailable. */
  qty: number;
  status: "active" | "inactive" | "unavailable" | "discontinued" | "pending_verification" | "source_pending" | "future_product";
  attributes: Record<string, string | number | boolean>;
  keywords: string[];
};

export const DEMO_PRODUCTS: DemoProduct[] = [
  // ------------------------------ MECHANIC ------------------------------
  {
    id: "demo-mechanic-brake-pads-bosch-front",
    tradeKey: "mechanic",
    categorySlug: "brakes",
    brand: { slug: "bosch", name: "Bosch" },
    name: "Bosch Front Brake Pads",
    subtitle: "Ceramic pads · direct fit for Toyota Camry",
    description: "Premium ceramic front brake pads engineered for consistent bite and low dust. Direct-fit replacement for Toyota Camry 2015–2024.",
    sku: "ONA-DEMO-MECH-BP-001",
    mpn: "BOSCH-CER-33470",
    oemNumber: "04465-33470",
    priceMinor: 2850000,
    qty: 40,
    status: "active",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Camry", vehicleYear: 2020, position: "Front", material: "Ceramic" },
    keywords: ["brake pads", "camry", "front brakes", "ceramic", "bosch"],
  },
  {
    id: "demo-mechanic-oil-filter-ngk",
    tradeKey: "mechanic",
    categorySlug: "filters",
    brand: { slug: "ngk", name: "NGK" },
    name: "NGK Engine Oil Filter",
    subtitle: "High-flow spin-on filter · 75mm thread",
    description: "High-flow spin-on engine oil filter with anti-drainback valve. Fits most Japanese and Korean petrol engines.",
    sku: "ONA-DEMO-MECH-OF-001",
    mpn: "NGK-1450",
    oemNumber: "15600-41020",
    priceMinor: 650000,
    qty: 0,
    status: "unavailable",
    attributes: { vehicleMake: "Toyota", thread: "M20x1.5", diameter: 75 },
    keywords: ["oil filter", "engine oil", "ngk", "spin-on"],
  },
  {
    id: "demo-mechanic-spark-plugs-ngk-4",
    tradeKey: "mechanic",
    categorySlug: "engine",
    brand: { slug: "ngk", name: "NGK" },
    name: "NGK Iridium Spark Plug (Set of 4)",
    subtitle: "0.6mm fine-wire iridium · long life",
    description: "Iridium-tipped spark plugs offering sharper spark, faster starts and up to 60,000km service life. Set of four.",
    sku: "ONA-DEMO-MECH-SP-004",
    mpn: "NGK-ILK16",
    oemNumber: "90919-01245",
    priceMinor: 3600000,
    qty: 60,
    status: "active",
    attributes: { vehicleMake: "Toyota", engine: "2.5L I4", material: "Iridium" },
    keywords: ["spark plug", "iridium", "engine", "ignition"],
  },
  {
    id: "demo-mechanic-shock-absorber-monroe-rear",
    tradeKey: "mechanic",
    categorySlug: "suspension",
    brand: { slug: "monroe", name: "Monroe" },
    name: "Monroe Rear Shock Absorber",
    subtitle: "Gas-charged · Toyota Corolla pair",
    description: "Gas-charged rear shock absorbers delivering stable, controlled ride. Supplied as a pair for Toyota Corolla.",
    sku: "ONA-DEMO-MECH-SH-001",
    mpn: "MON-37133",
    oemNumber: "48530-02130",
    priceMinor: 9800000,
    qty: 18,
    status: "active",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Corolla", position: "Rear", material: "Steel" },
    keywords: ["shock absorber", "corolla", "suspension", "rear"],
  },
  {
    id: "demo-mechanic-serpentine-belt-dayco",
    tradeKey: "mechanic",
    categorySlug: "engine",
    brand: { slug: "dayco", name: "Dayco" },
    name: "Dayco Serpentine Belt",
    subtitle: "6PK1680 · multi-rib accessory belt",
    description: "Multi-rib serpentine accessory belt with EPDM construction for long life and quiet operation.",
    sku: "ONA-DEMO-MECH-BELT-001",
    mpn: "DAY-6PK1680",
    oemNumber: "90916-02519",
    priceMinor: 1900000,
    qty: 0,
    status: "source_pending",
    attributes: { vehicleMake: "Toyota", engine: "1.8L I4" },
    keywords: ["serpentine belt", "accessory belt", "dayco", "engine"],
  },
  {
    id: "demo-mechanic-coolant-50-50-5l",
    tradeKey: "mechanic",
    categorySlug: "cooling",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Antifreeze Coolant 50/50 5L",
    subtitle: "Long-life organic coolant · -35°C",
    description: "Pre-mixed 50/50 ethylene-glycol coolant suitable for most petrol and diesel engines. Prevents corrosion and overheating.",
    sku: "ONA-DEMO-MECH-CL-5L",
    mpn: "ONA-50-50-5L",
    priceMinor: 1750000,
    qty: 120,
    status: "active",
    attributes: { capacity: 5, material: "Ethylene glycol" },
    keywords: ["coolant", "antifreeze", "radiator", "5L"],
  },

  // ------------------------------ VULCANIZER ------------------------------
  {
    id: "demo-vulcanizer-tire-195-65r15",
    tradeKey: "vulcanizer",
    categorySlug: "tires",
    brand: { slug: "continental", name: "Continental" },
    name: "Continental 195/65 R15 Tire",
    subtitle: "All-season touring · 88H",
    description: "All-season touring tire with low rolling resistance and balanced wet grip. Size 195/65 R15, load index 88, speed rating H.",
    sku: "ONA-DEMO-VUL-TR-001",
    mpn: "CONT-19565R15",
    priceMinor: 2450000,
    qty: 32,
    status: "active",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Corolla", tireWidth: 195, aspectRatio: 65, rimSize: 15, speedRating: "H", loadIndex: 88 },
    keywords: ["tire", "195/65 r15", "continental", "touring"],
  },
  {
    id: "demo-vulcanizer-tube-165r13",
    tradeKey: "vulcanizer",
    categorySlug: "tubes",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Inner Tube 165 R13",
    subtitle: "Butyl rubber · TR412 valve",
    description: "High-grade butyl rubber inner tube with TR412 rubber valve. Fits 13-inch wheels.",
    sku: "ONA-DEMO-VUL-TB-013",
    mpn: "ONA-165R13",
    priceMinor: 850000,
    qty: 90,
    status: "active",
    attributes: { rimSize: 13, tubeType: "Tube", material: "Butyl rubber" },
    keywords: ["inner tube", "165r13", "butyl", "valve"],
  },
  {
    id: "demo-vulcanizer-rim-15-5-100",
    tradeKey: "vulcanizer",
    categorySlug: "rims",
    brand: { slug: "enkei", name: "Enkei" },
    name: "Enkei Alloy Rim 15\" 5x100",
    subtitle: "Silver alloy · Toyota fitment",
    description: "Lightweight alloy rim, 15-inch diameter with 5x100 bolt pattern and offset 45. Fits Toyota Corolla, Camry.",
    sku: "ONA-DEMO-VUL-RIM-001",
    mpn: "ENK-15-5X100",
    priceMinor: 2150000,
    qty: 22,
    status: "pending_verification",
    attributes: { vehicleMake: "Toyota", rimSize: 15, material: "Aluminium" },
    keywords: ["rim", "alloy wheel", "15 inch", "enkei"],
  },
  {
    id: "demo-vulcanizer-tpms-sensor",
    tradeKey: "vulcanizer",
    categorySlug: "tpms",
    brand: { slug: "schrader", name: "Schrader" },
    name: "Schrader TPMS Sensor",
    subtitle: "433MHz programmable · OEM-grade",
    description: "Programmable 433MHz TPMS sensor compatible with most vehicles that use snap-in sensors.",
    sku: "ONA-DEMO-VUL-TPMS-001",
    mpn: "SCH-20051",
    priceMinor: 4200000,
    qty: 15,
    status: "active",
    attributes: { vehicleMake: "Toyota", material: "Plastic" },
    keywords: ["tpms", "sensor", "tire pressure", "schrader"],
  },
  {
    id: "demo-vulcanizer-tire-patch-kit",
    tradeKey: "vulcanizer",
    categorySlug: "tire-repair",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Tire Repair Patch Kit",
    subtitle: "Vulcanizing patches · 25 pieces",
    description: "Vulcanizing repair patches with cement for tubeless tire puncture repair. 25 mixed-size patches per box.",
    sku: "ONA-DEMO-VUL-PATCH-001",
    mpn: "ONA-VPK-25",
    priceMinor: 320000,
    qty: 0,
    status: "inactive",
    attributes: { tubeType: "Tubeless", material: "Rubber" },
    keywords: ["patch", "repair kit", "puncture", "vulcanizing"],
  },

  // ------------------------------ TOWING ------------------------------
  {
    id: "demo-towing-strap-10m-4t",
    tradeKey: "towing",
    categorySlug: "tow-straps",
    brand: { slug: "rhino", name: "Rhino" },
    name: "Rhino Recovery Tow Strap 10m",
    subtitle: "10m × 75mm · 4-ton breaking strength",
    description: "Heavy-duty recovery tow strap with reinforced loops and 4-ton breaking strength. Folds flat for storage.",
    sku: "ONA-DEMO-TOW-STRAP-001",
    mpn: "RHN-TS-10M",
    priceMinor: 1250000,
    qty: 45,
    status: "active",
    attributes: { capacity: 4000, length: 10, material: "Nylon" },
    keywords: ["tow strap", "recovery", "4 ton", "10m"],
  },
  {
    id: "demo-towing-winch-electric-12v",
    tradeKey: "towing",
    categorySlug: "winches",
    brand: { slug: "warn", name: "Warn" },
    name: "Warn 12V Electric Winch 4.5t",
    subtitle: "Steel cable · remote control",
    description: "Electric recovery winch with 4.5-ton pulling capacity, 12V DC motor, steel cable and wired remote.",
    sku: "ONA-DEMO-TOW-WINCH-001",
    mpn: "WARN-8274",
    priceMinor: 4850000,
    qty: 8,
    status: "active",
    attributes: { capacity: 4500, winchType: "Electric", material: "Steel" },
    keywords: ["winch", "12v", "recovery", "warn"],
  },
  {
    id: "demo-towing-shackle-3-25t",
    tradeKey: "towing",
    categorySlug: "recovery-equipment",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Recovery Shackle 3.25t",
    subtitle: "Forged steel D-shackle",
    description: "Forged steel D-shackle with screw pin, rated to 3.25 tons for recovery work.",
    sku: "ONA-DEMO-TOW-SHACKLE-001",
    mpn: "ONA-DSH-3.25",
    priceMinor: 480000,
    qty: 75,
    status: "active",
    attributes: { capacity: 3250, hookType: "D-shackle", material: "Steel" },
    keywords: ["shackle", "recovery", "d-shackle", "forged"],
  },
  {
    id: "demo-towing-tow-bar-adjustable",
    tradeKey: "towing",
    categorySlug: "tow-bars",
    brand: { slug: "rhino", name: "Rhino" },
    name: "Rhino Adjustable Tow Bar",
    subtitle: "Extends 1.2–1.8m · 3.5t rated",
    description: "Fully adjustable tow bar for light recovery and flat towing. Rated to 3.5 tons.",
    sku: "ONA-DEMO-TOW-BAR-001",
    mpn: "RHN-TB-3.5",
    priceMinor: 2350000,
    qty: 12,
    status: "active",
    attributes: { capacity: 3500, length: 1.5, material: "Steel" },
    keywords: ["tow bar", "flat towing", "adjustable", "rhino"],
  },
  {
    id: "demo-towing-warning-arrow-board",
    tradeKey: "towing",
    categorySlug: "warning-equipment",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro LED Warning Arrow Board",
    subtitle: "Solar-rechargeable · magnetic mount",
    description: "Portable LED arrow board with solar recharge and magnetic mount for roadside warning duty.",
    sku: "ONA-DEMO-TOW-ARROW-001",
    mpn: "ONA-AB-24",
    priceMinor: 980000,
    qty: 0,
    status: "future_product",
    attributes: { capacity: 0, material: "Composite" },
    keywords: ["arrow board", "warning", "led", "roadside"],
  },

  // ------------------------------ A/C ------------------------------
  {
    id: "demo-ac-refrigerant-r134a-13kg",
    tradeKey: "ac",
    categorySlug: "vehicle-ac",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro R-134a Refrigerant 13.6kg",
    subtitle: "Automotive refrigerant cylinder",
    description: "Virgin-grade R-134a automotive refrigerant in a 13.6kg refillable cylinder.",
    sku: "ONA-DEMO-AC-R134A-136",
    mpn: "ONA-R134A-136",
    priceMinor: 4800000,
    qty: 30,
    status: "active",
    attributes: { vehicleMake: "Toyota", refrigerant: "R-134a", btuCapacity: 12000, application: "Vehicle A/C" },
    keywords: ["refrigerant", "r-134a", "ac gas", "vehicle ac"],
  },
  {
    id: "demo-ac-compressor-toyota-camry",
    tradeKey: "ac",
    categorySlug: "compressors",
    brand: { slug: "denso", name: "Denso" },
    name: "Denso A/C Compressor",
    subtitle: "Toyota Camry 2015–2024 · new",
    description: "Brand-new A/C compressor with clutch for Toyota Camry 2015–2024. Direct OEM-style fitment.",
    sku: "ONA-DEMO-AC-COMP-001",
    mpn: "DEN-471-1244",
    oemNumber: "447260-3400",
    priceMinor: 7850000,
    qty: 10,
    status: "active",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Camry", compressorType: "Rotary", refrigerant: "R-134a", btuCapacity: 14000, application: "Vehicle A/C" },
    keywords: ["ac compressor", "camry", "denso", "air conditioning"],
  },
  {
    id: "demo-ac-split-1-5hp-12000btu",
    tradeKey: "ac",
    categorySlug: "commercial-ac",
    brand: { slug: "lg", name: "LG" },
    name: "LG Split A/C 1.5HP 12,000 BTU",
    subtitle: "Inverter · R-32 · cooling + heating",
    description: "1.5HP inverter split air conditioner, 12,000 BTU cooling capacity with R-32 refrigerant.",
    sku: "ONA-DEMO-AC-SPLIT-001",
    mpn: "LG-12K-182",
    priceMinor: 2850000,
    qty: 25,
    status: "active",
    attributes: { refrigerant: "R-32", btuCapacity: 12000, voltage: 230, compressorType: "Rotary", application: "Commercial A/C" },
    keywords: ["split ac", "12000 btu", "lg", "inverter", "1.5hp"],
  },
  {
    id: "demo-ac-condenser-corolla",
    tradeKey: "ac",
    categorySlug: "condensers",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro A/C Condenser",
    subtitle: "Toyota Corolla 2014–2019",
    description: "Aftermarket A/C condenser radiator for Toyota Corolla 2014–2019 with receiver-drier included.",
    sku: "ONA-DEMO-AC-COND-001",
    mpn: "ONA-COND-COR",
    priceMinor: 3850000,
    qty: 14,
    status: "pending_verification",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Corolla", btuCapacity: 9000, application: "Vehicle A/C" },
    keywords: ["condenser", "corolla", "ac", "cooling coil"],
  },
  {
    id: "demo-ac-manifold-gauge-set",
    tradeKey: "ac",
    categorySlug: "ac-tools",
    brand: { slug: "mastercool", name: "Mastercool" },
    name: "Mastercool A/C Manifold Gauge Set",
    subtitle: "3-way · R-134a hoses",
    description: "3-way manifold gauge set with 60-inch R-134a hoses and color-coded gauges for servicing.",
    sku: "ONA-DEMO-AC-GAUGE-001",
    mpn: "MSC-1772",
    priceMinor: 2550000,
    qty: 0,
    status: "unavailable",
    attributes: { refrigerant: "R-134a", btuCapacity: 12000, application: "Vehicle A/C" },
    keywords: ["manifold gauge", "ac tools", "r-134a", "service"],
  },

  // ------------------------------ BATTERY ------------------------------
  {
    id: "demo-battery-car-12v-60ah",
    tradeKey: "battery",
    categorySlug: "vehicle-batteries",
    brand: { slug: "exide", name: "Exide" },
    name: "Exide 12V 60Ah Car Battery",
    subtitle: "Maintenance-free · top post",
    description: "Maintenance-free 12V 60Ah car battery with 480 CCA. Fits most 1.3–1.8L Japanese and Korean cars.",
    sku: "ONA-DEMO-BAT-60-001",
    mpn: "EXIDE-60MF",
    priceMinor: 1385000,
    qty: 55,
    status: "active",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Corolla", voltage: 12, capacityAh: 60, batteryType: "Lead-acid", crankingAmps: 480, terminalType: "Top post" },
    keywords: ["car battery", "12v", "60ah", "exide"],
  },
  {
    id: "demo-battery-charger-smart-12v",
    tradeKey: "battery",
    categorySlug: "battery-chargers",
    brand: { slug: "ctek", name: "CTEK" },
    name: "CTEK Smart Battery Charger 12V",
    subtitle: "8-step charging · 5A",
    description: "Fully automatic 8-step smart charger for 12V batteries, 5A output with desulfation mode.",
    sku: "ONA-DEMO-BAT-CHG-001",
    mpn: "CTEK-CS5",
    priceMinor: 2850000,
    qty: 20,
    status: "active",
    attributes: { voltage: 12, capacityAh: 5 },
    keywords: ["battery charger", "smart", "12v", "ctek"],
  },
  {
    id: "demo-battery-tester-digital",
    tradeKey: "battery",
    categorySlug: "battery-testers",
    brand: { slug: "ancel", name: "Ancel" },
    name: "Ancel Digital Battery Tester",
    subtitle: "12V/24V · CCA + health",
    description: "Digital battery tester for 12V/24V batteries measuring CCA, voltage, health and charge state.",
    sku: "ONA-DEMO-BAT-TST-001",
    mpn: "ANCEL-BA101",
    priceMinor: 950000,
    qty: 0,
    status: "unavailable",
    attributes: { voltage: 12, capacityAh: 60, batteryType: "Lead-acid" },
    keywords: ["battery tester", "digital", "cca", "ancel"],
  },
  {
    id: "demo-battery-jump-starter-3000a",
    tradeKey: "battery",
    categorySlug: "jump-starters",
    brand: { slug: "duralast", name: "Duralast" },
    name: "Duralast Jump Starter 3000A",
    subtitle: "12V boost · USB power bank",
    description: "3000A peak jump starter for 12V petrol and diesel vehicles, with USB ports and LED work light.",
    sku: "ONA-DEMO-BAT-JS-001",
    mpn: "DUR-3000",
    priceMinor: 4750000,
    qty: 16,
    status: "active",
    attributes: { voltage: 12, capacityAh: 24, crankingAmps: 3000, batteryType: "Lithium-ion" },
    keywords: ["jump starter", "3000a", "boost", "power bank"],
  },
  {
    id: "demo-battery-terminal-corrosion-guard",
    tradeKey: "battery",
    categorySlug: "terminals",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Battery Terminal Corrosion Guard",
    subtitle: "120ml spray",
    description: "Anti-corrosion protective spray for battery terminals to prevent sulfation build-up.",
    sku: "ONA-DEMO-BAT-GUARD-001",
    mpn: "ONA-BTG-120",
    priceMinor: 280000,
    qty: 0,
    status: "source_pending",
    attributes: { voltage: 12, capacityAh: 5, batteryType: "Lead-acid" },
    keywords: ["terminal guard", "corrosion", "spray", "battery"],
  },

  // ------------------------------ BODY ------------------------------
  {
    id: "demo-body-door-toyota-camry-front",
    tradeKey: "body",
    categorySlug: "doors",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Front Door Shell",
    subtitle: "Toyota Camry 2018–2024 · driver side",
    description: "OEM-style front driver door shell for Toyota Camry 2018–2024. Primed, ready for paint.",
    sku: "ONA-DEMO-BODY-DOOR-001",
    mpn: "ONA-DR-CAM-FL",
    priceMinor: 7850000,
    qty: 6,
    status: "active",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Camry", position: "Driver", panelType: "Door", material: "Steel" },
    keywords: ["door", "camry", "body shell", "front door"],
  },
  {
    id: "demo-body-bonnet-corolla",
    tradeKey: "body",
    categorySlug: "bonnets",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Bonnet (Hood)",
    subtitle: "Toyota Corolla 2014–2019",
    description: "Replacement bonnet for Toyota Corolla 2014–2019 in primer finish.",
    sku: "ONA-DEMO-BODY-BONNET-001",
    mpn: "ONA-BN-COR",
    priceMinor: 4550000,
    qty: 9,
    status: "active",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Corolla", panelType: "Bonnet", material: "Steel" },
    keywords: ["bonnet", "hood", "corolla", "body"],
  },
  {
    id: "demo-body-bumper-front-camry",
    tradeKey: "body",
    categorySlug: "bumpers",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Front Bumper",
    subtitle: "Toyota Camry 2018–2024 · primed",
    description: "Front bumper cover for Toyota Camry 2018–2024, primed and ready for final paint.",
    sku: "ONA-DEMO-BODY-BUMPER-001",
    mpn: "ONA-BMP-CAM-F",
    priceMinor: 6250000,
    qty: 4,
    status: "active",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Camry", position: "Front", panelType: "Bumper", material: "Composite" },
    keywords: ["bumper", "camry", "front", "body"],
  },
  {
    id: "demo-body-headlight-led-camry",
    tradeKey: "body",
    categorySlug: "headlights",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro LED Headlight Assembly",
    subtitle: "Toyota Camry 2018–2024 · pair",
    description: "Pair of LED headlight assemblies for Toyota Camry 2018–2024 with projector lens and DRL.",
    sku: "ONA-DEMO-BODY-HL-001",
    mpn: "ONA-HL-CAM-LED",
    priceMinor: 6850000,
    qty: 11,
    status: "pending_verification",
    attributes: { vehicleMake: "Toyota", vehicleModel: "Camry", position: "Front", panelType: "Headlight", material: "Glass" },
    keywords: ["headlight", "led", "camry", "drl"],
  },
  {
    id: "demo-body-paint-blue-metallic-1l",
    tradeKey: "body",
    categorySlug: "paint",
    brand: { slug: "dupont", name: "DuPont" },
    name: "DuPont Metallic Blue Basecoat 1L",
    subtitle: "2K ready · deep blue",
    description: "Metallic blue basecoat for automotive refinish. Mixes with 2K clear coat system.",
    sku: "ONA-DEMO-BODY-PNT-001",
    mpn: "DUP-BLUE-1L",
    priceMinor: 1950000,
    qty: 40,
    status: "active",
    attributes: { panelType: "Paint", paintCode: "BLUE-MET", finish: "Metallic" },
    keywords: ["paint", "basecoat", "metallic blue", "2k", "refinish"],
  },

  // ------------------------------ ELECTRICAL ------------------------------
  {
    id: "demo-elec-battery-cable-jumper",
    tradeKey: "electrical",
    categorySlug: "cables",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Jumper Cable 4m 300A",
    subtitle: "Copper-clad · insulated clamps",
    description: "4-metre heavy-duty jumper cables rated to 300A with fully insulated clamps.",
    sku: "ONA-DEMO-ELEC-JC-001",
    mpn: "ONA-JC-300",
    priceMinor: 550000,
    qty: 100,
    status: "active",
    attributes: { amperage: 300 },
    keywords: ["jumper cable", "booster", "4m", "300a"],
  },
  {
    id: "demo-elec-breaker-63a-2p",
    tradeKey: "electrical",
    categorySlug: "breakers",
    brand: { slug: "schneider", name: "Schneider" },
    name: "Schneider MCB 63A 2-Pole",
    subtitle: "C-curve · 6kA breaking capacity",
    description: "Type C miniature circuit breaker, 63A, 2-pole, 6kA breaking capacity for distribution boards.",
    sku: "ONA-DEMO-ELEC-MCB-001",
    mpn: "SCH-18362",
    priceMinor: 720000,
    qty: 0,
    status: "unavailable",
    attributes: { amperage: 63, poleCount: 2 },
    keywords: ["mcb", "circuit breaker", "63a", "schneider"],
  },
  {
    id: "demo-elec-relay-12v-40a",
    tradeKey: "electrical",
    categorySlug: "relays",
    brand: { slug: "omron", name: "Omron" },
    name: "Omron Automotive Relay 12V 40A",
    subtitle: "SPST · plug-in (set of 5)",
    description: "Plug-in SPST automotive relays, 12V coil, 40A contact rating. Pack of five with harness.",
    sku: "ONA-DEMO-ELEC-RELAY-001",
    mpn: "OMRON-G8HL",
    priceMinor: 420000,
    qty: 130,
    status: "active",
    attributes: { voltage: 12, amperage: 40 },
    keywords: ["relay", "12v", "40a", "automotive", "omron"],
  },
  {
    id: "demo-elec-transformer-500va",
    tradeKey: "electrical",
    categorySlug: "transformers",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Step-Down Transformer 500VA",
    subtitle: "220V → 110V · toroidal",
    description: "500VA toroidal step-down transformer converting 220V input to 110V output for imported appliances.",
    sku: "ONA-DEMO-ELEC-TR-500",
    mpn: "ONA-TR-500",
    priceMinor: 3250000,
    qty: 18,
    status: "active",
    attributes: { voltage: 220, wireGauge: "18 AWG" },
    keywords: ["transformer", "step down", "500va", "110v"],
  },
  {
    id: "demo-elec-test-multimeter-digital",
    tradeKey: "electrical",
    categorySlug: "testing-equipment",
    brand: { slug: "fluke", name: "Fluke" },
    name: "Fluke Digital Multimeter 17B+",
    subtitle: "CAT III 600V · AC/DC",
    description: "True-RMS digital multimeter with 600V CAT III rating, AC/DC voltage, current, resistance and continuity.",
    sku: "ONA-DEMO-ELEC-MM-001",
    mpn: "FLUKE-17B",
    priceMinor: 4350000,
    qty: 12,
    status: "active",
    attributes: { voltage: 600, ipRating: "CAT III" },
    keywords: ["multimeter", "digital", "fluke", "test"],
  },

  // ------------------------------ DIAGNOSTICS ------------------------------
  {
    id: "demo-diag-obd2-scanner-autel",
    tradeKey: "diagnostics",
    categorySlug: "obd-scanners",
    brand: { slug: "autel", name: "Autel" },
    name: "Autel OBD2 Scanner AL519",
    subtitle: "Read + clear codes · live data",
    description: "Entry OBD2 scanner reading and clearing engine fault codes with live data and I/M readiness.",
    sku: "ONA-DEMO-DIAG-OBD-001",
    mpn: "AUTEL-AL519",
    priceMinor: 2850000,
    qty: 26,
    status: "active",
    attributes: { protocol: "OBD-II", connectivity: "USB", displayType: "Monochrome", updateable: false },
    keywords: ["obd2", "scanner", "autel", "diagnostic"],
  },
  {
    id: "demo-diag-scanner-launch-x431",
    tradeKey: "diagnostics",
    categorySlug: "diagnostic-scanners",
    brand: { slug: "launch", name: "Launch" },
    name: "Launch X431 PRO Elite Scanner",
    subtitle: "All-systems · WiFi · updates",
    description: "Professional all-systems diagnostic scanner with wireless VCI, online updates and 25+ service functions.",
    sku: "ONA-DEMO-DIAG-X431-001",
    mpn: "LAUNCH-X431P",
    priceMinor: 1850000,
    qty: 7,
    status: "active",
    attributes: { protocol: "OBD-II", connectivity: "Wi-Fi", displayType: "Color", updateable: true },
    keywords: ["scanner", "x431", "launch", "all systems", "diagnostic"],
  },
  {
    id: "demo-diag-code-reader-innova",
    tradeKey: "diagnostics",
    categorySlug: "code-readers",
    brand: { slug: "innova", name: "Innova" },
    name: "Innova Code Reader 3040",
    subtitle: "Pocket-size · freeze frame",
    description: "Pocket code reader displaying pending and stored codes with freeze-frame data.",
    sku: "ONA-DEMO-DIAG-CR-001",
    mpn: "INNOVA-3040",
    priceMinor: 1950000,
    qty: 0,
    status: "inactive",
    attributes: { protocol: "OBD-II", connectivity: "USB", displayType: "Monochrome", updateable: false },
    keywords: ["code reader", "innova", "freeze frame", "obd2"],
  },
  {
    id: "demo-diag-obd2-cable-extension",
    tradeKey: "diagnostics",
    categorySlug: "diagnostic-cables",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro OBD2 Extension Cable 1.5m",
    subtitle: "16-pin male–female",
    description: "1.5-metre OBD2 16-pin male-to-female extension cable for accessing the port in tight spaces.",
    sku: "ONA-DEMO-DIAG-CBL-001",
    mpn: "ONA-OBD-EXT",
    priceMinor: 250000,
    qty: 85,
    status: "active",
    attributes: { protocol: "OBD-II" },
    keywords: ["obd2 cable", "extension", "16 pin", "diagnostic"],
  },
  {
    id: "demo-diag-oscilloscope-hantek",
    tradeKey: "diagnostics",
    categorySlug: "oscilloscopes",
    brand: { slug: "hantek", name: "Hantek" },
    name: "Hantek Automotive Oscilloscope 2D72",
    subtitle: "2-channel · 250MS/s",
    description: "Handheld 2-channel automotive oscilloscope with 250MS/s sampling for sensor and waveform diagnosis.",
    sku: "ONA-DEMO-DIAG-SCOPE-001",
    mpn: "HANTEK-2D72",
    priceMinor: 2350000,
    qty: 5,
    status: "pending_verification",
    attributes: { connectivity: "USB", displayType: "Color", updateable: true },
    keywords: ["oscilloscope", "hantek", "waveform", "automotive"],
  },

  // ------------------------------ WASH ------------------------------
  {
    id: "demo-wash-pressure-washer-karcher",
    tradeKey: "wash",
    categorySlug: "pressure-washers",
    brand: { slug: "karcher", name: "Kärcher" },
    name: "Kärcher K4 Pressure Washer",
    subtitle: "150 bar · electric · 2.1kW",
    description: "Compact electric pressure washer with 150 bar working pressure and 2.1kW motor.",
    sku: "ONA-DEMO-WASH-PW-001",
    mpn: "KARCHER-K4",
    priceMinor: 4850000,
    qty: 14,
    status: "active",
    attributes: { pressure: 150, flowRate: 7, powerSource: "Electric" },
    keywords: ["pressure washer", "karcher", "150 bar", "k4"],
  },
  {
    id: "demo-wash-foam-cannon-1l",
    tradeKey: "wash",
    categorySlug: "foam-cannons",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Foam Cannon 1L",
    subtitle: "Adjustable · 1/4\" quick connect",
    description: "Snow-foam cannon with adjustable dilution for pressure washers using a 1/4-inch quick connect.",
    sku: "ONA-DEMO-WASH-FC-001",
    mpn: "ONA-FC-1L",
    priceMinor: 850000,
    qty: 60,
    status: "active",
    attributes: { pressure: 100, capacity: 1 },
    keywords: ["foam cannon", "snow foam", "pressure washer", "detailing"],
  },
  {
    id: "demo-wash-vacuum-wet-dry",
    tradeKey: "wash",
    categorySlug: "vacuum",
    brand: { slug: "deer", name: "Deer" },
    name: "Deer Wet/Dry Vacuum 20L",
    subtitle: "1600W · blower mode",
    description: "20-litre wet/dry vacuum cleaner with 1600W motor and reverse blower function.",
    sku: "ONA-DEMO-WASH-VAC-001",
    mpn: "DEER-20L",
    priceMinor: 2850000,
    qty: 22,
    status: "active",
    attributes: { powerSource: "Electric", capacity: 20 },
    keywords: ["vacuum", "wet dry", "20l", "deer", "interior cleaning"],
  },
  {
    id: "demo-wash-nozzle-set-5pcs",
    tradeKey: "wash",
    categorySlug: "nozzles",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Pressure Washer Nozzle Set",
    subtitle: "0°, 15°, 25°, 40°, 65° + foam tip",
    description: "Five quick-connect spray nozzles plus foam tip for most pressure washers.",
    sku: "ONA-DEMO-WASH-NZ-001",
    mpn: "ONA-NZ-5PC",
    priceMinor: 320000,
    qty: 0,
    status: "unavailable",
    attributes: { pressure: 150 },
    keywords: ["nozzle", "pressure washer", "spray tip", "set"],
  },
  {
    id: "demo-wash-microfiber-detail-kit",
    tradeKey: "wash",
    categorySlug: "detailing",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Microfiber Detailing Kit",
    subtitle: "12 cloths · 2 mitts · 3 brushes",
    description: "Complete microfiber detailing kit with 12 cloths, 2 wash mitts and 3 detail brushes.",
    sku: "ONA-DEMO-WASH-DET-001",
    mpn: "ONA-DK-12",
    priceMinor: 1450000,
    qty: 70,
    status: "active",
    attributes: { application: "Detailing" },
    keywords: ["microfiber", "detailing kit", "wash mitt", "cloths"],
  },

  // ------------------------------ PLUMBER ------------------------------
  {
    id: "demo-plumber-pvc-pipe-20mm",
    tradeKey: "plumber",
    categorySlug: "pipes",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro PVC Pipe 20mm × 3m",
    subtitle: "Pressure-rated · solvent weld",
    description: "20mm pressure-rated PVC pipe, 3 metres, for potable water and drainage systems.",
    sku: "ONA-DEMO-PLB-PVC-20",
    mpn: "ONA-PVC-20-3M",
    priceMinor: 220000,
    qty: 200,
    status: "active",
    attributes: { diameter: 20, material: "PVC", connection: "Solvent weld", application: "Potable water", pressureRating: 10 },
    keywords: ["pvc pipe", "20mm", "plumbing", "water pipe"],
  },
  {
    id: "demo-plumber-ball-valve-1-2",
    tradeKey: "plumber",
    categorySlug: "valves",
    brand: { slug: "kohler", name: "Kohler" },
    name: "Kohler Brass Ball Valve 1/2\"",
    subtitle: "Full bore · threaded ends",
    description: "Full-bore brass ball valve with threaded 1/2-inch ends for water isolation.",
    sku: "ONA-DEMO-PLB-BV-001",
    mpn: "KOH-1245",
    priceMinor: 1850000,
    qty: 0,
    status: "source_pending",
    attributes: { diameter: 15, connection: "Threaded", material: "Brass", pressureRating: 16, application: "Potable water" },
    keywords: ["ball valve", "brass", "1/2 inch", "kohler"],
  },
  {
    id: "demo-plumber-water-pump-1hp",
    tradeKey: "plumber",
    categorySlug: "pumps",
    brand: { slug: "pedrollo", name: "Pedrollo" },
    name: "Pedrollo Booster Pump 1HP",
    subtitle: "Self-priming · 45L/min",
    description: "Self-priming booster pump with 1HP motor delivering up to 45 L/min for home water pressure.",
    sku: "ONA-DEMO-PLB-PMP-001",
    mpn: "PED-1HP",
    priceMinor: 6850000,
    qty: 17,
    status: "active",
    attributes: { application: "Potable water", material: "Cast iron", pressureRating: 6 },
    keywords: ["booster pump", "water pump", "1hp", "pedrollo"],
  },
  {
    id: "demo-plumber-toilet-ceramic",
    tradeKey: "plumber",
    categorySlug: "toilets",
    brand: { slug: "royal", name: "Royal" },
    name: "Royal Ceramic Toilet Suite",
    subtitle: "White · dual-flush 3/6L",
    description: "Complete ceramic toilet suite with dual-flush cistern (3/6L) and soft-close seat.",
    sku: "ONA-DEMO-PLB-TT-001",
    mpn: "ROYAL-CT-01",
    priceMinor: 5850000,
    qty: 24,
    status: "active",
    attributes: { material: "Ceramic", application: "Potable water" },
    keywords: ["toilet", "ceramic", "dual flush", "royal", "sanitary"],
  },
  {
    id: "demo-plumber-water-heater-25l",
    tradeKey: "plumber",
    categorySlug: "water-heaters",
    brand: { slug: "ariston", name: "Ariston" },
    name: "Ariston 25L Water Heater",
    subtitle: "Electric · wall mount",
    description: "25-litre electric storage water heater with thermostat control and safety valve.",
    sku: "ONA-DEMO-PLB-WH-001",
    mpn: "ARIS-25L",
    priceMinor: 7850000,
    qty: 9,
    status: "pending_verification",
    attributes: { material: "Steel", connection: "Flanged", application: "Heating" },
    keywords: ["water heater", "25l", "electric", "ariston"],
  },

  // ------------------------------ CARPENTER ------------------------------
  {
    id: "demo-carpenter-plywood-18mm",
    tradeKey: "carpenter",
    categorySlug: "plywood",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Plywood 18mm × 2440×1220",
    subtitle: "Birch-faced · marine grade",
    description: "Marine-grade birch-faced plywood sheet, 18mm thick, full 2440×1220 panel.",
    sku: "ONA-DEMO-CAR-PLY-001",
    mpn: "ONA-PLY-18",
    priceMinor: 3850000,
    qty: 45,
    status: "active",
    attributes: { dimensions: "2440x1220x18", thickness: 18, material: "Wood", application: "Furniture" },
    keywords: ["plywood", "18mm", "marine", "board", "carpentry"],
  },
  {
    id: "demo-carpenter-timber-2x4",
    tradeKey: "carpenter",
    categorySlug: "timber",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Timber Stud 2×4 × 3.6m",
    subtitle: "Kiln-dried · structural grade",
    description: "Kiln-dried structural timber stud, 2×4 inches, 3.6 metres long.",
    sku: "ONA-DEMO-CAR-TMB-001",
    mpn: "ONA-TMB-24",
    priceMinor: 480000,
    qty: 150,
    status: "active",
    attributes: { dimensions: "50x100x3600", thickness: 50, material: "Wood", application: "Structural" },
    keywords: ["timber", "2x4", "stud", "structural", "wood"],
  },
  {
    id: "demo-carpenter-circular-saw-bosch",
    tradeKey: "carpenter",
    categorySlug: "saws",
    brand: { slug: "bosch", name: "Bosch" },
    name: "Bosch Circular Saw GKS 190",
    subtitle: "190mm blade · 1400W",
    description: "1400W circular saw with 190mm blade and 66mm cutting depth for framing and sheet work.",
    sku: "ONA-DEMO-CAR-SAW-001",
    mpn: "BOSCH-GKS190",
    priceMinor: 1285000,
    qty: 12,
    status: "active",
    attributes: { bladeSize: 7.5, toolPower: 1400, material: "Steel" },
    keywords: ["circular saw", "bosch", "gks 190", "power tool"],
  },
  {
    id: "demo-carpenter-wood-screw-4x40-box",
    tradeKey: "carpenter",
    categorySlug: "screws",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Wood Screws 4×40mm Box",
    subtitle: "300 pcs · zinc plated",
    description: "Zinc-plated countersunk wood screws, 4×40mm, box of 300.",
    sku: "ONA-DEMO-CAR-SCR-001",
    mpn: "ONA-WS-4040",
    priceMinor: 480000,
    qty: 0,
    status: "unavailable",
    attributes: { material: "Steel", finish: "Zinc plated" },
    keywords: ["wood screws", "4x40", "zinc", "fasteners"],
  },
  {
    id: "demo-carpenter-hinge-brass-pair",
    tradeKey: "carpenter",
    categorySlug: "hinges",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Brass Hinge 4\" Pair",
    subtitle: "Loose pin · antique brass",
    description: "Antique brass 4-inch butt hinges with loose pins, supplied as a pair.",
    sku: "ONA-DEMO-CAR-HNG-001",
    mpn: "ONA-HNG-4",
    priceMinor: 950000,
    qty: 55,
    status: "active",
    attributes: { material: "Brass", finish: "Antique brass" },
    keywords: ["hinge", "brass", "4 inch", "door hardware"],
  },

  // ------------------------------ PAINTER ------------------------------
  {
    id: "demo-painter-emulsion-white-20l",
    tradeKey: "painter",
    categorySlug: "interior-paint",
    brand: { slug: "majesty", name: "Majesty" },
    name: "Majesty Silk Emulsion White 20L",
    subtitle: "Washable · low odour",
    description: "Washable silk emulsion paint in brilliant white, 20-litre pail for interior walls.",
    sku: "ONA-DEMO-PNT-EML-20",
    mpn: "MAJ-EML-20",
    priceMinor: 3850000,
    qty: 80,
    status: "active",
    attributes: { paintType: "Emulsion", finish: "Silk", volume: 20, coverage: 12, dryingTime: 4 },
    keywords: ["emulsion", "white", "20l", "interior paint", "majesty"],
  },
  {
    id: "demo-painter-exterior-gloss-blue-4l",
    tradeKey: "painter",
    categorySlug: "exterior-paint",
    brand: { slug: "dulux", name: "Dulux" },
    name: "Dulux Exterior Gloss Blue 4L",
    subtitle: "Weathershield · UV resistant",
    description: "Weathershield exterior gloss in royal blue, 4 litres, UV resistant for outdoor wood and metal.",
    sku: "ONA-DEMO-PNT-GLS-4L",
    mpn: "DULUX-WS-4",
    priceMinor: 2950000,
    qty: 0,
    status: "source_pending",
    attributes: { paintType: "Gloss", finish: "Gloss", volume: 4, coverage: 10, dryingTime: 6 },
    keywords: ["exterior paint", "gloss", "dulux", "weathershield"],
  },
  {
    id: "demo-painter-primer-sealer-5l",
    tradeKey: "painter",
    categorySlug: "primer",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Wall Primer Sealer 5L",
    subtitle: "Universal · stain blocking",
    description: "Universal wall primer sealer, 5 litres, for interior and exterior before top coat.",
    sku: "ONA-DEMO-PNT-PRM-5L",
    mpn: "ONA-PRM-5",
    priceMinor: 1450000,
    qty: 95,
    status: "active",
    attributes: { paintType: "Primer", finish: "Matt", volume: 5, coverage: 12, dryingTime: 2 },
    keywords: ["primer", "sealer", "5l", "wall", "ona pro"],
  },
  {
    id: "demo-painter-roller-set-9in",
    tradeKey: "painter",
    categorySlug: "rollers",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Paint Roller Set 9\"",
    subtitle: "Frame + 3 sleeves + tray",
    description: "Complete roller set with 9-inch frame, three pile sleeves and paint tray.",
    sku: "ONA-DEMO-PNT-ROLL-001",
    mpn: "ONA-RL-9",
    priceMinor: 650000,
    qty: 110,
    status: "active",
    attributes: { paintType: "Emulsion" },
    keywords: ["paint roller", "9 inch", "roller set", "painting"],
  },
  {
    id: "demo-painter-spray-gun-hvlp",
    tradeKey: "painter",
    categorySlug: "spray-guns",
    brand: { slug: "deVilbiss", name: "DeVilbiss" },
    name: "DeVilbiss HVLP Spray Gun",
    subtitle: "1.3mm nozzle · gravity feed",
    description: "HVLP gravity-feed spray gun with 1.3mm nozzle for automotive and furniture finishes.",
    sku: "ONA-DEMO-PNT-SG-001",
    mpn: "DEVI-FLG5",
    priceMinor: 5250000,
    qty: 8,
    status: "active",
    attributes: { paintType: "Automotive" },
    keywords: ["spray gun", "hvlp", "devilbiss", "painting"],
  },

  // ------------------------------ SOLAR ------------------------------
  {
    id: "demo-solar-panel-550w-mono",
    tradeKey: "solar",
    categorySlug: "solar-panels",
    brand: { slug: "ja-solar", name: "JA Solar" },
    name: "JA Solar 550W Mono Panel",
    subtitle: "Half-cell · 72-cell",
    description: "550W monocrystalline half-cell solar panel with 21.3% module efficiency.",
    sku: "ONA-DEMO-SOL-PANEL-550",
    mpn: "JA-550M72",
    priceMinor: 1850000,
    qty: 0,
    status: "unavailable",
    attributes: { wattage: 550, voltage: 42, panelType: "Monocrystalline", efficiency: 21.3 },
    keywords: ["solar panel", "550w", "monocrystalline", "ja solar"],
  },
  {
    id: "demo-solar-inverter-5kva-48v",
    tradeKey: "solar",
    categorySlug: "inverters",
    brand: { slug: "luminous", name: "Luminous" },
    name: "Luminous 5kVA 48V Hybrid Inverter",
    subtitle: "Solar + grid + generator",
    description: "5kVA 48V hybrid inverter supporting solar, grid and generator inputs with pure sine wave output.",
    sku: "ONA-DEMO-SOL-INV-5KVA",
    mpn: "LUM-5KVA-48",
    priceMinor: 1850000,
    qty: 15,
    status: "active",
    attributes: { capacity: 5, voltage: 48, inverterType: "Hybrid", wattage: 5000 },
    keywords: ["inverter", "5kva", "hybrid", "48v", "luminous"],
  },
  {
    id: "demo-solar-battery-lifepo4-200ah",
    tradeKey: "solar",
    categorySlug: "batteries",
    brand: { slug: "felicity", name: "Felicity" },
    name: "Felicity LiFePO4 Battery 12V 200Ah",
    subtitle: "Deep cycle · BMS included",
    description: "12V 200Ah LiFePO4 deep-cycle solar battery with integrated BMS and 4000+ cycles.",
    sku: "ONA-DEMO-SOL-BAT-200",
    mpn: "FEL-12V200",
    priceMinor: 4850000,
    qty: 32,
    status: "active",
    attributes: { wattage: 2560, voltage: 12, capacity: 2.56, panelType: "LiFePO4", efficiency: 95 },
    keywords: ["lifepo4", "solar battery", "200ah", "felicity", "deep cycle"],
  },
  {
    id: "demo-solar-mppt-60a-victron",
    tradeKey: "solar",
    categorySlug: "mppt",
    brand: { slug: "victron", name: "Victron" },
    name: "Victron SmartSolar MPPT 60A",
    subtitle: "150V · Bluetooth VE.Smart",
    description: "SmartSolar MPPT charge controller, 60A, 150V input with Bluetooth monitoring.",
    sku: "ONA-DEMO-SOL-MPPT-60",
    mpn: "VIC-SM60",
    priceMinor: 3850000,
    qty: 18,
    status: "active",
    attributes: { wattage: 1500, capacity: 60, voltage: 150, panelType: "Monocrystalline", inverterType: "String" },
    keywords: ["mppt", "charge controller", "victron", "60a"],
  },
  {
    id: "demo-solar-cable-6mm-red-50m",
    tradeKey: "solar",
    categorySlug: "solar-cables",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Solar Cable 6mm² Red 50m",
    subtitle: "TUV certified · UV resistant",
    description: "TUV-certified 6mm² solar PV cable in red, 50-metre roll, UV and weather resistant.",
    sku: "ONA-DEMO-SOL-CBL-6",
    mpn: "ONA-PV6-R50",
    priceMinor: 1250000,
    qty: 0,
    status: "future_product",
    attributes: { wattage: 1000, voltage: 1000 },
    keywords: ["solar cable", "6mm2", "pv cable", "uv resistant"],
  },

  // ------------------------------ GENERATOR ------------------------------
  {
    id: "demo-gen-portable-3-5kva-petrol",
    tradeKey: "generator",
    categorySlug: "portable-generators",
    brand: { slug: "felicity", name: "Felicity" },
    name: "Felicity 3.5kVA Petrol Generator",
    subtitle: "Portable · recoil start",
    description: "3.5kVA petrol portable generator with recoil start and 25L fuel tank.",
    sku: "ONA-DEMO-GEN-3P5",
    mpn: "FEL-3.5PET",
    priceMinor: 3250000,
    qty: 0,
    status: "unavailable",
    attributes: { kva: 3.5, fuelType: "Petrol", phase: "Single", runTime: 8, tankCapacity: 25, startType: "Recoil" },
    keywords: ["generator", "3.5kva", "petrol", "portable", "felicity"],
  },
  {
    id: "demo-gen-diesel-10kva-silent",
    tradeKey: "generator",
    categorySlug: "diesel",
    brand: { slug: "elepaq", name: "Elepaq" },
    name: "Elepaq Silent Diesel Generator 10kVA",
    subtitle: "Soundproof canopy · AVR",
    description: "10kVA silent diesel generator in soundproof canopy with AVR and electric start.",
    sku: "ONA-DEMO-GEN-10D",
    mpn: "ELP-10D",
    priceMinor: 1850000,
    qty: 6,
    status: "active",
    attributes: { kva: 10, fuelType: "Diesel", phase: "Single", runTime: 10, tankCapacity: 40, startType: "Electric" },
    keywords: ["diesel generator", "10kva", "silent", "elepaq", "avr"],
  },
  {
    id: "demo-gen-avr-5kva-alternator",
    tradeKey: "generator",
    categorySlug: "avr",
    brand: { slug: "lem", name: "LEM" },
    name: "LEM AVR Automatic Voltage Regulator",
    subtitle: "Fits 3–5kVA alternators",
    description: "Automatic voltage regulator for 3–5kVA generator alternators, 220V output.",
    sku: "ONA-DEMO-GEN-AVR-001",
    mpn: "LEM-AVR5",
    priceMinor: 3850000,
    qty: 28,
    status: "active",
    attributes: { kva: 5, phase: "Single" },
    keywords: ["avr", "voltage regulator", "alternator", "generator part"],
  },
  {
    id: "demo-gen-transfer-switch-100a",
    tradeKey: "generator",
    categorySlug: "transfer-switches",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Automatic Transfer Switch 100A",
    subtitle: "2-pole · grid + generator",
    description: "100A automatic transfer switch for seamless grid-to-generator switching.",
    sku: "ONA-DEMO-GEN-TS-001",
    mpn: "ONA-ATS-100",
    priceMinor: 5850000,
    qty: 9,
    status: "active",
    attributes: { kva: 22, fuelType: "Diesel", phase: "Single", startType: "Auto" },
    keywords: ["transfer switch", "ats", "100a", "generator"],
  },
  {
    id: "demo-gen-fuel-filter-eco-diesel",
    tradeKey: "generator",
    categorySlug: "fuel-systems",
    brand: { slug: "donaldson", name: "Donaldson" },
    name: "Donaldson Diesel Fuel Filter",
    subtitle: "Spin-on · water separator",
    description: "Spin-on diesel fuel filter with integrated water separator for generator fuel systems.",
    sku: "ONA-DEMO-GEN-FF-001",
    mpn: "DON-P550403",
    priceMinor: 1250000,
    qty: 0,
    status: "pending_verification",
    attributes: { kva: 10, fuelType: "Diesel" },
    keywords: ["fuel filter", "diesel", "water separator", "donaldson"],
  },
];

export function demoProductsForTrade(tradeKey: string): DemoProduct[] {
  return DEMO_PRODUCTS.filter((p) => p.tradeKey === tradeKey);
}

export function demoProductCountByTrade(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const p of DEMO_PRODUCTS) {
    out[p.tradeKey] = (out[p.tradeKey] ?? 0) + 1;
  }
  return out;
}

export const DEMO_TRADE_KEYS = [
  "mechanic",
  "vulcanizer",
  "towing",
  "ac",
  "battery",
  "body",
  "electrical",
  "diagnostics",
  "wash",
  "plumber",
  "carpenter",
  "painter",
  "solar",
  "generator",
] as const;
