/**
 * Trade seed catalogs, deeper shop stock for every non-Automedics trade.
 *
 * Flows through the standard demo import pipeline (ona_demo connector) so
 * admins load it exactly like any other source: Admin → Shop → Data sources.
 * Deterministic demo-* ids/skus keep re-imports idempotent.
 *
 * Invariants (enforced by demo-catalog.test.ts):
 * - id starts with "demo-"
 * - categorySlug exists in the trade's taxonomy roots
 * - attributes use only schema keys, include required keys, and never use
 *   vehicle-fitment keys on vehicle-forbidden trades
 */

import type { DemoProduct } from "@/lib/shop/demo-catalog";

type Seed = {
  slug: string;
  name: string;
  sub: string;
  desc: string;
  brand: string;
  /** Naira major units */
  price: number;
  qty: number;
  cat: string;
  attrs: Record<string, string | number | boolean>;
  kw: string[];
};

function build(trade: string, seeds: Seed[]): DemoProduct[] {
  return seeds.map((s, i) => ({
    id: `demo-seed-${trade}-${s.slug}`,
    tradeKey: trade,
    categorySlug: s.cat,
    brand: { slug: s.brand.toLowerCase().replace(/[^a-z0-9]+/g, "-"), name: s.brand },
    name: s.name,
    subtitle: s.sub,
    description: s.desc,
    sku: `ONA-SEED-${trade.toUpperCase().slice(0, 4)}-${String(i + 1).padStart(3, "0")}`,
    priceMinor: s.price * 100,
    qty: s.qty,
    status: "active" as const,
    attributes: s.attrs,
    keywords: [...s.kw, s.brand.toLowerCase(), trade],
  }));
}

// ───────────────────────────── TOWING ──────────────────────────────────────
// roots: tow-straps,chains,winches,tow-bars,dollies,recovery-equipment,
//        warning-equipment,trailer-equipment,towing-accessories
// required attr: capacity (number)
const TOWING = build("towing", [
  { slug: "tow-rope-5t", name: "Heavy-Duty Tow Rope 5 Ton", sub: "5m nylon tow strap with forged hooks", desc: "5-ton rated nylon tow rope with reinforced forged hooks on both ends. Elastic rebound reduces jerks on low-speed recoveries.", brand: "RoadRescue", price: 18500, qty: 30, cat: "tow-straps", attrs: { capacity: 5, length: 5, material: "Nylon" }, kw: ["tow rope", "tow strap", "recovery"] },
  { slug: "tow-strap-8t", name: "Kinetic Recovery Strap 8 Ton", sub: "9m kinetic rope for stuck vehicles", desc: "8-ton kinetic recovery strap that stretches to pull stuck vehicles out of mud or sand without shock-loading the chassis.", brand: "RoadRescue", price: 32000, qty: 18, cat: "tow-straps", attrs: { capacity: 8, length: 9, material: "Nylon" }, kw: ["kinetic strap", "recovery", "mud"] },
  { slug: "tow-bar-fixed", name: "Fixed Tow Bar with 50mm Ball", sub: "Universal tow bar · sedan/SUV", desc: "Heavy steel fixed tow bar with standard 50mm ball hitch. Fits most sedans and compact SUVs with existing mounting points.", brand: "TowMaster", price: 65000, qty: 12, cat: "tow-bars", attrs: { capacity: 1500, material: "Steel" }, kw: ["tow bar", "ball hitch"] },
  { slug: "winch-12000lb", name: "Electric Winch 12000 lb", sub: "12V winch with steel cable + remote", desc: "12,000 lb pull 12V electric winch with planetary gear, steel cable, wired and wireless remote controls. Truck/SUV mount.", brand: "PullPro", price: 285000, qty: 6, cat: "winches", attrs: { capacity: 5443, winchType: "Electric", material: "Steel" }, kw: ["winch", "recovery", "offroad"] },
  { slug: "winch-synthetic-9500", name: "Winch 9500 lb Synthetic Rope", sub: "Sealed winch with synthetic line", desc: "9,500 lb sealed electric winch with lightweight synthetic rope and aluminium fairlead. Corrosion-resistant for rainy-season recoveries.", brand: "PullPro", price: 342000, qty: 5, cat: "winches", attrs: { capacity: 4310, winchType: "Electric", material: "Composite" }, kw: ["winch", "synthetic rope"] },
  { slug: "tow-dolly", name: "Car Tow Dolly 2-Wheel", sub: "Tow dolly with straps for FWD cars", desc: "Two-wheel tow dolly with ratchet tire straps and surge coupler. Tows front-wheel-drive cars behind any vehicle.", brand: "TowMaster", price: 450000, qty: 3, cat: "dollies", attrs: { capacity: 2000, material: "Steel" }, kw: ["tow dolly", "flat tow"] },
  { slug: "recovery-track-boards", name: "Recovery Track Boards (Pair)", sub: "Traction boards for sand and mud", desc: "Pair of high-traction recovery boards that grip tires in sand, mud, or snow. UV-stabilised, 4-ton flex rating.", brand: "TrailGrip", price: 78000, qty: 22, cat: "recovery-equipment", attrs: { capacity: 4000, length: 115, material: "Composite" }, kw: ["traction boards", "sand"] },
  { slug: "snatch-block-8t", name: "Snatch Block Pulley 8 Ton", sub: "Double your winch pull power", desc: "8-ton snatch block pulley for winch angle changes and doubling pull capacity. Fits up to 28mm synthetic line.", brand: "PullPro", price: 42000, qty: 15, cat: "recovery-equipment", attrs: { capacity: 8000, material: "Cast iron" }, kw: ["snatch block", "pulley"] },
  { slug: "tow-hitch-stabilizer", name: "Tow Hitch Stabilizer Clamp", sub: "Anti-rattle clamp for 50mm receivers", desc: "Heavy-gauge stabiliser clamp that eliminates hitch rattle and play on 50mm receiver tow bars.", brand: "TowMaster", price: 15500, qty: 25, cat: "towing-accessories", attrs: { capacity: 3000, material: "Steel" }, kw: ["hitch stabilizer", "anti rattle"] },
  { slug: "emergency-tow-kit", name: "Emergency Tow Kit 3 Ton", sub: "Rope + hooks + gloves + triangle", desc: "Complete emergency towing kit: 3-ton rope, two hooks, work gloves, and reflective warning triangle in a storage bag.", brand: "RoadRescue", price: 22500, qty: 35, cat: "towing-accessories", attrs: { capacity: 3, length: 4, material: "Nylon" }, kw: ["emergency kit", "tow kit"] },
  { slug: "flatbed-ratchet-set", name: "Flatbed Ratchet Strap Set (4)", sub: "5m ratchet straps for transport", desc: "Set of four 5m ratchet straps rated 2.5 tons each, secures vehicles on flatbeds and trailers without slipping.", brand: "RoadRescue", price: 28000, qty: 28, cat: "chains", attrs: { capacity: 2500, length: 5, material: "Polyester" }, kw: ["ratchet strap", "flatbed"] },
  { slug: "warning-triangle-led", name: "LED Warning Triangle Set", sub: "Reflective breakdown warning", desc: "Set of reflective warning triangles with LED flasher mode, keeps breakdown scenes safe at night.", brand: "TrailGrip", price: 9500, qty: 40, cat: "warning-equipment", attrs: { capacity: 0, material: "PVC" }, kw: ["warning triangle", "breakdown"] },
]);

// ───────────────────────────── BATTERY ─────────────────────────────────────
// roots: vehicle-batteries,battery-chargers,battery-testers,jump-starters,
//        terminals,cables,battery-boxes,battery-accessories,diagnostic-equipment
// required: voltage, capacityAh · enums: batteryType[Lead-acid/AGM/Gel/Lithium-ion/LiFePO4], terminalType[Top post/Side post/L-terminal]
const BATTERY = build("battery", [
  { slug: "battery-75ah", name: "75Ah Maintenance-Free Battery", sub: "12V MF battery · 1-year warranty", desc: "75Ah 12V maintenance-free battery with calcium grid technology. High cranking power for sedans and small SUVs.", brand: "PowerCell", price: 92000, qty: 40, cat: "vehicle-batteries", attrs: { voltage: 12, capacityAh: 75, batteryType: "Lead-acid", terminalType: "Top post", crankingAmps: 630 }, kw: ["car battery", "75ah"] },
  { slug: "battery-100ah", name: "100Ah Deep-Cycle Battery", sub: "12V deep cycle for heavy duty", desc: "100Ah deep-cycle battery built for repeated discharge, SUVs, vans, and auxiliary power setups.", brand: "PowerCell", price: 138000, qty: 25, cat: "vehicle-batteries", attrs: { voltage: 12, capacityAh: 100, batteryType: "Lead-acid", terminalType: "Top post", crankingAmps: 800 }, kw: ["deep cycle", "100ah battery"] },
  { slug: "battery-45ah", name: "45Ah Compact Car Battery", sub: "12V for small cars and keke", desc: "Compact 45Ah battery for small displacement engines, Corolla, Kia Rio, tricycles and small generators.", brand: "PowerCell", price: 61000, qty: 45, cat: "vehicle-batteries", attrs: { voltage: 12, capacityAh: 45, batteryType: "Lead-acid", terminalType: "Top post", crankingAmps: 390 }, kw: ["small battery", "45ah"] },
  { slug: "battery-80ah-agm", name: "80Ah AGM Start-Stop Battery", sub: "AGM for start-stop vehicles", desc: "Absorbent Glass Mat battery engineered for start-stop systems, 2× cycle life versus flooded batteries.", brand: "VoltaMax", price: 165000, qty: 15, cat: "vehicle-batteries", attrs: { voltage: 12, capacityAh: 80, batteryType: "AGM", terminalType: "Top post", crankingAmps: 740 }, kw: ["agm", "start stop battery"] },
  { slug: "battery-terminal-clamps", name: "Battery Terminal Clamps (Pair)", sub: "Lead replacement clamps, + and −", desc: "Pair of cast lead replacement terminal clamps for corroded or stripped battery ends. Marked positive/negative.", brand: "VoltTools", price: 4800, qty: 50, cat: "terminals", attrs: { voltage: 12, capacityAh: 0, batteryType: "Lead-acid", terminalType: "Top post", crankingAmps: 0 }, kw: ["terminal clamp", "lead"] },
  { slug: "battery-tester-digital", name: "Digital Battery Tester 12V", sub: "CCA, voltage and health readout", desc: "Digital conductance tester reads voltage, CCA, internal resistance and overall health in 3 seconds. Works on discharged batteries.", brand: "VoltTools", price: 27500, qty: 20, cat: "battery-testers", attrs: { voltage: 12, capacityAh: 200, batteryType: "AGM", terminalType: "Top post", crankingAmps: 2000 }, kw: ["battery tester", "cca"] },
  { slug: "battery-charger-10a", name: "Smart Charger 10A 12V", sub: "Automatic charging + repair mode", desc: "10-amp smart charger with automatic bulk/absorption/float stages plus a desulphation repair mode for flat batteries.", brand: "VoltaMax", price: 48000, qty: 18, cat: "battery-chargers", attrs: { voltage: 12, capacityAh: 10, batteryType: "AGM", terminalType: "L-terminal", crankingAmps: 0 }, kw: ["battery charger", "smart charger"] },
  { slug: "battery-105ah-truck", name: "105Ah Truck Battery", sub: "12V heavy-duty for trucks/buses", desc: "105Ah heavy-duty commercial battery with vibration-resistant plates for trucks, buses and plant equipment.", brand: "PowerCell", price: 172000, qty: 12, cat: "vehicle-batteries", attrs: { voltage: 12, capacityAh: 105, batteryType: "Lead-acid", terminalType: "Side post", crankingAmps: 920 }, kw: ["truck battery", "105ah"] },
  { slug: "battery-hold-down", name: "Battery Hold-Down Bracket", sub: "Anti-vibration clamp kit", desc: "Universal hold-down bracket with J-bolts, stops battery vibration that cracks internal plates on bad roads.", brand: "VoltTools", price: 5200, qty: 40, cat: "battery-accessories", attrs: { voltage: 12, capacityAh: 0, batteryType: "AGM", terminalType: "Top post", crankingAmps: 0 }, kw: ["hold down", "battery clamp"] },
  { slug: "battery-inverter-220ah", name: "220Ah Inverter Battery", sub: "12V tall-tubular for home backup", desc: "220Ah tall-tubular battery optimised for inverter backup systems, long runtime and 5-year design life.", brand: "VoltaMax", price: 295000, qty: 10, cat: "vehicle-batteries", attrs: { voltage: 12, capacityAh: 220, batteryType: "Gel", terminalType: "Top post", crankingAmps: 0 }, kw: ["inverter battery", "220ah", "tubular"] },
  { slug: "jumper-cables-800a", name: "Jumper Cables 800A 3m", sub: "Thick-copper booster cables", desc: "3-metre 800-amp jumper cables with insulated clamps, starts dead batteries from another car safely.", brand: "VoltTools", price: 16500, qty: 38, cat: "cables", attrs: { voltage: 12, capacityAh: 0, batteryType: "AGM", terminalType: "Top post", crankingAmps: 800 }, kw: ["jumper cables", "booster"] },
  { slug: "jump-starter-lithium", name: "Lithium Jump Starter 2000A", sub: "Pocket-sized · power bank too", desc: "2000-peak-amp lithium jump starter that fits in the glove box, starts V8s and doubles as a power bank.", brand: "VoltaMax", price: 58000, qty: 20, cat: "jump-starters", attrs: { voltage: 12, capacityAh: 24, batteryType: "Lithium-ion", terminalType: "Top post", crankingAmps: 2000 }, kw: ["jump starter", "lithium"] },
]);

// ───────────────────────────── A/C ─────────────────────────────────────────
// roots: vehicle-ac,commercial-ac,industrial-ac,compressors,condensers,
//        evaporators,blowers,fans,controls,sensors,refrigeration-equipment,ac-tools
// required: btuCapacity · enums: refrigerant[R-134a/R-410A/R-32/R-22/R-404A/R-600a],
//           compressorType[Rotary/Scroll/Reciprocating/Screw],
//           application[Vehicle A/C/Commercial A/C/Industrial A/C/Residential A/C]
const AC = build("ac", [
  { slug: "ac-compressor-toyota", name: "A/C Compressor Toyota Camry", sub: "OEM-spec compressor · R-134a", desc: "Complete A/C compressor for Toyota Camry 2012-2022. Pre-filled with oil, R-134a refrigerant, direct bolt-on fit.", brand: "ChillAuto", price: 148000, qty: 12, cat: "compressors", attrs: { refrigerant: "R-134a", btuCapacity: 18000, voltage: 12, compressorType: "Scroll", application: "Vehicle A/C" }, kw: ["ac compressor", "camry"] },
  { slug: "ac-condenser-honda", name: "A/C Condenser Honda Accord", sub: "Aluminium parallel-flow condenser", desc: "Parallel-flow aluminium condenser for Honda Accord 2010-2020. High heat rejection with corrosion-resistant fins.", brand: "ChillAuto", price: 82000, qty: 14, cat: "condensers", attrs: { refrigerant: "R-134a", btuCapacity: 16000, voltage: 12, compressorType: "Reciprocating", application: "Vehicle A/C" }, kw: ["condenser", "accord"] },
  { slug: "ac-evaporator-coil", name: "Universal Evaporator Coil", sub: "Under-dash cooling coil 12V", desc: "Universal under-dash evaporator coil with 3-speed blower, adds cold air to vehicles without factory A/C.", brand: "ChillAuto", price: 96000, qty: 9, cat: "evaporators", attrs: { refrigerant: "R-134a", btuCapacity: 12000, voltage: 12, compressorType: "Rotary", application: "Vehicle A/C" }, kw: ["evaporator", "under dash ac"] },
  { slug: "r134a-refill-can", name: "R-134a Refrigerant Can 450g", sub: "DIY top-up refrigerant", desc: "450g self-sealing can of R-134a refrigerant with recharge hose, tops up low A/C systems without a shop visit.", brand: "FreezePro", price: 9500, qty: 80, cat: "ac-tools", attrs: { refrigerant: "R-134a", btuCapacity: 1, voltage: 0, compressorType: "Rotary", application: "Vehicle A/C" }, kw: ["r134a", "refrigerant", "ac gas"] },
  { slug: "ac-compressor-sanden", name: "Sanden-Style Compressor 7H13", sub: "7-cylinder universal compressor", desc: "Sanden 7H13-style 7-cylinder compressor, the universal standard for custom and replacement A/C builds.", brand: "ChillAuto", price: 132000, qty: 10, cat: "compressors", attrs: { refrigerant: "R-134a", btuCapacity: 20000, voltage: 12, compressorType: "Scroll", application: "Vehicle A/C" }, kw: ["sanden", "compressor"] },
  { slug: "ac-blower-motor", name: "A/C Blower Motor 12V", sub: "High-airflow cabin blower", desc: "High-airflow 12V blower motor with cage fan. Restores strong airflow at all speed settings.", brand: "ChillAuto", price: 34000, qty: 22, cat: "blowers", attrs: { refrigerant: "R-134a", btuCapacity: 8000, voltage: 12, compressorType: "Rotary", application: "Vehicle A/C" }, kw: ["blower motor", "fan"] },
  { slug: "ac-expansion-valve", name: "A/C Expansion Valve Block", sub: "Block-type expansion valve", desc: "Block-type thermostatic expansion valve regulating refrigerant flow. Restores even cooling after compressor swap.", brand: "FreezePro", price: 18500, qty: 26, cat: "controls", attrs: { refrigerant: "R-134a", btuCapacity: 15000, voltage: 0, compressorType: "Reciprocating", application: "Vehicle A/C" }, kw: ["expansion valve"] },
  { slug: "ac-pressure-switch", name: "A/C Pressure Switch Trinary", sub: "High/low pressure safety switch", desc: "Trinary pressure switch, protects the compressor by cutting it off on high pressure or low charge.", brand: "FreezePro", price: 8500, qty: 30, cat: "controls", attrs: { refrigerant: "R-134a", btuCapacity: 9000, voltage: 12, compressorType: "Scroll", application: "Vehicle A/C" }, kw: ["pressure switch", "trinary"] },
  { slug: "ac-manifold-gauge", name: "Manifold Gauge Set R-134a", sub: "Gauges + 3 hoses + couplers", desc: "Complete manifold gauge set for R-134a, low/high gauges, three 60cm hoses, quick couplers and case.", brand: "FreezePro", price: 42000, qty: 16, cat: "ac-tools", attrs: { refrigerant: "R-134a", btuCapacity: 5000, voltage: 0, compressorType: "Reciprocating", application: "Vehicle A/C" }, kw: ["manifold gauge", "ac gauge"] },
  { slug: "ac-flush-kit", name: "A/C System Flush Kit", sub: "Clean lines after compressor failure", desc: "A/C flush kit with solvent canister and fittings, clears debris and old oil from lines after a compressor burnout.", brand: "FreezePro", price: 24000, qty: 12, cat: "ac-tools", attrs: { refrigerant: "R-134a", btuCapacity: 6000, voltage: 0, compressorType: "Reciprocating", application: "Vehicle A/C" }, kw: ["ac flush", "line cleaner"] },
  { slug: "ac-filter-drier", name: "Receiver Drier Filter", sub: "Moisture filter for A/C lines", desc: "Receiver drier that traps moisture and debris, replace every time the system is opened, or cooling will drop.", brand: "ChillAuto", price: 14500, qty: 28, cat: "refrigeration-equipment", attrs: { refrigerant: "R-134a", btuCapacity: 11000, voltage: 0, compressorType: "Rotary", application: "Vehicle A/C" }, kw: ["receiver drier", "filter drier"] },
  { slug: "ac-condenser-fan-12", name: "12\" Condenser Fan 12V", sub: "Slim push-pull electric fan", desc: "Slim 12-inch 12V condenser fan with mounting brackets, boosts cooling in traffic and hot climates.", brand: "ChillAuto", price: 26500, qty: 20, cat: "fans", attrs: { refrigerant: "R-134a", btuCapacity: 10000, voltage: 12, compressorType: "Rotary", application: "Vehicle A/C" }, kw: ["condenser fan", "radiator fan"] },
]);

// ───────────────────────────── BODY ────────────────────────────────────────
// roots: doors,bonnets,trunks,fenders,bumpers,grilles,mirrors,panels,
//        headlights,tail-lights,glass,body-hardware,paint,body-repair,body-tools
// enums: panelType[Door/Bonnet/Trunk/Fender/Bumper/Grille/Mirror/Panel/Headlight/Tail light/Glass]
const BODY = build("body", [
  { slug: "front-bumper-toyota", name: "Front Bumper Cover Toyota Corolla", sub: "Primed · 2019-2024", desc: "Unpainted primed front bumper cover for Corolla 2019-2024. Flexible PP plastic, ready for body-colour spray.", brand: "BodyLine", price: 85000, qty: 10, cat: "bumpers", attrs: { panelType: "Bumper", material: "PVC", paintCode: "primer" }, kw: ["front bumper", "corolla"] },
  { slug: "front-bumper-honda", name: "Front Bumper Cover Honda Civic", sub: "Primed · 2016-2021", desc: "OEM-fit front bumper cover for Civic 2016-2021. Impact-tolerant polypropylene with grille mounting points.", brand: "BodyLine", price: 92000, qty: 8, cat: "bumpers", attrs: { panelType: "Bumper", material: "PVC", paintCode: "primer" }, kw: ["front bumper", "civic"] },
  { slug: "front-grille-sport", name: "Sport Mesh Front Grille", sub: "Gloss black honeycomb mesh", desc: "Gloss-black honeycomb sport grille, direct swap for the factory grille, instantly sharpens the front end.", brand: "BodyLine", price: 48000, qty: 15, cat: "grilles", attrs: { panelType: "Grille", material: "Composite", paintCode: "gloss-black" }, kw: ["grille", "sport mesh"] },
  { slug: "headlight-assembly-led", name: "LED Projector Headlight (Pair)", sub: "DRL + sequential indicator", desc: "Pair of LED projector headlights with DRL strip and sequential turn signals. Plug-and-play wiring, DOT-style lens.", brand: "LumaDrive", price: 185000, qty: 7, cat: "headlights", attrs: { panelType: "Headlight", material: "Glass", paintCode: "n/a" }, kw: ["headlight", "led projector", "drl"] },
  { slug: "fender-left-toyota", name: "Left Fender Toyota Camry", sub: "Primed steel · 2015-2022", desc: "Primed steel left fender for Camry 2015-2022. E-coated inner surface resists rust from the inside out.", brand: "BodyLine", price: 56000, qty: 9, cat: "fenders", attrs: { panelType: "Fender", material: "Steel", paintCode: "primer" }, kw: ["fender", "camry"] },
  { slug: "bonnet-hood-toyota", name: "Bonnet/Hood Toyota Corolla", sub: "Steel · 2019-2024", desc: "Steel bonnet with factory-style creases and undercoating. Aligns to factory hinge and latch points.", brand: "BodyLine", price: 110000, qty: 6, cat: "bonnets", attrs: { panelType: "Bonnet", material: "Steel", paintCode: "primer" }, kw: ["bonnet", "hood"] },
  { slug: "side-mirror-powered", name: "Powered Side Mirror (Left)", sub: "Heated · electric fold · indicator", desc: "Left powered side mirror with heating, electric fold and built-in indicator. Wiring pigtail included.", brand: "LumaDrive", price: 42000, qty: 12, cat: "mirrors", attrs: { panelType: "Mirror", material: "Glass", paintCode: "primer" }, kw: ["side mirror", "powered"] },
  { slug: "rear-bumper-diffuser", name: "Rear Bumper Diffuser Lip", sub: "Gloss black diffuser", desc: "Gloss-black rear diffuser lip that mounts under the rear bumper, sporty finish and scuff protection.", brand: "BodyLine", price: 38000, qty: 14, cat: "bumpers", attrs: { panelType: "Bumper", material: "Composite", paintCode: "gloss-black" }, kw: ["diffuser", "rear lip"] },
  { slug: "door-shell-skin", name: "Door Skin Panel (Front Left)", sub: "Weld-on outer skin", desc: "Weld-on outer door skin for rusted or accident-damaged doors. E-coated, requires professional fitting and spray.", brand: "BodyLine", price: 39000, qty: 8, cat: "doors", attrs: { panelType: "Door", material: "Steel", paintCode: "primer" }, kw: ["door skin", "panel"] },
  { slug: "body-filler-1kg", name: "Body Filler 1kg + Hardener", sub: "Smooth sanding polyester filler", desc: "1kg two-part polyester body filler with hardener. Spreads smooth, sands easily, non-porous finish.", brand: "FillPro", price: 9500, qty: 45, cat: "body-repair", attrs: { panelType: "Panel", material: "Composite", paintCode: "n/a" }, kw: ["body filler", "bondo"] },
  { slug: "spray-gun-hvlp", name: "HVLP Spray Gun 1.3mm", sub: "Gravity-feed base/clear gun", desc: "Gravity-feed HVLP spray gun with 1.3mm tip and 600ml cup. Professional orange-peel-free finish with correct technique.", brand: "FillPro", price: 56000, qty: 10, cat: "body-tools", attrs: { panelType: "Panel", material: "Aluminium", paintCode: "n/a" }, kw: ["spray gun", "hvlp"] },
  { slug: "tail-light-assembly", name: "LED Tail Light Assembly (Right)", sub: "Smoked lens · plug-and-play", desc: "Right-side LED tail light with smoked lens and dynamic indicator. Sealed housing, no condensation.", brand: "LumaDrive", price: 68000, qty: 11, cat: "tail-lights", attrs: { panelType: "Tail light", material: "Glass", paintCode: "n/a" }, kw: ["tail light", "smoked"] },
]);

// ─────────────────────────── ELECTRICAL ────────────────────────────────────
// roots: cables,wires,switches,sockets,breakers,contactors,relays,transformers,
//        motors,panels,distribution,lighting,testing-equipment,industrial-electrical,automotive-electrical
const ELECTRICAL = build("electrical", [
  { slug: "alternator-100a", name: "Alternator 100A Toyota/Honda", sub: "12V · high-output replacement", desc: "100-amp 12V alternator covering popular Toyota and Honda fitments. New unit, not refurbished.", brand: "AmpFlow", price: 98000, qty: 12, cat: "automotive-electrical", attrs: { voltage: 12, amperage: 100 }, kw: ["alternator", "100a"] },
  { slug: "starter-motor", name: "Starter Motor 12V", sub: "OEM-spec reduction-gear starter", desc: "Reduction-gear starter motor for fast, reliable cranking in hot and cold conditions. New solenoid included.", brand: "AmpFlow", price: 74000, qty: 10, cat: "automotive-electrical", attrs: { voltage: 12, amperage: 150 }, kw: ["starter motor"] },
  { slug: "wiring-harness-tape", name: "Harness Tape 19mm × 15m", sub: "High-temp wiring loom tape", desc: "Heat-resistant cloth harness tape for bundling and repairing engine-bay wiring looms. Non-sticky residue.", brand: "WireWorks", price: 4200, qty: 55, cat: "cables", attrs: { voltage: 0, amperage: 0 }, kw: ["harness tape", "loom"] },
  { slug: "fuse-box-relay-kit", name: "Relay & Fuse Assortment 120pc", sub: "12V relays + blade fuses", desc: "120-piece kit: 40A/30A 5-pin relays plus mini/standard blade fuses 5A-30A. Covers every 12V repair.", brand: "WireWorks", price: 12500, qty: 40, cat: "relays", attrs: { voltage: 12, amperage: 40 }, kw: ["relay", "fuse kit"] },
  { slug: "headlight-wiring-loom", name: "Headlight Wiring Loom Upgrade", sub: "Relay loom for brighter lights", desc: "Pre-wired relay loom that feeds headlights straight from the battery, up to 30% brighter beams, less switch load.", brand: "WireWorks", price: 15500, qty: 22, cat: "automotive-electrical", attrs: { voltage: 12, amperage: 20 }, kw: ["headlight loom", "relay harness"] },
  { slug: "ignition-coil-pack", name: "Ignition Coil Pack", sub: "Direct-fit 3-pin coil", desc: "Direct-fit ignition coil with epoxy potting for heat resistance. Cures misfires and rough idle on coil-pack engines.", brand: "AmpFlow", price: 22000, qty: 30, cat: "automotive-electrical", attrs: { voltage: 12, amperage: 10 }, kw: ["ignition coil", "coil pack"] },
  { slug: "battery-cable-set", name: "Battery Cable Set 4AWG", sub: "Positive + negative with terminals", desc: "4AWG copper battery cable set with crimped terminal lugs and heat-shrink. Solves slow crank from thin stock cables.", brand: "WireWorks", price: 18500, qty: 26, cat: "cables", attrs: { voltage: 12, amperage: 250 }, kw: ["battery cable", "4awg"] },
  { slug: "electric-fan-relay-kit", name: "Electric Fan Relay Thermostat Kit", sub: "Auto fan control 80-85°C", desc: "Relay + adjustable thermostat kit that runs your electric fan automatically between 80-85°C. Stops heat-ups in traffic.", brand: "WireWorks", price: 14500, qty: 24, cat: "relays", attrs: { voltage: 12, amperage: 30 }, kw: ["fan relay", "thermostat"] },
  { slug: "led-headlight-bulbs", name: "LED Headlight Bulbs H4 6000K", sub: "Pair · fanless · CANbus-safe", desc: "Fanless H4 LED bulb pair, 6000K, CANbus-safe decoding. 3× the light of halogen with a clean cutoff.", brand: "LumaDrive", price: 32000, qty: 35, cat: "lighting", attrs: { voltage: 12, amperage: 3 }, kw: ["led headlight", "h4"] },
  { slug: "distribution-block", name: "Power Distribution Block 4-Way", sub: "Clean multi-accessory wiring", desc: "4-way power distribution block with fuses, tidy way to feed dashcam, lights, and inverters from one source.", brand: "WireWorks", price: 9800, qty: 28, cat: "distribution", attrs: { voltage: 12, amperage: 100 }, kw: ["distribution block", "fuse block"] },
  { slug: "window-switch-pack", name: "Power Window Switch Pack", sub: "Master 4-gang switch", desc: "Master 4-gang power window switch pack with illuminated buttons. Direct replacement for worn OEM switch panels.", brand: "AmpFlow", price: 13500, qty: 18, cat: "switches", attrs: { voltage: 12, amperage: 20 }, kw: ["window switch", "master switch"] },
  { slug: "solar-panel-trickle", name: "Solar Trickle Charger 20W", sub: "Keeps battery topped up when parked", desc: "20W amorphous solar panel with OBD/battery-lead cables, maintains charge on cars parked for weeks.", brand: "VoltaMax", price: 29500, qty: 16, cat: "lighting", attrs: { voltage: 12, amperage: 1.5 }, kw: ["solar charger", "trickle"] },
]);

// ─────────────────────────── DIAGNOSTICS ───────────────────────────────────
// roots: obd-scanners,diagnostic-scanners,code-readers,diagnostic-cables,adapters,
//        oscilloscopes,battery-testers,tpms-tools,ecu-tools,diagnostic-accessories,vehicle-coverage
// enums: protocol[OBD-II/CAN/J1850/ISO 9141/KWP2000],
//        connectivity[Bluetooth/Wi-Fi/USB/Wired], displayType[Color/Monochrome/None (mobile app)]
const DIAGNOSTICS = build("diagnostics", [
  { slug: "obd2-scanner-pro", name: "OBD2 Scanner Pro Tablet", sub: "Full-system scan + live data", desc: "Tablet-style diagnostic scanner: engine, transmission, ABS, airbag systems with live data streams and freeze-frame.", brand: "DiagTech", price: 245000, qty: 8, cat: "diagnostic-scanners", attrs: { protocol: "OBD-II", connectivity: "Wi-Fi", updateable: true, displayType: "Color" }, kw: ["obd2 scanner", "diagnostics"] },
  { slug: "obd2-bluetooth-mini", name: "Mini Bluetooth OBD2 Adapter", sub: "Phone-based basic diagnostics", desc: "Palm-sized Bluetooth OBD2 adapter, pairs with free phone apps to read engine codes and live sensors.", brand: "DiagTech", price: 18500, qty: 45, cat: "obd-scanners", attrs: { protocol: "OBD-II", connectivity: "Bluetooth", updateable: false, displayType: "None (mobile app)" }, kw: ["obd2 bluetooth", "elm327"] },
  { slug: "code-reader-cable", name: "Handheld Code Reader", sub: "Standalone read/clear codes", desc: "Standalone handheld code reader, reads and clears engine codes, shows I/M readiness. No phone needed.", brand: "DiagTech", price: 34000, qty: 20, cat: "code-readers", attrs: { protocol: "OBD-II", connectivity: "Wired", updateable: false, displayType: "Monochrome" }, kw: ["code reader"] },
  { slug: "battery-tester-printer", name: "Battery/System Tester + Printer", sub: "Prints test results for customers", desc: "Conductance battery/system tester with built-in printer, hands customers a printed health report.", brand: "DiagTech", price: 128000, qty: 6, cat: "battery-testers", attrs: { protocol: "OBD-II", connectivity: "Wired", updateable: true, displayType: "Color" }, kw: ["battery tester", "printer"] },
  { slug: "multimeter-automotive", name: "Automotive Multimeter CAT III", sub: "Duty cycle, RPM, Dwell modes", desc: "Automotive-rated multimeter with RPM, dwell, duty-cycle and diode modes. Essential for sensor and wiring diagnosis.", brand: "VoltTools", price: 38500, qty: 15, cat: "diagnostic-accessories", attrs: { protocol: "CAN", connectivity: "Wired", updateable: false, displayType: "Color" }, kw: ["multimeter", "automotive"] },
  { slug: "tpms-tool", name: "TPMS Reset Tool", sub: "Tire pressure sensor relearn", desc: "TPMS activation tool that triggers tire pressure sensors for relearn after rotation or replacement.", brand: "DiagTech", price: 26500, qty: 12, cat: "tpms-tools", attrs: { protocol: "OBD-II", connectivity: "Wired", updateable: false, displayType: "Monochrome" }, kw: ["tpms", "tire sensor"] },
  { slug: "immobilizer-key-prog", name: "Key Programmer Basic", sub: "Clone/reprogram transponder keys", desc: "Transponder key programmer covering common Toyota/Honda/Nissan chip keys. Cut the blade locally, program in minutes.", brand: "DiagTech", price: 168000, qty: 4, cat: "ecu-tools", attrs: { protocol: "KWP2000", connectivity: "USB", updateable: true, displayType: "Color" }, kw: ["key programmer", "transponder"] },
  { slug: "smoke-leak-tester", name: "EVAP Smoke Leak Tester", sub: "Finds vacuum/EVAP leaks fast", desc: "Smoke machine that fills the intake/EVAP system with visible smoke, pinpoints leaks in minutes, not hours.", brand: "DiagTech", price: 96000, qty: 5, cat: "diagnostic-accessories", attrs: { protocol: "CAN", connectivity: "Wired", updateable: false, displayType: "Monochrome" }, kw: ["smoke tester", "evap leak"] },
  { slug: "oscilloscope-auto", name: "2-Channel Automotive Oscilloscope", sub: "Waveform-level sensor diagnosis", desc: "2-channel handheld scope with automotive presets, crank/cam signals, injectors, CAN bus waveform checks.", brand: "DiagTech", price: 210000, qty: 3, cat: "oscilloscopes", attrs: { protocol: "CAN", connectivity: "USB", updateable: true, displayType: "Color" }, kw: ["oscilloscope", "waveform"] },
  { slug: "obd-extension-cable", name: "OBD2 Extension Cable 1.5m", sub: "Reach the cabin comfortably", desc: "1.5m OBD2 extension cable so scanners sit on the seat, not dangling from the port.", brand: "WireWorks", price: 6500, qty: 30, cat: "diagnostic-cables", attrs: { protocol: "OBD-II", connectivity: "Wired", updateable: false, displayType: "None (mobile app)" }, kw: ["obd extension", "cable"] },
  { slug: "circuit-tester-led", name: "6-24V Circuit Tester Pen", sub: "Computer-safe LED test light", desc: "Computer-safe LED circuit tester for 6-24V systems, checks fuses, grounds and power feeds without damaging ECUs.", brand: "VoltTools", price: 5500, qty: 40, cat: "diagnostic-accessories", attrs: { protocol: "OBD-II", connectivity: "Wired", updateable: false, displayType: "Monochrome" }, kw: ["circuit tester", "test light"] },
  { slug: "injector-test-kit", name: "Injector Test & Clean Kit", sub: "DIY injector flow test", desc: "On-car injector test and cleaner kit with pressurised canister and adapter set, restores spray patterns.", brand: "DiagTech", price: 52000, qty: 7, cat: "diagnostic-accessories", attrs: { protocol: "OBD-II", connectivity: "Wired", updateable: false, displayType: "Monochrome" }, kw: ["injector tester", "cleaner"] },
]);

// ──────────────────────────── FASHION ──────────────────────────────────────
// roots: fabrics-textiles,sewing-machines,sewing-tools-accessories,threads,
//        buttons-fasteners,zippers,patterns,trims-laces,embroidery-supplies,
//        mannequins-display,tailoring-equipment,garments-uniforms
// enums: fabricType[Cotton/Linen/Silk/Polyester/Ankara/Lace/Wool/Denim],
//        size[XS/S/M/L/XL/XXL/Custom], color[Black/White/Red/Blue/Green/Gold/Multi],
//        machineType[Manual/Electric/Industrial/Overlock/Computerized],
//        application[Bespoke/Alterations/Bridal/Native/Corporate/Embroidery]
const FASHION = build("fashion", [
  { slug: "ankara-fabric-6yd", name: "Premium Ankara Print 6 Yards", sub: "100% cotton wax print", desc: "Six yards of premium 100% cotton wax-print Ankara. Colourfast dyes, tight weave, perfect for custom outfits.", brand: "LoomHouse", price: 14500, qty: 60, cat: "fabrics-textiles", attrs: { fabricType: "Ankara", size: "Custom", color: "Multi", machineType: "Manual", application: "Native" }, kw: ["ankara", "wax print", "fabric"] },
  { slug: "aso-oke-gele", name: "Handwoven Aso-Oke Gele", sub: "Ceremonial headwrap piece", desc: "Handwoven aso-oke gele with metallic threading, structured hold for ceremonies without excessive pinning.", brand: "LoomHouse", price: 22000, qty: 25, cat: "fabrics-textiles", attrs: { fabricType: "Cotton", size: "Custom", color: "Blue", machineType: "Manual", application: "Native" }, kw: ["aso oke", "gele", "headwrap"] },
  { slug: "sewing-machine-industrial", name: "Industrial Straight-Stitch Machine", sub: "Single-needle lockstitch + stand", desc: "Cast-iron industrial straight-stitch machine with table stand and servo motor. Daily-production reliability.", brand: "StitchMaster", price: 285000, qty: 5, cat: "sewing-machines", attrs: { fabricType: "Cotton", size: "Custom", color: "Black", machineType: "Industrial", application: "Bespoke" }, kw: ["industrial sewing machine", "lockstitch"] },
  { slug: "sewing-machine-interlock", name: "Interlock Sewing Machine", sub: "Coverstitch for hems", desc: "Interlock/coverstitch machine for professional hem finishes on knits, polos and sportswear.", brand: "StitchMaster", price: 340000, qty: 3, cat: "sewing-machines", attrs: { fabricType: "Polyester", size: "Custom", color: "White", machineType: "Overlock", application: "Bespoke" }, kw: ["interlock machine", "coverstitch"] },
  { slug: "overlock-machine", name: "Overlock (Weaving) Machine 4-Thread", sub: "Clean edge finishing", desc: "4-thread overlock machine with differential feed, strong, tidy seams and rolled hems at production speed.", brand: "StitchMaster", price: 195000, qty: 6, cat: "sewing-machines", attrs: { fabricType: "Cotton", size: "Custom", color: "White", machineType: "Overlock", application: "Bespoke" }, kw: ["overlock", "weaving machine"] },
  { slug: "lace-fabric-5yd", name: "French Lace Fabric 5 Yards", sub: "Beaded tulle lace", desc: "Five yards of beaded French tulle lace with sequin work, occasion-ready for aso-ebi and bridal looks.", brand: "LoomHouse", price: 48000, qty: 30, cat: "fabrics-textiles", attrs: { fabricType: "Lace", size: "Custom", color: "Multi", machineType: "Manual", application: "Bridal" }, kw: ["lace", "french lace", "aso ebi"] },
  { slug: "tailor-scissors-set", name: "Tailor Shears Set (10\" + 8\")", sub: "Forged steel cutting pair", desc: "Forged-steel 10-inch shears plus 8-inch trimming scissors. Clean cuts through denim, ankara and leather.", brand: "StitchMaster", price: 16500, qty: 35, cat: "sewing-tools-accessories", attrs: { fabricType: "Denim", size: "Custom", color: "Black", machineType: "Manual", application: "Bespoke" }, kw: ["tailor scissors", "shears"] },
  { slug: "measuring-tape-pack", name: "Body Measuring Tape (5 Pack)", sub: "60-inch flexible tapes", desc: "Five flexible 60-inch measuring tapes, keep one at every station for consistent body measurements.", brand: "StitchMaster", price: 2500, qty: 80, cat: "sewing-tools-accessories", attrs: { fabricType: "Polyester", size: "Custom", color: "White", machineType: "Manual", application: "Alterations" }, kw: ["measuring tape"] },
  { slug: "interfacing-roll", name: "Fusible Interfacing Roll", sub: "Medium-weight · 5 metres", desc: "5-metre roll of medium-weight fusible interfacing, gives collars, cuffs and facings crisp structure.", brand: "LoomHouse", price: 6500, qty: 45, cat: "trims-laces", attrs: { fabricType: "Cotton", size: "Custom", color: "White", machineType: "Electric", application: "Bespoke" }, kw: ["interfacing", "fusible"] },
  { slug: "ready-wear-agbada", name: "Embroidered Agbada (3-Piece)", sub: "Made-to-measure · size L", desc: "Three-piece embroidered agbada set in premium cotton blend. Made-to-measure with 5-day delivery.", brand: "RoyalThread", price: 125000, qty: 8, cat: "garments-uniforms", attrs: { fabricType: "Cotton", size: "L", color: "White", machineType: "Computerized", application: "Embroidery" }, kw: ["agbada", "embroidered", "occasion"] },
  { slug: "sewing-threads-24", name: "Polyester Thread Box (24 Spools)", sub: "Assorted colours 1000m each", desc: "24 spools of 1000m polyester thread in core colours. Colourfast and low-lint on high-speed machines.", brand: "StitchMaster", price: 8800, qty: 50, cat: "threads", attrs: { fabricType: "Polyester", size: "Custom", color: "Multi", machineType: "Industrial", application: "Bespoke" }, kw: ["thread box", "polyester"] },
  { slug: "steam-iron-heavy", name: "Heavy Steam Iron Pro", sub: "Dry + steam pressing station", desc: "Professional gravity-feed steam iron with non-stick soleplate, crisp pressing that makes cheap work look expensive.", brand: "StitchMaster", price: 42000, qty: 14, cat: "tailoring-equipment", attrs: { fabricType: "Cotton", size: "Custom", color: "White", machineType: "Electric", application: "Bespoke" }, kw: ["steam iron", "pressing"] },
]);

// ──────────────────────────── PLUMBER ──────────────────────────────────────
// roots: pipes,fittings,valves,pumps,taps,toilets,sinks,water-heaters,connectors,
//        seals,adhesives,drainage,water-storage,pressure-equipment,plumbing-tools
// enums: connection[Threaded/Push-fit/Solvent weld/Compression/Flanged],
//        application[Potable water/Drainage/Gas/Heating]
const PLUMBER = build("plumber", [
  { slug: "pvc-pipe-4inch", name: "PVC Pipe 4\" × 6m", sub: "Schedule-40 drainage pipe", desc: "4-inch Schedule-40 PVC pipe, 6m length, for soil and wastewater drainage. Solvent-weld joints.", brand: "FlowLine", price: 14500, qty: 60, cat: "pipes", attrs: { diameter: 4, connection: "Solvent weld", pressureRating: 6, application: "Drainage" }, kw: ["pvc pipe", "drainage"] },
  { slug: "ppr-pipe-1inch", name: "PPR Pipe 1\" × 4m PN20", sub: "Hot/cold water supply pipe", desc: "1-inch PN20 polypropylene random pipe for hot and cold pressurised water. Heat-fusion joints never leak.", brand: "FlowLine", price: 9800, qty: 70, cat: "pipes", attrs: { diameter: 1, connection: "Compression", pressureRating: 20, application: "Potable water" }, kw: ["ppr pipe", "water supply"] },
  { slug: "pipe-wrench-14", name: "Pipe Wrench 14\" Cast Iron", sub: "Grip that won't slip", desc: "14-inch cast-iron pipe wrench with hardened jaw teeth and quick-adjust nut. The plumber's handshake.", brand: "TorqPro", price: 12500, qty: 35, cat: "plumbing-tools", attrs: { diameter: 2, connection: "Threaded", pressureRating: 0, application: "Potable water" }, kw: ["pipe wrench"] },
  { slug: "water-pump-1hp", name: "Surface Water Pump 1HP", sub: "Boosts pressure whole-building", desc: "1HP surface pump with brass impeller, restores strong pressure to upstairs bathrooms and kitchens.", brand: "FlowMax", price: 96000, qty: 12, cat: "pumps", attrs: { diameter: 1, connection: "Threaded", pressureRating: 16, application: "Potable water" }, kw: ["water pump", "pressure"] },
  { slug: "water-heater-30l", name: "Water Heater 30L Electric", sub: "Storage heater with safety valve", desc: "30-litre electric storage water heater with adjustable thermostat, safety relief valve and 2-year element warranty.", brand: "HeatWell", price: 148000, qty: 8, cat: "water-heaters", attrs: { diameter: 16, connection: "Threaded", pressureRating: 10, application: "Heating" }, kw: ["water heater", "30l"] },
  { slug: "basin-mixer-tap", name: "Single-Lever Basin Mixer", sub: "Chrome deck-mounted tap", desc: "Chrome single-lever basin mixer with ceramic cartridge, smooth handle feel, drip-free for years.", brand: "FlowLine", price: 24500, qty: 30, cat: "taps", attrs: { diameter: 0.5, connection: "Threaded", pressureRating: 10, application: "Potable water" }, kw: ["basin tap", "mixer"] },
  { slug: "toilet-seat-softclose", name: "Soft-Close Toilet Seat", sub: "Universal elongated fit", desc: "Elongated soft-close toilet seat with quick-release hinges for easy cleaning. Universal fittings included.", brand: "FlowLine", price: 28500, qty: 22, cat: "toilets", attrs: { diameter: 0, connection: "Compression", pressureRating: 0, application: "Drainage" }, kw: ["toilet seat", "soft close"] },
  { slug: "ptfe-thread-seal", name: "PTFE Thread Seal Tape (10 Pack)", sub: "Leak-proof threaded joints", desc: "Ten rolls of high-density PTFE tape, the cheapest insurance against threaded-joint leaks.", brand: "FlowLine", price: 3200, qty: 90, cat: "seals", attrs: { diameter: 0.5, connection: "Threaded", pressureRating: 20, application: "Potable water" }, kw: ["ptfe tape", "teflon"] },
  { slug: "drain-machine-7m", name: "Drain Auger Machine 7m", sub: "Clears blocked pipes fast", desc: "Hand-crank drain auger with 7m flexible shaft and corkscrew head, pulls hair and grease clogs out in minutes.", brand: "TorqPro", price: 38500, qty: 10, cat: "drainage", attrs: { diameter: 2, connection: "Threaded", pressureRating: 0, application: "Drainage" }, kw: ["drain auger", "plunger snake"] },
  { slug: "submersible-pump-05", name: "Submersible Pump 0.5HP", sub: "Clean-water well/borehole pump", desc: "0.5HP submersible clean-water pump for wells and tanks. Sealed motor, 32m max head, thermal-protected.", brand: "FlowMax", price: 78500, qty: 14, cat: "pumps", attrs: { diameter: 1, connection: "Threaded", pressureRating: 10, application: "Potable water" }, kw: ["submersible pump", "borehole"] },
  { slug: "elbow-90-1inch", name: "PPR Elbow 90° 1\" (10 Pack)", sub: "Heat-fusion fittings", desc: "Ten 90-degree PN20 PPR elbows for 1-inch supply lines. Fuse-on joints that outlast the pipe itself.", brand: "FlowLine", price: 6500, qty: 80, cat: "fittings", attrs: { diameter: 1, connection: "Compression", pressureRating: 20, application: "Potable water" }, kw: ["ppr elbow", "fitting"] },
  { slug: "manometer-gauge", name: "Pressure Test Gauge 0-16 Bar", sub: "Verify lines before closing walls", desc: "0-16 bar pressure test gauge with adapters, prove your pipework holds pressure before tiling over it.", brand: "TorqPro", price: 11500, qty: 16, cat: "pressure-equipment", attrs: { diameter: 0.5, connection: "Threaded", pressureRating: 16, application: "Potable water" }, kw: ["pressure gauge", "test"] },
]);

// ─────────────────────────── CARPENTER ─────────────────────────────────────
// roots: timber,boards,plywood,mdf,fasteners,nails,screws,hinges,handles,saws,
//        drills,planers,sanders,routers,measuring-tools,adhesives,workshop-equipment
// enums: application[Furniture/Structural/Doors/Cabinetry/Roofing]
const CARPENTER = build("carpenter", [
  { slug: "circular-saw-7", name: "Circular Saw 7¼\" 1400W", sub: "Bevel cuts + blade included", desc: "1400W circular saw with 7¼-inch blade, bevel to 45°, and safety brake. Straight, clean cuts in hardwood and sheet goods.", brand: "TimberTech", price: 68000, qty: 14, cat: "saws", attrs: { dimensions: "7-inch", thickness: 0, application: "Furniture", toolPower: 1400, bladeSize: 184 }, kw: ["circular saw"] },
  { slug: "jigsaw-650w", name: "Jigsaw 650W Variable Speed", sub: "Curves + bevel + blades", desc: "650W orbital jigsaw with variable speed and pendulum action, curves in ply, laminate and hardwood.", brand: "TimberTech", price: 42000, qty: 16, cat: "saws", attrs: { dimensions: "universal", thickness: 0, application: "Furniture", toolPower: 650, bladeSize: 0 }, kw: ["jigsaw"] },
  { slug: "plywood-18mm", name: "Plywood Sheet 18mm 8×4", sub: "Marine-grade B/BB face", desc: "18mm marine-grade plywood sheet, 8×4 feet, B/BB face veneer. Holds screws without splintering, furniture and formwork.", brand: "TimberYard", price: 52000, qty: 30, cat: "plywood", attrs: { dimensions: "8x4-ft", thickness: 18, application: "Furniture" }, kw: ["plywood", "18mm"] },
  { slug: "mdf-12mm", name: "MDF Sheet 12mm 8×4", sub: "Smooth paint-grade board", desc: "12mm medium-density fibreboard, 8×4. Dead-flat and ultra-smooth, the painter's favourite for cabinets and shelving.", brand: "TimberYard", price: 34000, qty: 35, cat: "mdf", attrs: { dimensions: "8x4-ft", thickness: 12, application: "Cabinetry" }, kw: ["mdf", "board"] },
  { slug: "clamps-set-4", name: "Bar Clamp Set (4-Pack)", sub: "12\" and 24\" F-clamps", desc: "Four F-clamps (two 12\", two 24\") with non-marring pads. The glue-up workhorses every bench needs.", brand: "TimberTech", price: 26500, qty: 20, cat: "workshop-equipment", attrs: { dimensions: "12-24-inch", thickness: 0, application: "Furniture" }, kw: ["bar clamp", "f clamp"] },
  { slug: "chisel-set-4pc", name: "Wood Chisel Set 4-Piece", sub: "6/12/19/25mm · honed", desc: "Four honed chrome-vanadium chisels (6/12/19/25mm) with strike caps. Clean paring and hinge recesses out of the box.", brand: "TimberTech", price: 18500, qty: 24, cat: "workshop-equipment", attrs: { dimensions: "6-25mm", thickness: 0, application: "Doors" }, kw: ["chisel set"] },
  { slug: "router-1-2", name: "Plunge Router ½\" 1600W", sub: "Edges, joints, dados", desc: "1600W plunge router taking ½-inch bits, with edge guide and collet set, raised panels, dados, decorative edges.", brand: "TimberTech", price: 74000, qty: 9, cat: "routers", attrs: { dimensions: "half-inch", thickness: 0, application: "Cabinetry", toolPower: 1600, bladeSize: 12 }, kw: ["plunge router"] },
  { slug: "wood-glue-5l", name: "PVA Wood Glue 5L", sub: "Stronger than the wood itself", desc: "5-litre PVA woodworking adhesive, clamp joints that end up stronger than the surrounding timber.", brand: "TimberYard", price: 12500, qty: 40, cat: "adhesives", attrs: { dimensions: "5-litre", thickness: 0, application: "Furniture" }, kw: ["wood glue", "pva"] },
  { slug: "hardwood-teak-plank", name: "Teak Hardwood Plank 1×12", sub: "Kiln-dried · 6-foot", desc: "Kiln-dried teak plank, 1×12 inches by 6 feet. Naturally oil-rich, outdoor furniture that outlives you.", brand: "TimberYard", price: 88000, qty: 15, cat: "timber", attrs: { dimensions: "1x12x6-ft", thickness: 25, application: "Furniture" }, kw: ["teak", "hardwood"] },
  { slug: "sander-orbital", name: "Random Orbital Sander 350W", sub: "Swirl-free finishing", desc: "350W random-orbital sander with dust canister and variable speed, swirl-free surfaces ready for varnish.", brand: "TimberTech", price: 33500, qty: 18, cat: "sanders", attrs: { dimensions: "5-inch", thickness: 0, application: "Furniture", toolPower: 350, bladeSize: 0 }, kw: ["orbital sander"] },
  { slug: "spirit-level-48", name: "Spirit Level 48\" Magnetic", sub: "Dead-true aluminium level", desc: "48-inch boxed aluminium level with magnetic strip and three vials. Everything you build stays honest.", brand: "TimberTech", price: 15500, qty: 22, cat: "measuring-tools", attrs: { dimensions: "48-inch", thickness: 0, application: "Structural" }, kw: ["spirit level"] },
  { slug: "saw-horse-pair", name: "Saw Horse Brackets (Pair)", sub: "Build work tops in minutes", desc: "Pair of steel saw-horse brackets, add any two planks for an instant, sturdy work surface anywhere.", brand: "TimberTech", price: 16800, qty: 16, cat: "workshop-equipment", attrs: { dimensions: "adjustable", thickness: 0, application: "Structural" }, kw: ["saw horse", "workbench"] },
]);

// ──────────────────────────── PAINTER ──────────────────────────────────────
// roots: interior-paint,exterior-paint,industrial-coatings,automotive-paint,primer,
//        thinner,brushes,rollers,spray-guns,sandpaper,masking,protective-equipment,painting-equipment
// enums: paintType[Emulsion/Gloss/Satin/Matt/Textured/Epoxy/Automotive/Primer/Industrial],
//        finish[Matt/Satin/Gloss/Silk]
const PAINTER = build("painter", [
  { slug: "emulsion-20l-white", name: "Interior Emulsion 20L White", sub: "Washable matt finish", desc: "20-litre washable matt emulsion for interior walls. One-coat coverage over previously painted surfaces.", brand: "ColourField", price: 42000, qty: 35, cat: "interior-paint", attrs: { paintType: "Emulsion", coverage: 120, volume: 20, finish: "Matt", dryingTime: 2 }, kw: ["emulsion", "interior paint"] },
  { slug: "gloss-4l-white", name: "Oil Gloss 4L White", sub: "Hard-wearing trim enamel", desc: "4-litre oil-based gloss for doors, frames and trims. Rock-hard, wipeable, high-shine finish.", brand: "ColourField", price: 18500, qty: 40, cat: "interior-paint", attrs: { paintType: "Gloss", coverage: 60, volume: 4, finish: "Gloss", dryingTime: 8 }, kw: ["gloss", "trim paint"] },
  { slug: "satinwood-4l", name: "Satinwood 4L Eggshell", sub: "Modern low-sheen trim finish", desc: "4-litre satinwood eggshell, the modern trim finish: low sheen, washable, less glare than gloss.", brand: "ColourField", price: 21000, qty: 32, cat: "interior-paint", attrs: { paintType: "Satin", coverage: 55, volume: 4, finish: "Silk", dryingTime: 6 }, kw: ["satinwood", "eggshell"] },
  { slug: "exterior-weathercoat-20l", name: "Exterior Weathercoat 20L", sub: "Sun/rain resistant facade paint", desc: "20-litre weather-shield exterior emulsion with UV blockers and anti-fungus, facades stay bright through rainy season.", brand: "ColourField", price: 58000, qty: 25, cat: "exterior-paint", attrs: { paintType: "Emulsion", coverage: 100, volume: 20, finish: "Satin", dryingTime: 3 }, kw: ["exterior paint", "weathercoat"] },
  { slug: "primer-4l", name: "Wall Primer Sealer 4L", sub: "Base coat for new plaster", desc: "4-litre penetrating primer-sealer that evens absorption on new plaster, topcoats go on even and stay put.", brand: "ColourField", price: 12800, qty: 45, cat: "primer", attrs: { paintType: "Primer", coverage: 70, volume: 4, finish: "Matt", dryingTime: 4 }, kw: ["primer", "sealer"] },
  { slug: "roller-sleeve-9", name: "9\" Roller Sleeves (6 Pack)", sub: "Medium-pile lint-free", desc: "Six 9-inch medium-pile lint-free roller sleeves, the everyday sleeve for emulsion on walls and ceilings.", brand: "RollRight", price: 4800, qty: 60, cat: "rollers", attrs: { paintType: "Emulsion", coverage: 0, volume: 0, finish: "Matt", dryingTime: 0 }, kw: ["roller sleeve"] },
  { slug: "roller-frame-9", name: "9\" Roller Frame Heavy-Duty", sub: "Comfort-grip steel frame", desc: "Heavy-duty 9-inch roller frame with threaded end and comfort grip, survives a full year of daily painting.", brand: "RollRight", price: 5200, qty: 50, cat: "rollers", attrs: { paintType: "Emulsion", coverage: 0, volume: 0, finish: "Matt", dryingTime: 0 }, kw: ["roller frame"] },
  { slug: "brush-set-5", name: "Paint Brush Set (5-Piece)", sub: "1\"-4\" bristle brushes", desc: "Five bristle brushes (1\", 1.5\", 2\", 3\", 4\") with flagged tips, clean cutting-in on edges without bristle loss.", brand: "RollRight", price: 9500, qty: 48, cat: "brushes", attrs: { paintType: "Gloss", coverage: 0, volume: 0, finish: "Gloss", dryingTime: 0 }, kw: ["paint brush set"] },
  { slug: "masking-tape-2", name: "Masking Tape 2\" (48mm)", sub: "Clean-release · no paint pull", desc: "48mm masking tape with clean-release adhesive, sharp paint lines, no torn plaster on removal.", brand: "RollRight", price: 2800, qty: 100, cat: "masking", attrs: { paintType: "Emulsion", coverage: 0, volume: 0, finish: "Matt", dryingTime: 0 }, kw: ["masking tape"] },
  { slug: "dust-sheets-2", name: "Canvas Dust Sheets (2-Pack)", sub: "12×9 ft washable covers", desc: "Two 12×9-foot canvas dust sheets, washable, reusable, and far safer than plastic around ladders.", brand: "RollRight", price: 11500, qty: 30, cat: "protective-equipment", attrs: { paintType: "Emulsion", coverage: 0, volume: 0, finish: "Matt", dryingTime: 0 }, kw: ["dust sheet", "drop cloth"] },
  { slug: "filler-wall-1kg", name: "Wall Filler 1kg", sub: "Crack and hole repair", desc: "1kg ready-mixed wall filler, smooths cracks and nail holes, sands to a feather edge in minutes.", brand: "FillPro", price: 4200, qty: 70, cat: "primer", attrs: { paintType: "Primer", coverage: 0, volume: 1, finish: "Matt", dryingTime: 2 }, kw: ["wall filler", "spackle"] },
  { slug: "extension-pole-2m", name: "Extension Pole 2m Threaded", sub: "Ceilings without a ladder", desc: "2-metre aluminium extension pole with universal thread, ceilings and high walls from the floor.", brand: "RollRight", price: 12500, qty: 26, cat: "rollers", attrs: { paintType: "Emulsion", coverage: 0, volume: 0, finish: "Matt", dryingTime: 0 }, kw: ["extension pole"] },
]);

// ───────────────────────────── SOLAR ───────────────────────────────────────
// roots: solar-panels,inverters,batteries,charge-controllers,mppt,mounting,
//        solar-cables,mc4,combiner-boxes,dc-protection,ac-protection,monitoring,
//        solar-pumps,solar-lighting,installation-tools,accessories
// required: wattage · enums: panelType[Monocrystalline/Polycrystalline/Thin-film/PERC/Bifacial],
//           inverterType[Hybrid/Off-grid/On-grid/String/Micro]
const SOLAR = build("solar", [
  { slug: "panel-450w-mono", name: "450W Mono Solar Panel", sub: "Tier-1 · 25-yr performance warranty", desc: "450W monocrystalline panel with half-cut cells, strong output even in haze and high heat. 25-year performance warranty.", brand: "SunCore", price: 218000, qty: 20, cat: "solar-panels", attrs: { wattage: 450, voltage: 24, panelType: "Monocrystalline", inverterType: "Hybrid", capacity: 0, efficiency: 20.5 }, kw: ["solar panel", "450w", "mono"] },
  { slug: "panel-550w-mono", name: "550W Mono Solar Panel", sub: "Half-cut · high efficiency", desc: "550W monocrystalline half-cut panel, the workhorse for Nigerian rooftops. Bifacial glass for extra yield.", brand: "SunCore", price: 262000, qty: 18, cat: "solar-panels", attrs: { wattage: 550, voltage: 24, panelType: "PERC", inverterType: "On-grid", capacity: 0, efficiency: 21.3 }, kw: ["solar panel", "550w"] },
  { slug: "inverter-5kva", name: "Hybrid Inverter 5.5kVA 48V", sub: "Solar + grid + battery auto-switch", desc: "5.5kVA 48V hybrid inverter with 80A MPPT, runs your home on solar, charges batteries, auto-falls back to grid.", brand: "VoltMax", price: 785000, qty: 6, cat: "inverters", attrs: { wattage: 5500, voltage: 48, panelType: "Monocrystalline", inverterType: "Hybrid", capacity: 80, efficiency: 97 }, kw: ["inverter", "5.5kva", "hybrid"] },
  { slug: "inverter-3-5kva", name: "Inverter 3.5kVA 24V", sub: "Pure sine wave · flats and shops", desc: "3.5kVA 24V pure sine wave inverter, fridges, fans, TVs and lights run clean and quiet.", brand: "VoltMax", price: 465000, qty: 8, cat: "inverters", attrs: { wattage: 3500, voltage: 24, panelType: "Monocrystalline", inverterType: "Off-grid", capacity: 60, efficiency: 95 }, kw: ["inverter", "3.5kva"] },
  { slug: "lifepo4-100ah", name: "LiFePO4 Battery 100Ah 48V", sub: "5,000+ cycle lithium bank", desc: "100Ah 48V lithium iron phosphate battery with BMS, 5,000+ cycles, 10× the life of tubular, zero maintenance.", brand: "VoltMax", price: 1250000, qty: 5, cat: "batteries", attrs: { wattage: 100, voltage: 48, panelType: "Monocrystalline", inverterType: "Hybrid", capacity: 100, efficiency: 98 }, kw: ["lifepo4", "lithium battery"] },
  { slug: "tubular-600ah-2v", name: "2V 600Ah Tubular Cell", sub: "OpzV battery for big banks", desc: "2V 600Ah OPzV tubular gel cell for serious bank builds, 20-year float life, deep-cycle proven.", brand: "SunCore", price: 485000, qty: 8, cat: "batteries", attrs: { wattage: 10, voltage: 2, panelType: "Monocrystalline", inverterType: "Off-grid", capacity: 600, efficiency: 90 }, kw: ["opzv", "tubular cell"] },
  { slug: "mppt-60a", name: "MPPT Charge Controller 60A", sub: "Maximises panel harvest", desc: "60A MPPT charge controller with LCD, extracts up to 30% more from your panels than PWM controllers.", brand: "VoltMax", price: 148000, qty: 10, cat: "mppt", attrs: { wattage: 3600, voltage: 48, panelType: "Monocrystalline", inverterType: "Off-grid", capacity: 60, efficiency: 98 }, kw: ["mppt", "charge controller"] },
  { slug: "mounting-rail-kit", name: "Roof Mounting Rail Kit", sub: "Aluminium · 4-panel set", desc: "Anodised aluminium mounting rail kit for 4 panels, cyclone-rated clamps, mid/end caps, roof hooks included.", brand: "SunCore", price: 95000, qty: 12, cat: "mounting", attrs: { wattage: 2000, voltage: 0, panelType: "Monocrystalline", inverterType: "On-grid", capacity: 0, efficiency: 0 }, kw: ["mounting rails", "solar brackets"] },
  { slug: "pv-cable-6mm", name: "Solar PV Cable 6mm² (50m)", sub: "UV-rated DC cable pair", desc: "50 metres of 6mm² double-insulated UV-rated DC cable (red/black), sized to keep voltage drop negligible.", brand: "WireWorks", price: 78000, qty: 14, cat: "solar-cables", attrs: { wattage: 0, voltage: 0, panelType: "Monocrystalline", inverterType: "String", capacity: 0, efficiency: 0 }, kw: ["pv cable", "solar cable"] },
  { slug: "mc4-connectors", name: "MC4 Connector Pair", sub: "IP68 weatherproof DC connectors", desc: "MC4 male/female connector pair with IP68 sealing, the standard snap-lock joint for solar strings.", brand: "WireWorks", price: 4500, qty: 60, cat: "mc4", attrs: { wattage: 0, voltage: 0, panelType: "Monocrystalline", inverterType: "String", capacity: 0, efficiency: 0 }, kw: ["mc4 connector"] },
  { slug: "changeover-63a", name: "Solar Changeover 63A 4-Pole", sub: "Manual solar/grid selector", desc: "63A 4-pole manual changeover switch, flip between solar/inverter and grid supply safely.", brand: "VoltMax", price: 34500, qty: 18, cat: "dc-protection", attrs: { wattage: 0, voltage: 230, panelType: "Monocrystalline", inverterType: "Hybrid", capacity: 63, efficiency: 0 }, kw: ["changeover", "transfer switch"] },
  { slug: "solar-fridge-dc", name: "DC Solar Fridge 100L", sub: "Runs directly off panels + battery", desc: "100-litre 12/24V DC compressor fridge designed for solar, sips power, runs all night on one battery.", brand: "SunCore", price: 385000, qty: 4, cat: "accessories", attrs: { wattage: 60, voltage: 24, panelType: "Monocrystalline", inverterType: "Off-grid", capacity: 100, efficiency: 92 }, kw: ["solar fridge", "dc fridge"] },
]);

// ─────────────────────────── GENERATOR ─────────────────────────────────────
// roots: portable-generators,standby-generators,industrial-generators,diesel,
//        petrol,engines,alternators,avr,control-panels,starters,fuel-systems,
//        cooling,exhaust,filters,batteries,sensors,transfer-switches,
//        generator-tools,maintenance-parts
// required: kva · enums: fuelType[Petrol/Diesel/Gas/Solar hybrid],
//           phase[Single/Three], startType[Recoil/Electric/Remote/Auto]
const GENERATOR = build("generator", [
  { slug: "gen-2-5kva-petrol", name: "2.5kVA Petrol Generator", sub: "Manual start · home essentials", desc: "2.5kVA manual-start petrol generator, lights, fans, TV and freezer through an outage without breaking the bank.", brand: "GenPower", price: 265000, qty: 12, cat: "petrol", attrs: { kva: 2.5, fuelType: "Petrol", phase: "Single", runTime: 10, tankCapacity: 15, startType: "Recoil" }, kw: ["generator", "2.5kva", "petrol"] },
  { slug: "gen-3-5kva-key", name: "3.5kVA Key-Start Petrol Generator", sub: "Key start · copper coil", desc: "3.5kVA key-start petrol generator with 100% copper alternator, fridges and pumps without voltage dips.", brand: "GenPower", price: 385000, qty: 9, cat: "portable-generators", attrs: { kva: 3.5, fuelType: "Petrol", phase: "Single", runTime: 9, tankCapacity: 20, startType: "Electric" }, kw: ["generator", "3.5kva", "key start"] },
  { slug: "gen-6-5kva-diesel", name: "6.5kVA Diesel Generator", sub: "Economy diesel · long runtime", desc: "6.5kVA diesel generator, diesel's lower cost per hour makes this the small-business workhorse.", brand: "GenPower", price: 685000, qty: 6, cat: "diesel", attrs: { kva: 6.5, fuelType: "Diesel", phase: "Single", runTime: 12, tankCapacity: 25, startType: "Electric" }, kw: ["diesel generator", "6.5kva"] },
  { slug: "gen-10kva-diesel", name: "10kVA Diesel Generator ATS-Ready", sub: "Auto-start · shops and clinics", desc: "10kVA diesel generator with ATS terminals, pairs with a changeover to restore power automatically.", brand: "GenPower", price: 1250000, qty: 4, cat: "standby-generators", attrs: { kva: 10, fuelType: "Diesel", phase: "Single", runTime: 10, tankCapacity: 40, startType: "Auto" }, kw: ["diesel generator", "10kva", "ats"] },
  { slug: "gen-15kva-3phase", name: "15kVA 3-Phase Diesel Generator", sub: "For equipment needing 3-phase", desc: "15kVA three-phase diesel generator for boreholes, industrial freezers and workshop machinery.", brand: "GenPower", price: 2150000, qty: 3, cat: "industrial-generators", attrs: { kva: 15, fuelType: "Diesel", phase: "Three", runTime: 9, tankCapacity: 55, startType: "Electric" }, kw: ["3 phase generator", "15kva"] },
  { slug: "gen-inverter-2kva", name: "2kVA Inverter Generator", sub: "Silent · safe for electronics", desc: "2kVA inverter generator at whisper level (58dB), clean sine power that laptops and TVs love.", brand: "GenPower", price: 585000, qty: 5, cat: "portable-generators", attrs: { kva: 2, fuelType: "Petrol", phase: "Single", runTime: 8, tankCapacity: 8, startType: "Recoil" }, kw: ["inverter generator", "silent"] },
  { slug: "gen-service-kit", name: "Generator Service Kit", sub: "Oil + filter + air filter + plug", desc: "Complete service kit (engine oil, oil filter, air filter, spark plug), the 250-hour service, done right.", brand: "GenPower", price: 22500, qty: 40, cat: "maintenance-parts", attrs: { kva: 5, fuelType: "Petrol", phase: "Single", runTime: 0, tankCapacity: 0, startType: "Recoil" }, kw: ["service kit", "maintenance"] },
  { slug: "avr-automatic", name: "Automatic Voltage Regulator (AVR)", sub: "Stops voltage killing appliances", desc: "Replacement AVR that steadies generator output, protects TVs and fridges from the voltage spikes that kill them.", brand: "GenPower", price: 28500, qty: 18, cat: "avr", attrs: { kva: 5, fuelType: "Petrol", phase: "Single", runTime: 0, tankCapacity: 0, startType: "Electric" }, kw: ["avr", "voltage regulator"] },
  { slug: "gen-wheel-kit", name: "Wheel & Handle Kit", sub: "Roll your generator around", desc: "Never-lift-again wheel and folding-handle kit, move even the 10kVA sets with one hand.", brand: "GenPower", price: 18500, qty: 22, cat: "maintenance-parts", attrs: { kva: 5, fuelType: "Diesel", phase: "Single", runTime: 0, tankCapacity: 0, startType: "Recoil" }, kw: ["wheel kit", "handles"] },
  { slug: "fuel-tank-extended", name: "Extended Fuel Tank 30L", sub: "Double your runtime", desc: "30-litre extended-range fuel tank with all fittings, overnight events and long outages without 2am refuels.", brand: "GenPower", price: 42500, qty: 10, cat: "fuel-systems", attrs: { kva: 5, fuelType: "Petrol", phase: "Single", runTime: 20, tankCapacity: 30, startType: "Recoil" }, kw: ["extended tank", "fuel"] },
  { slug: "gen-battery-12v", name: "Electric-Start Battery 12V 18Ah", sub: "For key/electric-start sets", desc: "12V 18Ah sealed battery sized for electric-start generators, reliable cranking in every season.", brand: "PowerCell", price: 46500, qty: 16, cat: "batteries", attrs: { kva: 5, fuelType: "Diesel", phase: "Single", runTime: 0, tankCapacity: 0, startType: "Electric" }, kw: ["generator battery", "12v"] },
  { slug: "gen-exhaust-ext", name: "Exhaust Extension Pipe", sub: "Vent fumes away from windows", desc: "Flexible exhaust extension that routes fumes away from windows and neighbours, safer nights, happier street.", brand: "GenPower", price: 15500, qty: 20, cat: "exhaust", attrs: { kva: 5, fuelType: "Diesel", phase: "Single", runTime: 0, tankCapacity: 0, startType: "Recoil" }, kw: ["exhaust extension", "fume pipe"] },
]);

export const TRADE_SEED_PRODUCTS: DemoProduct[] = [
  ...TOWING,
  ...BATTERY,
  ...AC,
  ...BODY,
  ...ELECTRICAL,
  ...DIAGNOSTICS,
  ...FASHION,
  ...PLUMBER,
  ...CARPENTER,
  ...PAINTER,
  ...SOLAR,
  ...GENERATOR,
];
