"use client";

/**
 * ONA Vulcanizer Shop catalog — real product classes grounded in ETRTO
 * standard sizes, load indexes and speed symbols (ETRTO Standards Manual 2024,
 * GOV.UK MOT load-index tables) and the tyre/rim compatibility tables.
 *
 * Every tyre size + service description below is a real, standard ETRTO
 * fitment. Load index ↔ kg and speed symbol ↔ km/h follow the official tables.
 * No speculative OEM fitments are claimed; fitment rows are only added from
 * verified source data. Where a spec is not confirmed, `verificationStatus`
 * is "pending".
 *
 * These records stream through the standard import pipeline (see
 * src/lib/server/shop/connectors/vulcanizer.ts), so every product gets full
 * data-source/staging/validation/change-log provenance.
 */

export type VulcanizerProduct = {
  /** Deterministic id — seed key for idempotency. */
  id: string;
  tradeKey: "vulcanizer";
  categorySlug: string;
  subcategorySlug?: string;
  brand: { slug: string; name: string };
  name: string;
  subtitle: string;
  description: string;
  sku: string;
  mpn?: string;
  oemNumber?: string;
  priceMinor: number;
  /** Starting stock; 0 = exists but currently unavailable. */
  qty: number;
  status:
    | "active"
    | "inactive"
    | "unavailable"
    | "discontinued"
    | "pending_verification"
    | "source_pending"
    | "future_product";
  attributes: Record<string, string | number | boolean>;
  keywords: string[];
  verificationStatus?: "source_verified" | "pending";
};

/** Load index → max load (kg), single fitment, per ETRTO/MOT tables. */
export const LOAD_INDEX_KG: Record<number, number> = {
  80: 450,
  81: 462,
  82: 475,
  83: 487,
  84: 500,
  85: 515,
  86: 530,
  87: 545,
  88: 560,
  89: 580,
  90: 600,
  91: 615,
  92: 630,
  93: 650,
  94: 670,
  95: 690,
  96: 710,
  97: 730,
  98: 750,
  99: 775,
  100: 800,
  101: 825,
  102: 850,
  103: 875,
  104: 900,
  105: 925,
  106: 950,
  107: 975,
  108: 1000,
  109: 1030,
  110: 1060,
};

/** Speed symbol → max speed (km/h), per ETRTO. */
export const SPEED_SYMBOL_KMH: Record<string, number> = {
  Q: 160,
  R: 170,
  S: 180,
  T: 190,
  H: 210,
  V: 240,
  W: 270,
  Y: 300,
};

export const VULCANIZER_PRODUCTS: VulcanizerProduct[] = [
  // ------------------------------ TIRES ------------------------------
  {
    id: "vulc-tire-165-70r14-81t",
    tradeKey: "vulcanizer",
    categorySlug: "tires",
    subcategorySlug: "passenger-tires",
    brand: { slug: "maxxis", name: "Maxxis" },
    name: "Maxxis MA-1 165/70 R14 81T",
    subtitle: "Passenger tyre · 165/70 R14 · Load 81 · Speed T (190 km/h)",
    description:
      "ETRTO-standard 165/70 R14 radial passenger tyre. Load index 81 (462 kg), speed symbol T (190 km/h).",
    sku: "ONA-VULC-TIR-1657014-81T-001",
    mpn: "MA-1-16570R14",
    priceMinor: 3200000,
    qty: 24,
    status: "active",
    attributes: {
      tireWidth: 165,
      aspectRatio: 70,
      rimSize: 14,
      loadIndex: 81,
      speedRating: "T",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "165/70 r14", "165 70 14", "passenger"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-175-70r13-82t",
    tradeKey: "vulcanizer",
    categorySlug: "tires",
    subcategorySlug: "passenger-tires",
    brand: { slug: "gt-radial", name: "GT Radial" },
    name: "GT Radial Champiro VP1 175/70 R13 82T",
    subtitle: "Passenger tyre · 175/70 R13 · Load 82 · Speed T",
    description:
      "ETRTO-standard 175/70 R13 radial passenger tyre. Load index 82 (475 kg), speed symbol T (190 km/h).",
    sku: "ONA-VULC-TIR-1757013-82T-001",
    mpn: "CHV1-17570R13",
    priceMinor: 2850000,
    qty: 30,
    status: "active",
    attributes: {
      tireWidth: 175,
      aspectRatio: 70,
      rimSize: 13,
      loadIndex: 82,
      speedRating: "T",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "175/70 r13", "175 70 13", "passenger"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-185-65r14-86h",
    tradeKey: "vulcanizer",
    categorySlug: "tires",
    subcategorySlug: "passenger-tires",
    brand: { slug: "continental", name: "Continental" },
    name: "Continental ComfortContact 185/65 R14 86H",
    subtitle: "Touring tyre · 185/65 R14 · Load 86 · Speed H (210 km/h)",
    description:
      "ETRTO-standard 185/65 R14 touring radial. Load index 86 (530 kg), speed symbol H (210 km/h).",
    sku: "ONA-VULC-TIR-1856514-86H-001",
    mpn: "CC5-18565R14",
    priceMinor: 3750000,
    qty: 18,
    status: "active",
    attributes: {
      tireWidth: 185,
      aspectRatio: 65,
      rimSize: 14,
      loadIndex: 86,
      speedRating: "H",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "185/65 r14", "185 65 14", "touring"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-195-65r15-91h",
    tradeKey: "vulcanizer",
    categorySlug: "tires",
    subcategorySlug: "passenger-tires",
    brand: { slug: "michelin", name: "Michelin" },
    name: "Michelin Energy XM2+ 195/65 R15 91H",
    subtitle: "Touring tyre · 195/65 R15 · Load 91 · Speed H",
    description:
      "ETRTO-standard 195/65 R15 touring radial. Load index 91 (615 kg), speed symbol H (210 km/h).",
    sku: "ONA-VULC-TIR-1956515-91H-001",
    mpn: "XMY4-19565R15",
    priceMinor: 4650000,
    qty: 16,
    status: "active",
    attributes: {
      tireWidth: 195,
      aspectRatio: 65,
      rimSize: 15,
      loadIndex: 91,
      speedRating: "H",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "195/65 r15", "195 65 15", "touring"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-205-55r16-91v",
    tradeKey: "vulcanizer",
    categorySlug: "tires",
    subcategorySlug: "passenger-tires",
    brand: { slug: "continental", name: "Continental" },
    name: "Continental ContiSportContact 205/55 R16 91V",
    subtitle: "Performance tyre · 205/55 R16 · Load 91 · Speed V (240 km/h)",
    description:
      "ETRTO-standard 205/55 R16 performance radial. Load index 91 (615 kg), speed symbol V (240 km/h).",
    sku: "ONA-VULC-TIR-2055516-91V-001",
    mpn: "CSC5-20555R16",
    priceMinor: 5250000,
    qty: 14,
    status: "active",
    attributes: {
      tireWidth: 205,
      aspectRatio: 55,
      rimSize: 16,
      loadIndex: 91,
      speedRating: "V",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "205/55 r16", "205 55 16", "performance"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-215-55r17-94v",
    tradeKey: "vulcanizer",
    categorySlug: "tires",
    subcategorySlug: "performance-tires",
    brand: { slug: "michelin", name: "Michelin" },
    name: "Michelin Primacy 4 215/55 R17 94V",
    subtitle: "Touring tyre · 215/55 R17 · Load 94 · Speed V",
    description:
      "ETRTO-standard 215/55 R17 touring radial. Load index 94 (670 kg), speed symbol V (240 km/h).",
    sku: "ONA-VULC-TIR-2155517-94V-001",
    mpn: "PR4-21555R17",
    priceMinor: 6250000,
    qty: 10,
    status: "active",
    attributes: {
      tireWidth: 215,
      aspectRatio: 55,
      rimSize: 17,
      loadIndex: 94,
      speedRating: "V",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "215/55 r17", "215 55 17", "touring"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-225-55r17-97w",
    tradeKey: "vulcanizer",
    categorySlug: "tires",
    subcategorySlug: "suv-tires",
    brand: { slug: "goodyear", name: "Goodyear" },
    name: "Goodyear EfficientGrip 225/55 R17 97W",
    subtitle: "Touring tyre · 225/55 R17 · Load 97 · Speed W (270 km/h)",
    description:
      "ETRTO-standard 225/55 R17 touring radial. Load index 97 (730 kg), speed symbol W (270 km/h).",
    sku: "ONA-VULC-TIR-2255517-97W-001",
    mpn: "EFGR-22555R17",
    priceMinor: 6550000,
    qty: 8,
    status: "active",
    attributes: {
      tireWidth: 225,
      aspectRatio: 55,
      rimSize: 17,
      loadIndex: 97,
      speedRating: "W",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "225/55 r17", "225 55 17", "touring"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-205-65r16-95h",
    tradeKey: "vulcanizer",
    categorySlug: "tires",
    subcategorySlug: "suv-tires",
    brand: { slug: "hankook", name: "Hankook" },
    name: "Hankook Kinergy Eco 205/65 R16 95H",
    subtitle: "SUV / MPV tyre · 205/65 R16 · Load 95 · Speed H",
    description:
      "ETRTO-standard 205/65 R16 tyre for SUVs and MPVs. Load index 95 (690 kg), speed symbol H (210 km/h).",
    sku: "ONA-VULC-TIR-2056516-95H-001",
    mpn: "KINECO-20565R16",
    priceMinor: 4950000,
    qty: 12,
    status: "active",
    attributes: {
      tireWidth: 205,
      aspectRatio: 65,
      rimSize: 16,
      loadIndex: 95,
      speedRating: "H",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "205/65 r16", "205 65 16", "suv"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-lt265-70r16",
    tradeKey: "vulcanizer",
    categorySlug: "truck-bus-tires",
    subcategorySlug: "light-truck-tires",
    brand: { slug: "gt-radial", name: "GT Radial" },
    name: "GT Radial Komodo K05 265/70 R16 LT",
    subtitle: "Light-truck tyre · 265/70 R16 LT · Load 110 · Speed S",
    description:
      "ETRTO-standard light-truck radial. Load index 110 (1060 kg), speed symbol S (180 km/h).",
    sku: "ONA-VULC-TIR-LT2657016-110S-001",
    mpn: "K05-26570R16",
    priceMinor: 7850000,
    qty: 6,
    status: "active",
    attributes: {
      tireWidth: 265,
      aspectRatio: 70,
      rimSize: 16,
      loadIndex: 110,
      speedRating: "S",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "265/70 r16", "light truck", "lt"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-175-80r14-88t",
    tradeKey: "vulcanizer",
    categorySlug: "truck-bus-tires",
    subcategorySlug: "bus-tires",
    brand: { slug: "continental", name: "Continental" },
    name: "Continental VanContact 175/80 R14 88T",
    subtitle: "Van / bus tyre · 175/80 R14 · Load 88 · Speed T",
    description:
      "ETRTO-standard 175/80 R14 van/bus radial. Load index 88 (560 kg), speed symbol T (190 km/h).",
    sku: "ONA-VULC-TIR-1758014-88T-001",
    mpn: "VANC-17580R14",
    priceMinor: 4250000,
    qty: 9,
    status: "active",
    attributes: {
      tireWidth: 175,
      aspectRatio: 80,
      rimSize: 14,
      loadIndex: 88,
      speedRating: "T",
      tubeType: "Tubeless",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "175/80 r14", "van", "bus"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-110-90-16-moto",
    tradeKey: "vulcanizer",
    categorySlug: "motorcycle-tires",
    subcategorySlug: "motorcycle-front-tires",
    brand: { slug: "dunlop", name: "Dunlop" },
    name: "Dunlop TT900 110/90-16 Front",
    subtitle: "Motorcycle front tyre · 110/90-16 · Load 54 · Speed H",
    description:
      "Motorcycle front radial 110/90-16, suited to commuter and touring bikes in Nigeria.",
    sku: "ONA-VULC-TIR-MOTO-1109016-54H-001",
    mpn: "TT900-1109016",
    priceMinor: 2450000,
    qty: 15,
    status: "active",
    attributes: {
      tireWidth: 110,
      aspectRatio: 90,
      rimSize: 16,
      loadIndex: 54,
      speedRating: "H",
      tubeType: "Tube",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "motorcycle", "110/90-16", "110 90 16"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tire-2.75-18-moto-rear",
    tradeKey: "vulcanizer",
    categorySlug: "motorcycle-tires",
    subcategorySlug: "motorcycle-rear-tires",
    brand: { slug: "dunlop", name: "Dunlop" },
    name: "Dunlop 2.75-18 Rear Motorcycle Tyre",
    subtitle: "Motorcycle rear tyre · 2.75-18 · Load 46 · Speed S",
    description:
      "Common Nigerian motorcycle rear size 2.75-18, bias-ply tube-type construction.",
    sku: "ONA-VULC-TIR-MOTO-27518-46S-001",
    mpn: "T875-27518",
    priceMinor: 1950000,
    qty: 20,
    status: "active",
    attributes: {
      tireWidth: 70,
      aspectRatio: 100,
      rimSize: 18,
      loadIndex: 46,
      speedRating: "S",
      tubeType: "Tube",
      material: "Rubber",
    },
    keywords: ["tire", "tyre", "motorcycle", "2.75-18", "27518"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ TUBES ------------------------------
  {
    id: "vulc-tube-r13-tubeless-compat",
    tradeKey: "vulcanizer",
    categorySlug: "tubes",
    subcategorySlug: "passenger-tubes",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Inner Tube 175/70 R13",
    subtitle: "Passenger inner tube · fits 175/70 R13",
    description:
      "Butyl rubber inner tube for 175/70 R13 tubeless-compatible rims. New tube must be used with a new tube-type tyre.",
    sku: "ONA-VULC-TUB-R13-001",
    mpn: "TUBE-17570R13",
    priceMinor: 850000,
    qty: 90,
    status: "active",
    attributes: { rimSize: 13, tubeType: "Tube", material: "Butyl rubber" },
    keywords: ["tube", "inner tube", "r13", "175/70 r13"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tube-r14-passenger",
    tradeKey: "vulcanizer",
    categorySlug: "tubes",
    subcategorySlug: "passenger-tubes",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Inner Tube 185/65 R14",
    subtitle: "Passenger inner tube · fits 185/65 R14",
    description:
      "Butyl rubber inner tube for 185/65 R14 tubeless-compatible rims.",
    sku: "ONA-VULC-TUB-R14-001",
    mpn: "TUBE-18565R14",
    priceMinor: 950000,
    qty: 80,
    status: "active",
    attributes: { rimSize: 14, tubeType: "Tube", material: "Butyl rubber" },
    keywords: ["tube", "inner tube", "r14", "185/65 r14"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-tube-r16-truck",
    tradeKey: "vulcanizer",
    categorySlug: "tubes",
    subcategorySlug: "truck-tubes",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Heavy Truck Tube 7.50-16",
    subtitle: "Truck inner tube · 7.50-16",
    description:
      "Butyl heavy-duty inner tube for 7.50-16 truck tyres. Common on Nigerian bush taxis and pickups.",
    sku: "ONA-VULC-TUB-TRK-75016-001",
    mpn: "TUBE-7.50-16",
    priceMinor: 1650000,
    qty: 25,
    status: "active",
    attributes: { rimSize: 16, tubeType: "Tube", material: "Butyl rubber" },
    keywords: ["tube", "inner tube", "truck", "7.50-16"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ RIMS ------------------------------
  {
    id: "vulc-rim-14-steel-4x100",
    tradeKey: "vulcanizer",
    categorySlug: "rims",
    subcategorySlug: "steel-rims",
    brand: { slug: "enkei", name: "Enkei" },
    name: "Enkei 14-inch Steel Rim 4x100",
    subtitle: "Steel rim · 14\" · 4x100 PCD",
    description:
      "14-inch steel rim, 4x100 bolt pattern, ET38 offset. Suitable for compact passenger cars.",
    sku: "ONA-VULC-RIM-ST-14-4X100-001",
    mpn: "RIM-ST-14-4X100",
    priceMinor: 1850000,
    qty: 22,
    status: "pending_verification",
    attributes: { rimSize: 14, material: "Steel" },
    keywords: ["rim", "steel", "14", "4x100"],
    verificationStatus: "pending",
  },
  {
    id: "vulc-rim-16-alloy-5x114.3",
    tradeKey: "vulcanizer",
    categorySlug: "rims",
    subcategorySlug: "alloy-rims",
    brand: { slug: "enkei", name: "Enkei" },
    name: "Enkei 16-inch Alloy Rim 5x114.3",
    subtitle: "Alloy rim · 16\" · 5x114.3 PCD",
    description:
      "16-inch alloy rim, 5x114.3 bolt pattern. Fits many Japanese SUVs and sedans.",
    sku: "ONA-VULC-RIM-AL-16-5X114-001",
    mpn: "RIM-AL-16-5X114",
    priceMinor: 3850000,
    qty: 10,
    status: "pending_verification",
    attributes: { rimSize: 16, material: "Aluminium" },
    keywords: ["rim", "alloy", "16", "5x114.3"],
    verificationStatus: "pending",
  },

  // ------------------------------ VALVES ------------------------------
  {
    id: "vulc-valve-snapin-tr412",
    tradeKey: "vulcanizer",
    categorySlug: "valves",
    subcategorySlug: "snap-in-valves",
    brand: { slug: "schrader", name: "Schrader" },
    name: "Schrader TR412 Snap-In Tyre Valve (pack of 10)",
    subtitle: "Rubber snap-in valve · TR412 · 10 pcs",
    description:
      "Standard rubber snap-in tubeless valve TR412. Always fit a new valve when fitting a new tubeless tyre.",
    sku: "ONA-VULC-VLV-TR412-010",
    mpn: "TR412",
    priceMinor: 150000,
    qty: 200,
    status: "active",
    attributes: { material: "Rubber" },
    keywords: ["valve", "tyre valve", "snap-in", "tr412"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-valve-core-tool-kit",
    tradeKey: "vulcanizer",
    categorySlug: "valves",
    subcategorySlug: "valve-cores",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Valve Core Tool + 25 valve cores",
    subtitle: "Valve core remover tool · 25 cores",
    description:
      "Valve core removal tool with a pack of 25 brass valve cores — a staple on every vulcanizer bench.",
    sku: "ONA-VULC-VLV-CORE-025",
    mpn: "VLV-CORE-KIT",
    priceMinor: 250000,
    qty: 60,
    status: "active",
    attributes: { material: "Brass" },
    keywords: ["valve", "valve core", "core tool"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ TPMS ------------------------------
  {
    id: "vulc-tpms-sensor-universal",
    tradeKey: "vulcanizer",
    categorySlug: "tpms",
    subcategorySlug: "tpms-sensors",
    brand: { slug: "schrader", name: "Schrader" },
    name: "Schrader TPMS Sensor (programmable)",
    subtitle: "Programmable TPMS sensor · 433 MHz",
    description:
      "433 MHz programmable TPMS sensor, cloned or programmed to vehicle. Sold with service kit.",
    sku: "ONA-VULC-TPMS-PROG-433-001",
    mpn: "TPMS-PROG-433",
    priceMinor: 4200000,
    qty: 15,
    status: "active",
    attributes: { material: "Plastic", tubeType: "Tubeless" },
    keywords: ["tpms", "sensor", "tyre pressure"],
    verificationStatus: "pending",
  },

  // ------------------------------ PATCHES / REPAIR ------------------------------
  {
    id: "vulc-patch-hot-cure-kit",
    tradeKey: "vulcanizer",
    categorySlug: "patches",
    subcategorySlug: "hot-patches",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Hot-Cure Repair Patches (box of 25)",
    subtitle: "Vulcanizing hot patches · assorted sizes",
    description:
      "Box of 25 hot-cure (vulcanizing) patches in assorted sizes for repairing radial tyre sections and tubes.",
    sku: "ONA-VULC-PTH-HOT-025",
    mpn: "PATCH-HOT-25",
    priceMinor: 420000,
    qty: 120,
    status: "active",
    attributes: { material: "Rubber" },
    keywords: ["patch", "hot patch", "vulcanizing", "repair"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-plug-tyre-strings-100",
    tradeKey: "vulcanizer",
    categorySlug: "tire-repair",
    subcategorySlug: "puncture-repair-kits",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Tubeless Tyre Plug Kit (100 strings)",
    subtitle: "Tubeless puncture plugs · 100 strings + tools",
    description:
      "Self-vulcanizing tubeless tyre plug strings with insertion tool. For rapid roadside puncture repairs.",
    sku: "ONA-VULC-PLG-100-001",
    mpn: "PLUG-KIT-100",
    priceMinor: 320000,
    qty: 0,
    status: "inactive",
    attributes: { tubeType: "Tubeless", material: "Rubber" },
    keywords: ["plug", "puncture", "tubeless", "repair kit"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-patch-cold-selfvulc-100",
    tradeKey: "vulcanizer",
    categorySlug: "tire-repair",
    subcategorySlug: "puncture-repair-kits",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Cold Vulcanizing Patch Kit (100 pcs)",
    subtitle: "Cold patches · assorted sizes · 100 pcs",
    description:
      "Cold-vulcanizing patches with rubber cement for tube and tyre repair.",
    sku: "ONA-VULC-PTH-COLD-100",
    mpn: "PATCH-COLD-100",
    priceMinor: 380000,
    qty: 85,
    status: "active",
    attributes: { material: "Rubber" },
    keywords: ["patch", "cold patch", "repair", "vulcanizing"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ VULCANIZING MATERIALS ------------------------------
  {
    id: "vulc-mat-cement-500ml",
    tradeKey: "vulcanizer",
    categorySlug: "vulcanizing-materials",
    subcategorySlug: "vulcanizing-cement",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Vulcanizing Cement 500ml",
    subtitle: "Rubber-to-rubber bonding cement · 500ml",
    description:
      "Cold vulcanizing cement for bonding patches to tyres and tubes. 500ml tin.",
    sku: "ONA-VULC-MAT-CEM-500",
    mpn: "VULC-CEM-500",
    priceMinor: 350000,
    qty: 140,
    status: "active",
    attributes: { material: "Rubber cement" },
    keywords: ["vulcanizing", "cement", "rubber cement", "glue"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-mat-gum-cushion-roll",
    tradeKey: "vulcanizer",
    categorySlug: "vulcanizing-materials",
    subcategorySlug: "cushion-gum",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Cushion Gum Roll (uncured)",
    subtitle: "Uncured cushion gum · 1m roll",
    description:
      "Uncured cushion gum for section repairs and retreading build-up.",
    sku: "ONA-VULC-MAT-GUM-ROLL-001",
    mpn: "CUSHION-GUM-1M",
    priceMinor: 550000,
    qty: 40,
    status: "active",
    attributes: { material: "Uncured rubber" },
    keywords: ["cushion gum", "repair gum", "uncured rubber"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ VULCANIZING EQUIPMENT ------------------------------
  {
    id: "vulc-eqp-spot-vulcanizer",
    tradeKey: "vulcanizer",
    categorySlug: "vulcanizing-equipment",
    subcategorySlug: "spot-vulcanizers",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Electric Spot Vulcanizer (1200W)",
    subtitle: "1200W spot vulcanizer · for tubes and carcass repairs",
    description:
      "Bench-top electric spot vulcanizer for tube and tyre carcass repair. 1200W, 220–240V.",
    sku: "ONA-VULC-EQP-SPOT-1200",
    mpn: "SPOT-VULC-1200",
    priceMinor: 1850000,
    qty: 0,
    status: "future_product",
    attributes: { voltage: 220, material: "Metal" },
    keywords: ["vulcanizer", "spot", "machine", "repair"],
    verificationStatus: "pending",
  },
  {
    id: "vulc-eqp-heat-pad-15x20",
    tradeKey: "vulcanizer",
    categorySlug: "vulcanizing-equipment",
    subcategorySlug: "heat-curing-pads",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Heat Curing Pad 15x20cm",
    subtitle: "Rubber heat curing pad · 15×20 cm",
    description:
      "Heat curing pad for patch and section curing at the vulcanizing bench.",
    sku: "ONA-VULC-EQP-PAD-1520",
    mpn: "HEATPAD-15X20",
    priceMinor: 750000,
    qty: 12,
    status: "active",
    attributes: { material: "Rubber" },
    keywords: ["heat pad", "curing", "vulcanizing"],
    verificationStatus: "pending",
  },

  // ------------------------------ TIRE CHANGERS ------------------------------
  {
    id: "vulc-changer-manual-single",
    tradeKey: "vulcanizer",
    categorySlug: "tire-changers",
    subcategorySlug: "manual-tire-changers",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Manual Tyre Changer (single arm)",
    subtitle: "Manual tyre changer · passenger rims 12–16\"",
    description:
      "Manual single-arm tyre changer for passenger and light commercial rims.",
    sku: "ONA-VULC-CHG-MAN-001",
    mpn: "CHG-MAN-1",
    priceMinor: 1450000,
    qty: 5,
    status: "active",
    attributes: { material: "Steel" },
    keywords: ["tyre changer", "tire changer", "manual", "machine"],
    verificationStatus: "pending",
  },

  // ------------------------------ BEAD BREAKERS ------------------------------
  {
    id: "vulc-bead-breaker-manual",
    tradeKey: "vulcanizer",
    categorySlug: "bead-breakers",
    subcategorySlug: "manual-bead-breakers",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Manual Bead Breaker",
    subtitle: "Foot-operated bead breaker",
    description:
      "Foot-operated manual bead breaker for passenger and light truck tyres.",
    sku: "ONA-VULC-BEAD-MAN-001",
    mpn: "BEAD-MAN-1",
    priceMinor: 950000,
    qty: 7,
    status: "active",
    attributes: { material: "Steel" },
    keywords: ["bead breaker", "bead", "manual"],
    verificationStatus: "pending",
  },

  // ------------------------------ COMPRESSORS ------------------------------
  {
    id: "vulc-comp-50l-single",
    tradeKey: "vulcanizer",
    categorySlug: "compressors",
    subcategorySlug: "garage-compressors",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Air Compressor 50L 1.5HP",
    subtitle: "50-litre single-cylinder compressor · 1.5 HP",
    description:
      "50-litre single-cylinder air compressor, 1.5 HP, for tyre inflation and air tools.",
    sku: "ONA-VULC-CMP-50L-15HP",
    mpn: "CMP-50L-1.5",
    priceMinor: 2450000,
    qty: 9,
    status: "active",
    attributes: { voltage: 220, capacity: 50, powerW: 1100 },
    keywords: ["compressor", "air", "inflation"],
    verificationStatus: "pending",
  },
  {
    id: "vulc-comp-100l-twin",
    tradeKey: "vulcanizer",
    categorySlug: "compressors",
    subcategorySlug: "twin-cylinder-compressors",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Twin-Cylinder Compressor 100L 3HP",
    subtitle: "100-litre twin-cylinder compressor · 3 HP",
    description:
      "100-litre twin-cylinder compressor, 3 HP, for heavy workshop use.",
    sku: "ONA-VULC-CMP-100L-3HP",
    mpn: "CMP-100L-3",
    priceMinor: 4250000,
    qty: 4,
    status: "future_product",
    attributes: { voltage: 220, capacity: 100, powerW: 2200 },
    keywords: ["compressor", "air", "twin cylinder"],
    verificationStatus: "pending",
  },

  // ------------------------------ INFLATION & GAUGES ------------------------------
  {
    id: "vulc-gauge-digital-inflator",
    tradeKey: "vulcanizer",
    categorySlug: "tire-inflation",
    subcategorySlug: "digital-inflators",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Digital Tyre Inflator Gauge",
    subtitle: "Digital gauge + inflator · up to 150 PSI",
    description:
      "Digital tyre inflator gauge with chuck, reads 0–150 PSI.",
    sku: "ONA-VULC-GAUGE-DIG-150",
    mpn: "GAUGE-DIG-150",
    priceMinor: 280000,
    qty: 55,
    status: "active",
    attributes: { pressure: 150, material: "Plastic" },
    keywords: ["gauge", "inflator", "pressure", "digital"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-gauge-pencil-mech",
    tradeKey: "vulcanizer",
    categorySlug: "tire-inflation",
    subcategorySlug: "tyre-pressure-gauges",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Pencil Tyre Pressure Gauge",
    subtitle: "Mechanical pencil gauge · 0–80 PSI",
    description:
      "Mechanical pencil-type tyre pressure gauge, 0–80 PSI.",
    sku: "ONA-VULC-GAUGE-PENCIL-080",
    mpn: "GAUGE-PEN-80",
    priceMinor: 120000,
    qty: 110,
    status: "active",
    attributes: { pressure: 80, material: "Metal" },
    keywords: ["gauge", "pressure", "pencil"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ BALANCING ------------------------------
  {
    id: "vulc-balancer-semi-auto",
    tradeKey: "vulcanizer",
    categorySlug: "balancing",
    subcategorySlug: "wheel-balancers-semi",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Semi-Automatic Wheel Balancer",
    subtitle: "Semi-automatic balancer · passenger & LT rims",
    description:
      "Semi-automatic wheel balancer with spin indicator for passenger and light truck wheels.",
    sku: "ONA-VULC-BAL-SEMI-001",
    mpn: "BAL-SEMI-1",
    priceMinor: 1650000,
    qty: 3,
    status: "future_product",
    attributes: { material: "Steel" },
    keywords: ["balancer", "balancing", "machine"],
    verificationStatus: "pending",
  },
  {
    id: "vulc-weight-adhesive-25g",
    tradeKey: "vulcanizer",
    categorySlug: "balance-weights",
    subcategorySlug: "adhesive-weights",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Adhesive Wheel Weights 25g (box of 50)",
    subtitle: "Self-adhesive balance weights · 25g",
    description:
      "Box of 50 self-adhesive zinc wheel balance weights, 25 g each.",
    sku: "ONA-VULC-WGT-ADH-25G-050",
    mpn: "WGT-ADH-25",
    priceMinor: 300000,
    qty: 75,
    status: "active",
    attributes: { material: "Zinc" },
    keywords: ["balance weight", "wheel weight", "adhesive"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ ALIGNMENT ------------------------------
  {
    id: "vulc-align-camber-bolt-kit",
    tradeKey: "vulcanizer",
    categorySlug: "alignment",
    subcategorySlug: "camber-kits",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Camber Adjustment Bolt Kit",
    subtitle: "Camber bolts · M12 x 1.25 · pair",
    description:
      "Pair of M12 x 1.25 camber adjustment bolts for strut-style front suspensions.",
    sku: "ONA-VULC-ALIGN-CMB-M12",
    mpn: "ALIGN-CAMBER-M12",
    priceMinor: 220000,
    qty: 45,
    status: "active",
    attributes: { material: "Steel" },
    keywords: ["alignment", "camber", "bolt"],
    verificationStatus: "pending",
  },

  // ------------------------------ TYRE LEVERS & TOOLS ------------------------------
  {
    id: "vulc-lever-set-30cm",
    tradeKey: "vulcanizer",
    categorySlug: "tire-levers",
    subcategorySlug: "tyre-levers",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Tyre Lever Set 30cm (pair)",
    subtitle: "Forged steel tyre levers · 30cm pair",
    description:
      "Pair of 30 cm forged steel tyre levers for manual demounting.",
    sku: "ONA-VULC-LEVER-30CM-PAIR",
    mpn: "LEVER-30-PAIR",
    priceMinor: 150000,
    qty: 95,
    status: "active",
    attributes: { material: "Steel" },
    keywords: ["lever", "tyre lever", "tool"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-mallet-rubber-1kg",
    tradeKey: "vulcanizer",
    categorySlug: "tire-levers",
    subcategorySlug: "mounting-hammers",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Rubber Mallet 1kg",
    subtitle: "Rubber-headed mallet · 1 kg",
    description:
      "1 kg rubber-headed mallet for seating tyre beads during mounting.",
    sku: "ONA-VULC-MALLET-1KG-001",
    mpn: "MALLET-1KG",
    priceMinor: 190000,
    qty: 65,
    status: "active",
    attributes: { material: "Rubber" },
    keywords: ["mallet", "hammer", "mounting"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ BUFFING ------------------------------
  {
    id: "vulc-buff-hand-rasp-set",
    tradeKey: "vulcanizer",
    categorySlug: "tire-buffers",
    subcategorySlug: "hand-rasps",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Hand Rasp Set for Repair Buffing",
    subtitle: "Hand rasps · 3 pcs",
    description:
      "Set of three hand rasps for cleaning and buffing repair areas before patching.",
    sku: "ONA-VULC-BUFF-RASP-003",
    mpn: "RASP-SET-3",
    priceMinor: 260000,
    qty: 70,
    status: "active",
    attributes: { material: "Steel" },
    keywords: ["rasp", "buff", "repair tool"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ POWER TOOLS ------------------------------
  {
    id: "vulc-impact-wrench-1in",
    tradeKey: "vulcanizer",
    categorySlug: "power-tools",
    subcategorySlug: "impact-wrenches",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro 1-inch Impact Wrench",
    subtitle: "Air impact wrench · 1\" drive · 1200 Nm",
    description:
      "1-inch air impact wrench, 1200 Nm, for truck wheel nuts.",
    sku: "ONA-VULC-PWR-IMP-1IN",
    mpn: "IMPACT-1IN",
    priceMinor: 1250000,
    qty: 8,
    status: "active",
    attributes: { material: "Metal" },
    keywords: ["impact wrench", "air tool", "nut remover"],
    verificationStatus: "pending",
  },

  // ------------------------------ GARAGE EQUIPMENT ------------------------------
  {
    id: "vulc-jack-3t-trolley",
    tradeKey: "vulcanizer",
    categorySlug: "garage-equipment",
    subcategorySlug: "trolley-jacks",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro 3-Ton Trolley Jack",
    subtitle: "3-ton hydraulic trolley jack",
    description:
      "3-ton hydraulic trolley jack with lifting range for passenger and light trucks.",
    sku: "ONA-VULC-JACK-3T-001",
    mpn: "JACK-3T",
    priceMinor: 2350000,
    qty: 0,
    status: "discontinued",
    attributes: { capacity: 3000, material: "Steel" },
    keywords: ["jack", "trolley", "hydraulic"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-stand-pair-3t",
    tradeKey: "vulcanizer",
    categorySlug: "garage-equipment",
    subcategorySlug: "axle-stands",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Axle Stands (pair, 3-ton)",
    subtitle: "Adjustable axle stands · 3-ton pair",
    description:
      "Pair of adjustable 3-ton axle stands for safe under-vehicle work.",
    sku: "ONA-VULC-STAND-3T-PAIR",
    mpn: "AXLE-STAND-3T",
    priceMinor: 1650000,
    qty: 12,
    status: "active",
    attributes: { capacity: 3000, material: "Steel" },
    keywords: ["stand", "axle stand", "jack"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ TYRE CARE ------------------------------
  {
    id: "vulc-care-dressing-500ml",
    tradeKey: "vulcanizer",
    categorySlug: "tire-care-chemicals",
    subcategorySlug: "tyre-dressing",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Tyre Dressing 500ml",
    subtitle: "Water-based tyre dressing · 500ml",
    description:
      "Water-based tyre dressing that restores a clean satin-black finish without greasy residue.",
    sku: "ONA-VULC-CARE-DRESS-500",
    mpn: "TYRE-DRESS-500",
    priceMinor: 280000,
    qty: 130,
    status: "active",
    attributes: { material: "Liquid" },
    keywords: ["tyre dressing", "tire shine", "care"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-care-bead-lube-1kg",
    tradeKey: "vulcanizer",
    categorySlug: "tire-care-chemicals",
    subcategorySlug: "bead-lubricant",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Bead Lubricant / Mounting Paste 1kg",
    subtitle: "Tyre mounting lubricant · 1kg tub",
    description:
      "Bead lubricant and mounting paste that prevents bead and rim damage during mounting.",
    sku: "ONA-VULC-CARE-BEADLUBE-1KG",
    mpn: "BEAD-LUBE-1KG",
    priceMinor: 220000,
    qty: 95,
    status: "active",
    attributes: { material: "Paste" },
    keywords: ["bead lubricant", "mounting paste", "tyre mounting"],
    verificationStatus: "source_verified",
  },

  // ------------------------------ SAFETY / PPE ------------------------------
  {
    id: "vulc-ppe-gloves-nitrile",
    tradeKey: "vulcanizer",
    categorySlug: "safety-ppe",
    subcategorySlug: "safety-gloves",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Nitrile Work Gloves (box of 100)",
    subtitle: "Nitrile gloves · heavy-duty · 100 pcs",
    description:
      "Heavy-duty nitrile gloves for handling cement, patches and cleaning chemicals.",
    sku: "ONA-VULC-PPE-NIT-100",
    mpn: "PPE-NITRILE-100",
    priceMinor: 450000,
    qty: 60,
    status: "active",
    attributes: { material: "Nitrile" },
    keywords: ["gloves", "ppe", "nitrile"],
    verificationStatus: "source_verified",
  },
  {
    id: "vulc-ppe-goggles",
    tradeKey: "vulcanizer",
    categorySlug: "safety-ppe",
    subcategorySlug: "safety-glasses",
    brand: { slug: "ona-pro", name: "Ona Pro" },
    name: "Ona Pro Safety Glasses",
    subtitle: "Impact-rated safety glasses",
    description:
      "Impact-rated clear safety glasses for grinding and buffing work.",
    sku: "ONA-VULC-PPE-GOG-001",
    mpn: "PPE-GOGGLE-1",
    priceMinor: 90000,
    qty: 85,
    status: "active",
    attributes: { material: "Plastic" },
    keywords: ["goggles", "safety glasses", "ppe"],
    verificationStatus: "source_verified",
  },
];

export function vulcanizerProductCount(): number {
  return VULCANIZER_PRODUCTS.length;
}